fail_fast: true
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-yaml
      - id: mixed-line-ending
      - id: end-of-file-fixer
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v22.1.0
    hooks:
    - id: clang-format
      name: format .cpp & .h with clang-format
  - repo: https://github.com/zultron/cmake-format-precommit
    rev: v0.6.14
    hooks:
      - id: cmake-format
