/*----- PROTECTED REGION ID(SlsDetectorControlClass.cpp) ENABLED START -----*/
/* clang-format on */
//=============================================================================
//
// file :        SlsDetectorControlClass.cpp
//
// description : C++ source for the SlsDetectorControlClass.
//               A singleton class derived from DeviceClass.
//               It implements the command and attribute list
//               and all properties and methods required
//               by the SlsDetectorControl once per process.
//
// project :     tango-slsdetectorcontrol
//
// This file is part of Tango device class.
//
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the MIT licence.
//
//
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================

#include "SlsDetectorControlClass.h"
/* clang-format off */
/*----- PROTECTED REGION END -----*/	//	SlsDetectorControlClass.cpp

//-------------------------------------------------------------------
/**
 *	Create SlsDetectorControlClass singleton and
 *	return it in a C function for Python usage
 */
//-------------------------------------------------------------------
extern "C" {
#ifdef _TG_WINDOWS_

__declspec(dllexport)

#endif

	Tango::DeviceClass *_create_SlsDetectorControl_class(const char *name) {
		return SlsDetectorControl_ns::SlsDetectorControlClass::init(name);
	}
}

namespace SlsDetectorControl_ns
{
//===================================================================
//	Initialize pointer for singleton pattern
//===================================================================
SlsDetectorControlClass *SlsDetectorControlClass::_instance = NULL;

//===================================================================
//	Class constants
//===================================================================
constexpr long num_missing_packetsAttrib::X_DATA_SIZE;
//--------------------------------------------------------
/**
 * method : 		SlsDetectorControlClass::SlsDetectorControlClass(std::string &s)
 * description : 	constructor for the SlsDetectorControlClass
 *
 * @param s	The class name
 */
//--------------------------------------------------------
SlsDetectorControlClass::SlsDetectorControlClass(std::string &s):Tango::DeviceClass(s)
{
	TANGO_LOG_INFO << "Entering SlsDetectorControlClass constructor" << std::endl;
	set_default_property();
	write_class_property();

	/*----- PROTECTED REGION ID(SlsDetectorControlClass::constructor) ENABLED START -----*/
    /* clang-format on */
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControlClass::constructor

	TANGO_LOG_INFO << "Leaving SlsDetectorControlClass constructor" << std::endl;
}

//--------------------------------------------------------
/**
 * method : 		SlsDetectorControlClass::~SlsDetectorControlClass()
 * description : 	destructor for the SlsDetectorControlClass
 */
//--------------------------------------------------------
SlsDetectorControlClass::~SlsDetectorControlClass()
{
	/*----- PROTECTED REGION ID(SlsDetectorControlClass::destructor) ENABLED START -----*/
    /* clang-format on */
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControlClass::destructor

	_instance = NULL;
}


//--------------------------------------------------------
/**
 * method : 		SlsDetectorControlClass::init
 * description : 	Create the object if not already done.
 *                  Otherwise, just return a pointer to the object
 *
 * @param	name	The class name
 */
//--------------------------------------------------------
SlsDetectorControlClass *SlsDetectorControlClass::init(const char *name)
{
	if (_instance == NULL)
	{
		try
		{
			std::string s(name);
			_instance = new SlsDetectorControlClass(s);
		}
		catch (std::bad_alloc &)
		{
			throw;
		}
	}
	return _instance;
}

//--------------------------------------------------------
/**
 * method : 		SlsDetectorControlClass::instance
 * description : 	Check if object already created,
 *                  and return a pointer to the object
 */
//--------------------------------------------------------
SlsDetectorControlClass *SlsDetectorControlClass::instance()
{
	if (_instance == NULL)
	{
		std::cerr << "Class is not initialised !!" << std::endl;
		exit(-1);
	}
	return _instance;
}



//===================================================================
//	Command execution method calls
//===================================================================
//--------------------------------------------------------
/**
 * method : 		start_acquireClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *start_acquireClass::execute(Tango::DeviceImpl *device, TANGO_UNUSED(const CORBA::Any &in_any))
{
	TANGO_LOG_INFO << "start_acquireClass::execute(): arrived" << std::endl;
	((static_cast<SlsDetectorControl *>(device))->start_acquire());
	return new CORBA::Any();
}

//--------------------------------------------------------
/**
 * method : 		start_detectorClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *start_detectorClass::execute(Tango::DeviceImpl *device, TANGO_UNUSED(const CORBA::Any &in_any))
{
	TANGO_LOG_INFO << "start_detectorClass::execute(): arrived" << std::endl;
	((static_cast<SlsDetectorControl *>(device))->start_detector());
	return new CORBA::Any();
}

//--------------------------------------------------------
/**
 * method : 		start_receiverClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *start_receiverClass::execute(Tango::DeviceImpl *device, TANGO_UNUSED(const CORBA::Any &in_any))
{
	TANGO_LOG_INFO << "start_receiverClass::execute(): arrived" << std::endl;
	((static_cast<SlsDetectorControl *>(device))->start_receiver());
	return new CORBA::Any();
}

//--------------------------------------------------------
/**
 * method : 		stop_acquireClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *stop_acquireClass::execute(Tango::DeviceImpl *device, TANGO_UNUSED(const CORBA::Any &in_any))
{
	TANGO_LOG_INFO << "stop_acquireClass::execute(): arrived" << std::endl;
	((static_cast<SlsDetectorControl *>(device))->stop_acquire());
	return new CORBA::Any();
}

//--------------------------------------------------------
/**
 * method : 		stop_detectorClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *stop_detectorClass::execute(Tango::DeviceImpl *device, TANGO_UNUSED(const CORBA::Any &in_any))
{
	TANGO_LOG_INFO << "stop_detectorClass::execute(): arrived" << std::endl;
	((static_cast<SlsDetectorControl *>(device))->stop_detector());
	return new CORBA::Any();
}

//--------------------------------------------------------
/**
 * method : 		stop_receiverClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *stop_receiverClass::execute(Tango::DeviceImpl *device, TANGO_UNUSED(const CORBA::Any &in_any))
{
	TANGO_LOG_INFO << "stop_receiverClass::execute(): arrived" << std::endl;
	((static_cast<SlsDetectorControl *>(device))->stop_receiver());
	return new CORBA::Any();
}

//--------------------------------------------------------
/**
 * method : 		load_trimbitsClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *load_trimbitsClass::execute(Tango::DeviceImpl *device, const CORBA::Any &in_any)
{
	TANGO_LOG_INFO << "load_trimbitsClass::execute(): arrived" << std::endl;
	Tango::DevString argin;
	extract(in_any, argin);
	((static_cast<SlsDetectorControl *>(device))->load_trimbits(argin, *this));
	return new CORBA::Any();
}


//===================================================================
//	Properties management
//===================================================================
//--------------------------------------------------------
/**
 *	Method      : SlsDetectorControlClass::get_class_property()
 * Description:  Get the class property for specified name.
 */
//--------------------------------------------------------
Tango::DbDatum SlsDetectorControlClass::get_class_property(std::string &prop_name)
{
	for (unsigned int i=0 ; i<cl_prop.size() ; i++)
		if (cl_prop[i].name == prop_name)
			return cl_prop[i];
	//	if not found, returns  an empty DbDatum
	return Tango::DbDatum(prop_name);
}

//--------------------------------------------------------
/**
 *	Method      : SlsDetectorControlClass::get_default_device_property()
 * Description:  Return the default value for device property.
 */
//--------------------------------------------------------
Tango::DbDatum SlsDetectorControlClass::get_default_device_property(std::string &prop_name)
{
	for (unsigned int i=0 ; i<dev_def_prop.size() ; i++)
		if (dev_def_prop[i].name == prop_name)
			return dev_def_prop[i];
	//	if not found, return  an empty DbDatum
	return Tango::DbDatum(prop_name);
}

//--------------------------------------------------------
/**
 *	Method      : SlsDetectorControlClass::get_default_class_property()
 * Description:  Return the default value for class property.
 */
//--------------------------------------------------------
Tango::DbDatum SlsDetectorControlClass::get_default_class_property(std::string &prop_name)
{
	for (unsigned int i=0 ; i<cl_def_prop.size() ; i++)
		if (cl_def_prop[i].name == prop_name)
			return cl_def_prop[i];
	//	if not found, return  an empty DbDatum
	return Tango::DbDatum(prop_name);
}


//--------------------------------------------------------
/**
 *	Method      : SlsDetectorControlClass::set_default_property()
 * Description:  Set default property (class and device) for wizard.
 *                For each property, add to wizard property name and description.
 *                If default value has been set, add it to wizard property and
 *                store it in a DbDatum.
 */
//--------------------------------------------------------
void SlsDetectorControlClass::set_default_property()
{
	std::string	prop_name;
	std::string	prop_desc;
	std::string	prop_def;
	std::vector<std::string>	vect_data;

	//	Set Default Class Properties

	//	Set Default device Properties
	prop_name = "ConfigurationPathDevString";
	prop_desc = "Config file for Detector and Receiver objects from the slsDetectorPackage.";
	prop_def  = "";
	vect_data.clear();
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "DetectorId";
	prop_desc = "Detector shared memory id Default value is 0. Can be set to more values for multiple detectors.It is important only if you are controlling multiple detectors from the same pc.";
	prop_def  = "0";
	vect_data.clear();
	vect_data.push_back("0");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "GainMapPaths";
	prop_desc = "Gain map files for each module.";
	prop_def  = "";
	vect_data.clear();
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "PixelMaskPaths";
	prop_desc = "Pixel map files for each module.";
	prop_def  = "";
	vect_data.clear();
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
}

//--------------------------------------------------------
/**
 *	Method      : SlsDetectorControlClass::write_class_property()
 * Description:  Set class description fields as property in database
 */
//--------------------------------------------------------
void SlsDetectorControlClass::write_class_property()
{
//	First time, check if database used
if (Tango::Util::_UseDb == false)
	return;

Tango::DbData	data;
std::string	classname = get_name();
std::string	header;

//	Put title
Tango::DbDatum	title("ProjectTitle");
std::string	str_title("tango-slsdetectorcontrol");
title << str_title;
data.push_back(title);

//	Put Description
Tango::DbDatum	description("Description");
std::vector<std::string>	str_desc;
str_desc.push_back("");
description << str_desc;
data.push_back(description);

//  Put inheritance
Tango::DbDatum	inher_datum("InheritedFrom");
std::vector<std::string> inheritance;
inheritance.push_back("TANGO_BASE_CLASS");
inher_datum << inheritance;
data.push_back(inher_datum);

//	Call database and and values
get_db_class()->put_property(data);
}

//===================================================================
//	Factory methods
//===================================================================

//--------------------------------------------------------
/**
 *	Method      : SlsDetectorControlClass::device_factory()
 * Description:  Create the device object(s)
 *                and store them in the device list
 */
//--------------------------------------------------------
void SlsDetectorControlClass::device_factory(const Tango::DevVarStringArray *devlist_ptr)
{
/*----- PROTECTED REGION ID(SlsDetectorControlClass::device_factory_before) ENABLED START -----*/
    /* clang-format on */
    //	Add your own code
    /* clang-format off */
/*----- PROTECTED REGION END -----*/	//	SlsDetectorControlClass::device_factory_before

//	Create devices and add it into the device list
for (unsigned long i=0 ; i<devlist_ptr->length() ; i++)
{
	TANGO_LOG_DEBUG << "Device name : " << (*devlist_ptr)[i].in() << std::endl;
	device_list.push_back(new SlsDetectorControl(this, (*devlist_ptr)[i]));
}

//	Manage dynamic attributes if any
erase_dynamic_attributes(devlist_ptr, get_class_attr()->get_attr_list());

//	Export devices to the outside world
for (unsigned long i=1 ; i<=devlist_ptr->length() ; i++)
{
	//	Add dynamic attributes if any
	SlsDetectorControl *dev = static_cast<SlsDetectorControl *>(device_list[device_list.size()-i]);
	dev->add_dynamic_attributes();
	dev->add_dynamic_commands();

	//	Check before if database used.
	if ((Tango::Util::_UseDb == true) && (Tango::Util::_FileDb == false))
		export_device(dev);
	else
		export_device(dev, dev->get_name().c_str());
}

/*----- PROTECTED REGION ID(SlsDetectorControlClass::device_factory_after) ENABLED START -----*/
    /* clang-format on */
    //	Add your own code
    /* clang-format off */
/*----- PROTECTED REGION END -----*/	//	SlsDetectorControlClass::device_factory_after
}
//--------------------------------------------------------
/**
 *	Method      : SlsDetectorControlClass::attribute_factory()
 * Description:  Create the attribute object(s)
 *                and store them in the attribute list
 */
//--------------------------------------------------------
void SlsDetectorControlClass::attribute_factory(std::vector<Tango::Attr *> &att_list)
{
	/*----- PROTECTED REGION ID(SlsDetectorControlClass::attribute_factory_before) ENABLED START -----*/
    /* clang-format on */
    //	Add your own code
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControlClass::attribute_factory_before
	//	Attribute : acquisition_index
	acquisition_indexAttrib	*acquisition_index = new acquisition_indexAttrib();
	Tango::UserDefaultAttrProp	acquisition_index_prop;
	//	description	not set for acquisition_index
	//	label	not set for acquisition_index
	//	unit	not set for acquisition_index
	//	standard_unit	not set for acquisition_index
	//	display_unit	not set for acquisition_index
	//	format	not set for acquisition_index
	//	max_value	not set for acquisition_index
	//	min_value	not set for acquisition_index
	//	max_alarm	not set for acquisition_index
	//	min_alarm	not set for acquisition_index
	//	max_warning	not set for acquisition_index
	//	min_warning	not set for acquisition_index
	//	delta_t	not set for acquisition_index
	//	delta_val	not set for acquisition_index
	acquisition_index->set_default_properties(acquisition_index_prop);
	//	Not Polled
	acquisition_index->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(acquisition_index);

	//	Attribute : detector_type
	detector_typeAttrib	*detector_type = new detector_typeAttrib();
	Tango::UserDefaultAttrProp	detector_type_prop;
	//	description	not set for detector_type
	//	label	not set for detector_type
	//	unit	not set for detector_type
	//	standard_unit	not set for detector_type
	//	display_unit	not set for detector_type
	//	format	not set for detector_type
	//	max_value	not set for detector_type
	//	min_value	not set for detector_type
	//	max_alarm	not set for detector_type
	//	min_alarm	not set for detector_type
	//	max_warning	not set for detector_type
	//	min_warning	not set for detector_type
	//	delta_t	not set for detector_type
	//	delta_val	not set for detector_type
	detector_type->set_default_properties(detector_type_prop);
	//	Not Polled
	detector_type->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(detector_type);

	//	Attribute : dynamic_range
	dynamic_rangeAttrib	*dynamic_range = new dynamic_rangeAttrib();
	Tango::UserDefaultAttrProp	dynamic_range_prop;
	//	description	not set for dynamic_range
	//	label	not set for dynamic_range
	//	unit	not set for dynamic_range
	//	standard_unit	not set for dynamic_range
	//	display_unit	not set for dynamic_range
	//	format	not set for dynamic_range
	//	max_value	not set for dynamic_range
	//	min_value	not set for dynamic_range
	//	max_alarm	not set for dynamic_range
	//	min_alarm	not set for dynamic_range
	//	max_warning	not set for dynamic_range
	//	min_warning	not set for dynamic_range
	//	delta_t	not set for dynamic_range
	//	delta_val	not set for dynamic_range
	dynamic_range->set_default_properties(dynamic_range_prop);
	//	Not Polled
	dynamic_range->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(dynamic_range);

	//	Attribute : exptime
	exptimeAttrib	*exptime = new exptimeAttrib();
	Tango::UserDefaultAttrProp	exptime_prop;
	//	description	not set for exptime
	//	label	not set for exptime
	exptime_prop.set_unit("s");
	//	standard_unit	not set for exptime
	//	display_unit	not set for exptime
	exptime_prop.set_format("%5.2e");
	//	max_value	not set for exptime
	//	min_value	not set for exptime
	//	max_alarm	not set for exptime
	//	min_alarm	not set for exptime
	//	max_warning	not set for exptime
	//	min_warning	not set for exptime
	//	delta_t	not set for exptime
	//	delta_val	not set for exptime
	exptime->set_default_properties(exptime_prop);
	//	Not Polled
	exptime->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(exptime);

	//	Attribute : file_name
	file_nameAttrib	*file_name = new file_nameAttrib();
	Tango::UserDefaultAttrProp	file_name_prop;
	//	description	not set for file_name
	//	label	not set for file_name
	//	unit	not set for file_name
	//	standard_unit	not set for file_name
	//	display_unit	not set for file_name
	//	format	not set for file_name
	//	max_value	not set for file_name
	//	min_value	not set for file_name
	//	max_alarm	not set for file_name
	//	min_alarm	not set for file_name
	//	max_warning	not set for file_name
	//	min_warning	not set for file_name
	//	delta_t	not set for file_name
	//	delta_val	not set for file_name
	file_name->set_default_properties(file_name_prop);
	//	Not Polled
	file_name->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(file_name);

	//	Attribute : file_name_prefix
	file_name_prefixAttrib	*file_name_prefix = new file_name_prefixAttrib();
	Tango::UserDefaultAttrProp	file_name_prefix_prop;
	//	description	not set for file_name_prefix
	//	label	not set for file_name_prefix
	//	unit	not set for file_name_prefix
	//	standard_unit	not set for file_name_prefix
	//	display_unit	not set for file_name_prefix
	//	format	not set for file_name_prefix
	//	max_value	not set for file_name_prefix
	//	min_value	not set for file_name_prefix
	//	max_alarm	not set for file_name_prefix
	//	min_alarm	not set for file_name_prefix
	//	max_warning	not set for file_name_prefix
	//	min_warning	not set for file_name_prefix
	//	delta_t	not set for file_name_prefix
	//	delta_val	not set for file_name_prefix
	file_name_prefix->set_default_properties(file_name_prefix_prop);
	//	Not Polled
	file_name_prefix->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(file_name_prefix);

	//	Attribute : file_overwrite
	file_overwriteAttrib	*file_overwrite = new file_overwriteAttrib();
	Tango::UserDefaultAttrProp	file_overwrite_prop;
	//	description	not set for file_overwrite
	//	label	not set for file_overwrite
	//	unit	not set for file_overwrite
	//	standard_unit	not set for file_overwrite
	//	display_unit	not set for file_overwrite
	//	format	not set for file_overwrite
	//	max_value	not set for file_overwrite
	//	min_value	not set for file_overwrite
	//	max_alarm	not set for file_overwrite
	//	min_alarm	not set for file_overwrite
	//	max_warning	not set for file_overwrite
	//	min_warning	not set for file_overwrite
	//	delta_t	not set for file_overwrite
	//	delta_val	not set for file_overwrite
	file_overwrite->set_default_properties(file_overwrite_prop);
	//	Not Polled
	file_overwrite->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(file_overwrite);

	//	Attribute : file_path
	file_pathAttrib	*file_path = new file_pathAttrib();
	Tango::UserDefaultAttrProp	file_path_prop;
	//	description	not set for file_path
	//	label	not set for file_path
	//	unit	not set for file_path
	//	standard_unit	not set for file_path
	//	display_unit	not set for file_path
	//	format	not set for file_path
	//	max_value	not set for file_path
	//	min_value	not set for file_path
	//	max_alarm	not set for file_path
	//	min_alarm	not set for file_path
	//	max_warning	not set for file_path
	//	min_warning	not set for file_path
	//	delta_t	not set for file_path
	//	delta_val	not set for file_path
	file_path->set_default_properties(file_path_prop);
	//	Not Polled
	file_path->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(file_path);

	//	Attribute : file_write
	file_writeAttrib	*file_write = new file_writeAttrib();
	Tango::UserDefaultAttrProp	file_write_prop;
	//	description	not set for file_write
	//	label	not set for file_write
	//	unit	not set for file_write
	//	standard_unit	not set for file_write
	//	display_unit	not set for file_write
	//	format	not set for file_write
	//	max_value	not set for file_write
	//	min_value	not set for file_write
	//	max_alarm	not set for file_write
	//	min_alarm	not set for file_write
	//	max_warning	not set for file_write
	//	min_warning	not set for file_write
	//	delta_t	not set for file_write
	//	delta_val	not set for file_write
	file_write->set_default_properties(file_write_prop);
	//	Not Polled
	file_write->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(file_write);

	//	Attribute : firmware_version
	firmware_versionAttrib	*firmware_version = new firmware_versionAttrib();
	Tango::UserDefaultAttrProp	firmware_version_prop;
	//	description	not set for firmware_version
	//	label	not set for firmware_version
	//	unit	not set for firmware_version
	//	standard_unit	not set for firmware_version
	//	display_unit	not set for firmware_version
	firmware_version_prop.set_format("%05X");
	//	max_value	not set for firmware_version
	//	min_value	not set for firmware_version
	//	max_alarm	not set for firmware_version
	//	min_alarm	not set for firmware_version
	//	max_warning	not set for firmware_version
	//	min_warning	not set for firmware_version
	//	delta_t	not set for firmware_version
	//	delta_val	not set for firmware_version
	firmware_version->set_default_properties(firmware_version_prop);
	//	Not Polled
	firmware_version->set_disp_level(Tango::EXPERT);
	//	Not Memorized
	att_list.push_back(firmware_version);

	//	Attribute : high_voltage
	high_voltageAttrib	*high_voltage = new high_voltageAttrib();
	Tango::UserDefaultAttrProp	high_voltage_prop;
	//	description	not set for high_voltage
	//	label	not set for high_voltage
	high_voltage_prop.set_unit("V");
	//	standard_unit	not set for high_voltage
	//	display_unit	not set for high_voltage
	//	format	not set for high_voltage
	high_voltage_prop.set_max_value("200");
	//	min_value	not set for high_voltage
	//	max_alarm	not set for high_voltage
	//	min_alarm	not set for high_voltage
	//	max_warning	not set for high_voltage
	//	min_warning	not set for high_voltage
	//	delta_t	not set for high_voltage
	//	delta_val	not set for high_voltage
	high_voltage->set_default_properties(high_voltage_prop);
	//	Not Polled
	high_voltage->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(high_voltage);

	//	Attribute : hostname
	hostnameAttrib	*hostname = new hostnameAttrib();
	Tango::UserDefaultAttrProp	hostname_prop;
	//	description	not set for hostname
	//	label	not set for hostname
	//	unit	not set for hostname
	//	standard_unit	not set for hostname
	//	display_unit	not set for hostname
	//	format	not set for hostname
	//	max_value	not set for hostname
	//	min_value	not set for hostname
	//	max_alarm	not set for hostname
	//	min_alarm	not set for hostname
	//	max_warning	not set for hostname
	//	min_warning	not set for hostname
	//	delta_t	not set for hostname
	//	delta_val	not set for hostname
	hostname->set_default_properties(hostname_prop);
	//	Not Polled
	hostname->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(hostname);

	//	Attribute : master_file_write
	master_file_writeAttrib	*master_file_write = new master_file_writeAttrib();
	Tango::UserDefaultAttrProp	master_file_write_prop;
	//	description	not set for master_file_write
	//	label	not set for master_file_write
	//	unit	not set for master_file_write
	//	standard_unit	not set for master_file_write
	//	display_unit	not set for master_file_write
	//	format	not set for master_file_write
	//	max_value	not set for master_file_write
	//	min_value	not set for master_file_write
	//	max_alarm	not set for master_file_write
	//	min_alarm	not set for master_file_write
	//	max_warning	not set for master_file_write
	//	min_warning	not set for master_file_write
	//	delta_t	not set for master_file_write
	//	delta_val	not set for master_file_write
	master_file_write->set_default_properties(master_file_write_prop);
	//	Not Polled
	master_file_write->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(master_file_write);

	//	Attribute : num_frames
	num_framesAttrib	*num_frames = new num_framesAttrib();
	Tango::UserDefaultAttrProp	num_frames_prop;
	//	description	not set for num_frames
	//	label	not set for num_frames
	//	unit	not set for num_frames
	//	standard_unit	not set for num_frames
	//	display_unit	not set for num_frames
	//	format	not set for num_frames
	//	max_value	not set for num_frames
	num_frames_prop.set_min_value("0");
	//	max_alarm	not set for num_frames
	//	min_alarm	not set for num_frames
	//	max_warning	not set for num_frames
	//	min_warning	not set for num_frames
	//	delta_t	not set for num_frames
	//	delta_val	not set for num_frames
	num_frames->set_default_properties(num_frames_prop);
	//	Not Polled
	num_frames->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(num_frames);

	//	Attribute : num_frames_per_file
	num_frames_per_fileAttrib	*num_frames_per_file = new num_frames_per_fileAttrib();
	Tango::UserDefaultAttrProp	num_frames_per_file_prop;
	//	description	not set for num_frames_per_file
	//	label	not set for num_frames_per_file
	//	unit	not set for num_frames_per_file
	//	standard_unit	not set for num_frames_per_file
	//	display_unit	not set for num_frames_per_file
	//	format	not set for num_frames_per_file
	//	max_value	not set for num_frames_per_file
	num_frames_per_file_prop.set_min_value("0");
	//	max_alarm	not set for num_frames_per_file
	//	min_alarm	not set for num_frames_per_file
	//	max_warning	not set for num_frames_per_file
	//	min_warning	not set for num_frames_per_file
	//	delta_t	not set for num_frames_per_file
	//	delta_val	not set for num_frames_per_file
	num_frames_per_file->set_default_properties(num_frames_per_file_prop);
	//	Not Polled
	num_frames_per_file->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(num_frames_per_file);

	//	Attribute : num_triggers
	num_triggersAttrib	*num_triggers = new num_triggersAttrib();
	Tango::UserDefaultAttrProp	num_triggers_prop;
	//	description	not set for num_triggers
	//	label	not set for num_triggers
	//	unit	not set for num_triggers
	//	standard_unit	not set for num_triggers
	//	display_unit	not set for num_triggers
	//	format	not set for num_triggers
	//	max_value	not set for num_triggers
	num_triggers_prop.set_min_value("0");
	//	max_alarm	not set for num_triggers
	//	min_alarm	not set for num_triggers
	//	max_warning	not set for num_triggers
	//	min_warning	not set for num_triggers
	//	delta_t	not set for num_triggers
	//	delta_val	not set for num_triggers
	num_triggers->set_default_properties(num_triggers_prop);
	//	Not Polled
	num_triggers->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(num_triggers);

	//	Attribute : package_version
	package_versionAttrib	*package_version = new package_versionAttrib();
	Tango::UserDefaultAttrProp	package_version_prop;
	//	description	not set for package_version
	//	label	not set for package_version
	//	unit	not set for package_version
	//	standard_unit	not set for package_version
	//	display_unit	not set for package_version
	//	format	not set for package_version
	//	max_value	not set for package_version
	//	min_value	not set for package_version
	//	max_alarm	not set for package_version
	//	min_alarm	not set for package_version
	//	max_warning	not set for package_version
	//	min_warning	not set for package_version
	//	delta_t	not set for package_version
	//	delta_val	not set for package_version
	package_version->set_default_properties(package_version_prop);
	//	Not Polled
	package_version->set_disp_level(Tango::EXPERT);
	//	Not Memorized
	att_list.push_back(package_version);

	//	Attribute : period
	periodAttrib	*period = new periodAttrib();
	Tango::UserDefaultAttrProp	period_prop;
	//	description	not set for period
	//	label	not set for period
	period_prop.set_unit("s");
	//	standard_unit	not set for period
	//	display_unit	not set for period
	period_prop.set_format("%5.3e");
	//	max_value	not set for period
	//	min_value	not set for period
	//	max_alarm	not set for period
	//	min_alarm	not set for period
	//	max_warning	not set for period
	//	min_warning	not set for period
	//	delta_t	not set for period
	//	delta_val	not set for period
	period->set_default_properties(period_prop);
	//	Not Polled
	period->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(period);

	//	Attribute : rx_zmq_data_stream
	rx_zmq_data_streamAttrib	*rx_zmq_data_stream = new rx_zmq_data_streamAttrib();
	Tango::UserDefaultAttrProp	rx_zmq_data_stream_prop;
	//	description	not set for rx_zmq_data_stream
	//	label	not set for rx_zmq_data_stream
	//	unit	not set for rx_zmq_data_stream
	//	standard_unit	not set for rx_zmq_data_stream
	//	display_unit	not set for rx_zmq_data_stream
	//	format	not set for rx_zmq_data_stream
	//	max_value	not set for rx_zmq_data_stream
	//	min_value	not set for rx_zmq_data_stream
	//	max_alarm	not set for rx_zmq_data_stream
	//	min_alarm	not set for rx_zmq_data_stream
	//	max_warning	not set for rx_zmq_data_stream
	//	min_warning	not set for rx_zmq_data_stream
	//	delta_t	not set for rx_zmq_data_stream
	//	delta_val	not set for rx_zmq_data_stream
	rx_zmq_data_stream->set_default_properties(rx_zmq_data_stream_prop);
	//	Not Polled
	rx_zmq_data_stream->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(rx_zmq_data_stream);

	//	Attribute : temperature_fpga
	temperature_fpgaAttrib	*temperature_fpga = new temperature_fpgaAttrib();
	Tango::UserDefaultAttrProp	temperature_fpga_prop;
	//	description	not set for temperature_fpga
	//	label	not set for temperature_fpga
	temperature_fpga_prop.set_unit("°C");
	//	standard_unit	not set for temperature_fpga
	//	display_unit	not set for temperature_fpga
	//	format	not set for temperature_fpga
	//	max_value	not set for temperature_fpga
	//	min_value	not set for temperature_fpga
	//	max_alarm	not set for temperature_fpga
	//	min_alarm	not set for temperature_fpga
	//	max_warning	not set for temperature_fpga
	//	min_warning	not set for temperature_fpga
	//	delta_t	not set for temperature_fpga
	//	delta_val	not set for temperature_fpga
	temperature_fpga->set_default_properties(temperature_fpga_prop);
	//	Not Polled
	temperature_fpga->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(temperature_fpga);

	//	Attribute : num_missing_packets
	num_missing_packetsAttrib	*num_missing_packets = new num_missing_packetsAttrib();
	Tango::UserDefaultAttrProp	num_missing_packets_prop;
	//	description	not set for num_missing_packets
	//	label	not set for num_missing_packets
	//	unit	not set for num_missing_packets
	//	standard_unit	not set for num_missing_packets
	//	display_unit	not set for num_missing_packets
	//	format	not set for num_missing_packets
	//	max_value	not set for num_missing_packets
	//	min_value	not set for num_missing_packets
	//	max_alarm	not set for num_missing_packets
	//	min_alarm	not set for num_missing_packets
	//	max_warning	not set for num_missing_packets
	//	min_warning	not set for num_missing_packets
	//	delta_t	not set for num_missing_packets
	//	delta_val	not set for num_missing_packets
	num_missing_packets->set_default_properties(num_missing_packets_prop);
	//	Not Polled
	num_missing_packets->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(num_missing_packets);


	//	Create a list of static attributes
	create_static_attribute_list(get_class_attr()->get_attr_list());
	/*----- PROTECTED REGION ID(SlsDetectorControlClass::attribute_factory_after) ENABLED START -----*/
    /* clang-format on */
    //	Add your own code
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControlClass::attribute_factory_after
}
//--------------------------------------------------------
/**
 *	Method      : SlsDetectorControlClass::pipe_factory()
 * Description:  Create the pipe object(s)
 *                and store them in the pipe list
 */
//--------------------------------------------------------
void SlsDetectorControlClass::pipe_factory()
{
	/*----- PROTECTED REGION ID(SlsDetectorControlClass::pipe_factory_before) ENABLED START -----*/
    /* clang-format on */
    //	Add your own code
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControlClass::pipe_factory_before
	/*----- PROTECTED REGION ID(SlsDetectorControlClass::pipe_factory_after) ENABLED START -----*/
    /* clang-format on */
    //	Add your own code
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControlClass::pipe_factory_after
}
//--------------------------------------------------------
/**
 *	Method      : SlsDetectorControlClass::command_factory()
 * Description:  Create the command object(s)
 *                and store them in the command list
 */
//--------------------------------------------------------
void SlsDetectorControlClass::command_factory()
{
	/*----- PROTECTED REGION ID(SlsDetectorControlClass::command_factory_before) ENABLED START -----*/
    /* clang-format on */
    //	Add your own code
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControlClass::command_factory_before
	//	Command start_acquire
	start_acquireClass	*pstart_acquireCmd =
		new start_acquireClass("start_acquire",
			Tango::DEV_VOID, Tango::DEV_VOID,
			"",
			"",
			Tango::OPERATOR);
	command_list.push_back(pstart_acquireCmd);

	//	Command start_detector
	start_detectorClass	*pstart_detectorCmd =
		new start_detectorClass("start_detector",
			Tango::DEV_VOID, Tango::DEV_VOID,
			"",
			"",
			Tango::EXPERT);
	command_list.push_back(pstart_detectorCmd);

	//	Command start_receiver
	start_receiverClass	*pstart_receiverCmd =
		new start_receiverClass("start_receiver",
			Tango::DEV_VOID, Tango::DEV_VOID,
			"",
			"",
			Tango::EXPERT);
	command_list.push_back(pstart_receiverCmd);

	//	Command stop_acquire
	stop_acquireClass	*pstop_acquireCmd =
		new stop_acquireClass("stop_acquire",
			Tango::DEV_VOID, Tango::DEV_VOID,
			"",
			"",
			Tango::OPERATOR);
	command_list.push_back(pstop_acquireCmd);

	//	Command stop_detector
	stop_detectorClass	*pstop_detectorCmd =
		new stop_detectorClass("stop_detector",
			Tango::DEV_VOID, Tango::DEV_VOID,
			"",
			"",
			Tango::EXPERT);
	command_list.push_back(pstop_detectorCmd);

	//	Command stop_receiver
	stop_receiverClass	*pstop_receiverCmd =
		new stop_receiverClass("stop_receiver",
			Tango::DEV_VOID, Tango::DEV_VOID,
			"",
			"",
			Tango::EXPERT);
	command_list.push_back(pstop_receiverCmd);



	/*----- PROTECTED REGION ID(SlsDetectorControlClass::command_factory_after) ENABLED START -----*/
    /* clang-format on */
    //	Add your own code
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControlClass::command_factory_after
}

//===================================================================
//	Dynamic attributes related methods
//===================================================================

//--------------------------------------------------------
/**
 * method : 		SlsDetectorControlClass::create_static_attribute_list
 * description : 	Create the a list of static attributes
 *
 * @param	att_list	the created attribute list
 */
//--------------------------------------------------------
void SlsDetectorControlClass::create_static_attribute_list(std::vector<Tango::Attr *> &att_list)
{
	for (unsigned long i=0 ; i<att_list.size() ; i++)
	{
		std::string att_name(att_list[i]->get_name());
		transform(att_name.begin(), att_name.end(), att_name.begin(), ::tolower);
		defaultAttList.push_back(att_name);
	}

	TANGO_LOG_INFO << defaultAttList.size() << " attributes in default list" << std::endl;

	/*----- PROTECTED REGION ID(SlsDetectorControlClass::create_static_att_list) ENABLED START -----*/
    /* clang-format on */
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControlClass::create_static_att_list
}


//--------------------------------------------------------
/**
 * method : 		SlsDetectorControlClass::erase_dynamic_attributes
 * description : 	delete the dynamic attributes if any.
 *
 * @param	devlist_ptr	the device list pointer
 * @param	list of all attributes
 */
//--------------------------------------------------------
void SlsDetectorControlClass::erase_dynamic_attributes(const Tango::DevVarStringArray *devlist_ptr, std::vector<Tango::Attr *> &att_list)
{
	Tango::Util *tg = Tango::Util::instance();

	for (unsigned long i=0 ; i<devlist_ptr->length() ; i++)
	{
		Tango::DeviceImpl *dev_impl = tg->get_device_by_name(((std::string)(*devlist_ptr)[i]).c_str());
		SlsDetectorControl *dev = static_cast<SlsDetectorControl *> (dev_impl);

		std::vector<Tango::Attribute *> &dev_att_list = dev->get_device_attr()->get_attribute_list();
		std::vector<Tango::Attribute *>::iterator ite_att;
		for (ite_att=dev_att_list.begin() ; ite_att != dev_att_list.end() ; ++ite_att)
		{
			std::string att_name((*ite_att)->get_name_lower());
			if ((att_name == "state") || (att_name == "status"))
				continue;
			std::vector<std::string>::iterator ite_str = find(defaultAttList.begin(), defaultAttList.end(), att_name);
			if (ite_str == defaultAttList.end())
			{
				TANGO_LOG_INFO << att_name << " is a UNWANTED dynamic attribute for device " << (*devlist_ptr)[i] << std::endl;
				Tango::Attribute &att = dev->get_device_attr()->get_attr_by_name(att_name.c_str());
				dev->remove_attribute(att_list[att.get_attr_idx()], true, false);
				--ite_att;
			}
		}
	}
	/*----- PROTECTED REGION ID(SlsDetectorControlClass::erase_dynamic_attributes) ENABLED START -----*/
    /* clang-format on */
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControlClass::erase_dynamic_attributes
}

//--------------------------------------------------------
/**
 *	Method      : SlsDetectorControlClass::get_attr_object_by_name()
 * Description:  returns Tango::Attr * object found by name
 */
//--------------------------------------------------------
Tango::Attr *SlsDetectorControlClass::get_attr_object_by_name(std::vector<Tango::Attr *> &att_list, std::string attname)
{
	std::vector<Tango::Attr *>::iterator it;
	for (it=att_list.begin() ; it<att_list.end() ; ++it)
		if ((*it)->get_name()==attname)
			return (*it);
	//	Attr does not exist
	return NULL;
}


/*----- PROTECTED REGION ID(SlsDetectorControlClass::Additional Methods) ENABLED START -----*/
/* clang-format on */
/* clang-format off */
/*----- PROTECTED REGION END -----*/	//	SlsDetectorControlClass::Additional Methods
} //	namespace
