/*----- PROTECTED REGION ID(SlsDetectorControl.cpp) ENABLED START -----*/
/* clang-format on */
//=============================================================================
//
// file :        SlsDetectorControl.cpp
//
// description : C++ source for the SlsDetectorControl class and its commands.
//               The class is derived from Device. It represents the
//               CORBA servant object which will be accessed from the
//               network. All commands which can be executed on the
//               SlsDetectorControl are implemented in this file.
//
// project :     tango-slsdetectorcontrol
//
// This file is part of Tango device class.
//
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the MIT licence.
//
//
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================

#include "SlsDetectorControl.h"
#include "SlsDetectorControlClass.h"

/* clang-format off */
/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl.cpp

/**
 *  SlsDetectorControl class description:
 *    
 */

//================================================================
//  The following table gives the correspondence
//  between command and method names.
//
//  Command name    |  Method name
//================================================================
//  start_acquire   |  start_acquire
//  start_detector  |  start_detector
//  start_receiver  |  start_receiver
//  stop_acquire    |  stop_acquire
//  stop_detector   |  stop_detector
//  stop_receiver   |  stop_receiver
//  Status          |  Inherited (no method)
//  State           |  Inherited (no method)
//================================================================

//================================================================
//  Attributes managed are:
//================================================================
//  acquisition_index    |  Tango::DevLong64	Scalar
//  detector_type        |  Tango::DevString	Scalar
//  dynamic_range        |  Tango::DevLong	Scalar
//  exptime              |  Tango::DevDouble	Scalar
//  file_name            |  Tango::DevString	Scalar
//  file_name_prefix     |  Tango::DevString	Scalar
//  file_overwrite       |  Tango::DevBoolean	Scalar
//  file_path            |  Tango::DevString	Scalar
//  file_write           |  Tango::DevBoolean	Scalar
//  firmware_version     |  Tango::DevLong64	Scalar
//  high_voltage         |  Tango::DevLong	Scalar
//  hostname             |  Tango::DevString	Scalar
//  master_file_write    |  Tango::DevBoolean	Scalar
//  num_frames           |  Tango::DevLong64	Scalar
//  num_frames_per_file  |  Tango::DevLong	Scalar
//  num_triggers         |  Tango::DevLong64	Scalar
//  package_version      |  Tango::DevString	Scalar
//  period               |  Tango::DevDouble	Scalar
//  rx_zmq_data_stream   |  Tango::DevBoolean	Scalar
//  temperature_fpga     |  Tango::DevLong	Scalar
//  num_missing_packets  |  Tango::DevLong64	Spectrum  ( max = 2)
//================================================================

namespace SlsDetectorControl_ns
{
/*----- PROTECTED REGION ID(SlsDetectorControl::namespace_starting) ENABLED START -----*/
/* clang-format on */

//	static initializations
/* clang-format off */
/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::namespace_starting

//--------------------------------------------------------
/**
 *	Method      : SlsDetectorControl::SlsDetectorControl()
 * Description:  Constructors for a Tango device
 *                implementing the classSlsDetectorControl
 */
//--------------------------------------------------------
SlsDetectorControl::SlsDetectorControl(Tango::DeviceClass *cl, std::string &s)
 : TANGO_BASE_CLASS(cl, s.c_str())
{
	/*----- PROTECTED REGION ID(SlsDetectorControl::constructor_1) ENABLED START -----*/
    /* clang-format on */
    init_device();
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::constructor_1
}
//--------------------------------------------------------
SlsDetectorControl::SlsDetectorControl(Tango::DeviceClass *cl, const char *s)
 : TANGO_BASE_CLASS(cl, s)
{
	/*----- PROTECTED REGION ID(SlsDetectorControl::constructor_2) ENABLED START -----*/
    /* clang-format on */
    init_device();
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::constructor_2
}
//--------------------------------------------------------
SlsDetectorControl::SlsDetectorControl(Tango::DeviceClass *cl, const char *s, const char *d)
 : TANGO_BASE_CLASS(cl, s, d)
{
	/*----- PROTECTED REGION ID(SlsDetectorControl::constructor_3) ENABLED START -----*/
    /* clang-format on */
    init_device();
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::constructor_3
}
//--------------------------------------------------------
SlsDetectorControl::~SlsDetectorControl()
{
	delete_device();
}

//--------------------------------------------------------
/**
 *	Method      : SlsDetectorControl::delete_device()
 * Description:  will be called at device destruction or at init command
 */
//--------------------------------------------------------
void SlsDetectorControl::delete_device()
{
	DEBUG_STREAM << "SlsDetectorControl::delete_device() " << device_name << std::endl;
	/*----- PROTECTED REGION ID(SlsDetectorControl::delete_device) ENABLED START -----*/
    /* clang-format on */
    // kill slsReceiver if was started as a forked process
    if(startReceiverOnStartup && receiver_pid > 0)
    {
        // SIGTERM is not enough to kill the receiver process
        kill(receiver_pid, SIGKILL);
        waitpid(receiver_pid, nullptr, 0);
    }
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::delete_device
	delete[] attr_acquisition_index_read;
	delete[] attr_dynamic_range_read;
	delete[] attr_exptime_read;
	delete[] attr_file_name_read;
	delete[] attr_file_name_prefix_read;
	delete[] attr_file_overwrite_read;
	delete[] attr_file_path_read;
	delete[] attr_file_write_read;
	delete[] attr_firmware_version_read;
	delete[] attr_high_voltage_read;
	delete[] attr_hostname_read;
	delete[] attr_master_file_write_read;
	delete[] attr_num_frames_read;
	delete[] attr_num_frames_per_file_read;
	delete[] attr_num_triggers_read;
	delete[] attr_package_version_read;
	delete[] attr_period_read;
	delete[] attr_rx_zmq_data_stream_read;
	delete[] attr_temperature_fpga_read;
	delete[] attr_num_missing_packets_read;
}

//--------------------------------------------------------
/**
 *	Method      : SlsDetectorControl::init_device()
 * Description:  will be called at device initialization.
 */
//--------------------------------------------------------
void SlsDetectorControl::init_device()
{
	DEBUG_STREAM << "SlsDetectorControl::init_device() create device " << device_name << std::endl;
	/*----- PROTECTED REGION ID(SlsDetectorControl::init_device_before) ENABLED START -----*/
    /* clang-format on */
    //	Initialization before get_device_property() call
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::init_device_before


	//	Get the device properties from database
	get_device_property();

	attr_acquisition_index_read = new Tango::DevLong64[1];
	attr_dynamic_range_read = new Tango::DevLong[1];
	attr_exptime_read = new Tango::DevDouble[1];
	attr_file_name_read = new Tango::DevString[1];
	attr_file_name_prefix_read = new Tango::DevString[1];
	attr_file_overwrite_read = new Tango::DevBoolean[1];
	attr_file_path_read = new Tango::DevString[1];
	attr_file_write_read = new Tango::DevBoolean[1];
	attr_firmware_version_read = new Tango::DevLong64[1];
	attr_high_voltage_read = new Tango::DevLong[1];
	attr_hostname_read = new Tango::DevString[1];
	attr_master_file_write_read = new Tango::DevBoolean[1];
	attr_num_frames_read = new Tango::DevLong64[1];
	attr_num_frames_per_file_read = new Tango::DevLong[1];
	attr_num_triggers_read = new Tango::DevLong64[1];
	attr_package_version_read = new Tango::DevString[1];
	attr_period_read = new Tango::DevDouble[1];
	attr_rx_zmq_data_stream_read = new Tango::DevBoolean[1];
	attr_temperature_fpga_read = new Tango::DevLong[1];
	attr_num_missing_packets_read = new Tango::DevLong64[2];
	//	No longer if mandatory property not set.
	if (mandatoryNotDefined)
		return;

	/*----- PROTECTED REGION ID(SlsDetectorControl::init_device) ENABLED START -----*/
    /* clang-format on */
    if(startReceiverOnStartup)
    {
#ifdef SLS_DET_EMBED_RECEIVER
        if(receiverExecutablePath.empty())
        {
            receiver_ptr = std::make_unique<sls::Receiver>(receiverPort);
            TANGO_LOG_DEBUG << "Created sls::Receiver with port " << receiverPort << std::endl;
        }
#endif
        if(!receiverExecutablePath.empty())
        {
            auto exec_name = std::filesystem::path(receiverExecutablePath).filename().c_str();
            receiver_pid = fork();
            if(receiver_pid == 0) // child process
            {
                TANGO_LOG_DEBUG << "Created sls::Receiver with executable " << receiverExecutablePath << " and port "
                                << receiverPort << std::endl;
                execl(receiverExecutablePath.c_str(), exec_name, "-p", std::to_string(receiverPort).c_str(), nullptr);
            }
            std::this_thread::sleep_for(1s); // give the receiver some time to start
        }
    }
    detector_ptr = std::make_unique<sls::Detector>(detectorId);
    TANGO_LOG_DEBUG << "Created sls::Detector with id " << detectorId << std::endl;
    try
    {
        detector_ptr->loadConfig(configurationPathDevString);
    }
    catch(sls::RuntimeError &e)
    {
        TANGO_LOG_DEBUG << "Error loading detector configuration: " << e.what() << std::endl;
    }

    for(auto &[k, v] : attributesInfo)
    {
        try
        {
            v.available = v.checkFunction();
        }
        catch(sls::RuntimeError &e)
        {
            TANGO_LOG_DEBUG << "Error initializing attribute " << k << ": " << e.what() << std::endl;
            v.available = false;
        }
    }
    for(auto &[k, v] : commandsInfo)
    {
        try
        {
            v.available = v.checkFunction();
        }
        catch(sls::RuntimeError &e)
        {
            TANGO_LOG_DEBUG << "Error initializing command " << k << ": " << e.what() << std::endl;
            v.available = false;
        }
    }

    set_state(Tango::ON);
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::init_device
}

//--------------------------------------------------------
/**
 *	Method      : SlsDetectorControl::get_device_property()
 * Description:  Read database to initialize property data members.
 */
//--------------------------------------------------------
void SlsDetectorControl::get_device_property()
{
	/*----- PROTECTED REGION ID(SlsDetectorControl::get_device_property_before) ENABLED START -----*/
    /* clang-format on */
    //	Initialize property data members
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::get_device_property_before

	mandatoryNotDefined = false;

	//	Read device properties from database.
	Tango::DbData	dev_prop;
	dev_prop.push_back(Tango::DbDatum("ConfigurationPathDevString"));
	dev_prop.push_back(Tango::DbDatum("DetectorId"));
	dev_prop.push_back(Tango::DbDatum("GainMapPaths"));
	dev_prop.push_back(Tango::DbDatum("PixelMaskPaths"));
	dev_prop.push_back(Tango::DbDatum("ReceiverPort"));
	dev_prop.push_back(Tango::DbDatum("ReceiverExecutablePath"));
	dev_prop.push_back(Tango::DbDatum("StartReceiverOnStartup"));

	//	is there at least one property to be read ?
	if (dev_prop.size()>0)
	{
		//	Call database and extract values
		if (Tango::Util::instance()->_UseDb==true)
			get_db_device()->get_property(dev_prop);

		//	get instance on SlsDetectorControlClass to get class property
		Tango::DbDatum	def_prop, cl_prop;
		SlsDetectorControlClass	*ds_class =
			(static_cast<SlsDetectorControlClass *>(get_device_class()));
		int	i = -1;

		//	Try to initialize ConfigurationPathDevString from class property
		cl_prop = ds_class->get_class_property(dev_prop[++i].name);
		if (cl_prop.is_empty()==false)	cl_prop  >>  configurationPathDevString;
		else {
			//	Try to initialize ConfigurationPathDevString from default device value
			def_prop = ds_class->get_default_device_property(dev_prop[i].name);
			if (def_prop.is_empty()==false)	def_prop  >>  configurationPathDevString;
		}
		//	And try to extract ConfigurationPathDevString value from database
		if (dev_prop[i].is_empty()==false)	dev_prop[i]  >>  configurationPathDevString;
		//	Property StartDsPath is mandatory, check if has been defined in database.
		check_mandatory_property(cl_prop, dev_prop[i]);

		//	Try to initialize DetectorId from class property
		cl_prop = ds_class->get_class_property(dev_prop[++i].name);
		if (cl_prop.is_empty()==false)	cl_prop  >>  detectorId;
		else {
			//	Try to initialize DetectorId from default device value
			def_prop = ds_class->get_default_device_property(dev_prop[i].name);
			if (def_prop.is_empty()==false)	def_prop  >>  detectorId;
		}
		//	And try to extract DetectorId value from database
		if (dev_prop[i].is_empty()==false)	dev_prop[i]  >>  detectorId;

		//	Try to initialize GainMapPaths from class property
		cl_prop = ds_class->get_class_property(dev_prop[++i].name);
		if (cl_prop.is_empty()==false)	cl_prop  >>  gainMapPaths;
		else {
			//	Try to initialize GainMapPaths from default device value
			def_prop = ds_class->get_default_device_property(dev_prop[i].name);
			if (def_prop.is_empty()==false)	def_prop  >>  gainMapPaths;
		}
		//	And try to extract GainMapPaths value from database
		if (dev_prop[i].is_empty()==false)	dev_prop[i]  >>  gainMapPaths;

		//	Try to initialize PixelMaskPaths from class property
		cl_prop = ds_class->get_class_property(dev_prop[++i].name);
		if (cl_prop.is_empty()==false)	cl_prop  >>  pixelMaskPaths;
		else {
			//	Try to initialize PixelMaskPaths from default device value
			def_prop = ds_class->get_default_device_property(dev_prop[i].name);
			if (def_prop.is_empty()==false)	def_prop  >>  pixelMaskPaths;
		}
		//	And try to extract PixelMaskPaths value from database
		if (dev_prop[i].is_empty()==false)	dev_prop[i]  >>  pixelMaskPaths;

		//	Try to initialize ReceiverPort from class property
		cl_prop = ds_class->get_class_property(dev_prop[++i].name);
		if (cl_prop.is_empty()==false)	cl_prop  >>  receiverPort;
		else {
			//	Try to initialize ReceiverPort from default device value
			def_prop = ds_class->get_default_device_property(dev_prop[i].name);
			if (def_prop.is_empty()==false)	def_prop  >>  receiverPort;
		}
		//	And try to extract ReceiverPort value from database
		if (dev_prop[i].is_empty()==false)	dev_prop[i]  >>  receiverPort;

		//	Try to initialize ReceiverExecutablePath from class property
		cl_prop = ds_class->get_class_property(dev_prop[++i].name);
		if (cl_prop.is_empty()==false)	cl_prop  >>  receiverExecutablePath;
		else {
			//	Try to initialize ReceiverExecutablePath from default device value
			def_prop = ds_class->get_default_device_property(dev_prop[i].name);
			if (def_prop.is_empty()==false)	def_prop  >>  receiverExecutablePath;
		}
		//	And try to extract ReceiverExecutablePath value from database
		if (dev_prop[i].is_empty()==false)	dev_prop[i]  >>  receiverExecutablePath;

		//	Try to initialize StartReceiverOnStartup from class property
		cl_prop = ds_class->get_class_property(dev_prop[++i].name);
		if (cl_prop.is_empty()==false)	cl_prop  >>  startReceiverOnStartup;
		else {
			//	Try to initialize StartReceiverOnStartup from default device value
			def_prop = ds_class->get_default_device_property(dev_prop[i].name);
			if (def_prop.is_empty()==false)	def_prop  >>  startReceiverOnStartup;
		}
		//	And try to extract StartReceiverOnStartup value from database
		if (dev_prop[i].is_empty()==false)	dev_prop[i]  >>  startReceiverOnStartup;

	}

	/*----- PROTECTED REGION ID(SlsDetectorControl::get_device_property_after) ENABLED START -----*/
    /* clang-format on */
    //	Check device property data members init
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::get_device_property_after
}
//--------------------------------------------------------
/**
 *	Method      : SlsDetectorControl::check_mandatory_property()
 * Description:  For mandatory properties check if defined in database.
 */
//--------------------------------------------------------
void SlsDetectorControl::check_mandatory_property(Tango::DbDatum &class_prop, Tango::DbDatum &dev_prop)
{
	//	Check if all properties are empty
	if (class_prop.is_empty() && dev_prop.is_empty())
	{
		TangoSys_OMemStream	tms;
		tms << std::endl <<"Property \'" << dev_prop.name;
		if (Tango::Util::instance()->_UseDb==true)
			tms << "\' is mandatory but not defined in database";
		else
			tms << "\' is mandatory but cannot be defined without database";
		append_status(tms.str());
		mandatoryNotDefined = true;
		/*----- PROTECTED REGION ID(SlsDetectorControl::check_mandatory_property) ENABLED START -----*/
        /* clang-format on */
        std::cerr << tms.str() << " for " << device_name << std::endl;
        /* clang-format off */
		/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::check_mandatory_property
	}
}


//--------------------------------------------------------
/**
 *	Method      : SlsDetectorControl::always_executed_hook()
 * Description:  method always executed before any command is executed
 */
//--------------------------------------------------------
void SlsDetectorControl::always_executed_hook()
{
	DEBUG_STREAM << "SlsDetectorControl::always_executed_hook()  " << device_name << std::endl;
	if (mandatoryNotDefined)
	{
		Tango::Except::throw_exception(
					(const char *)"PROPERTY_NOT_SET",
					get_status().c_str(),
					(const char *)"SlsDetectorControl::always_executed_hook()");
	}
	/*----- PROTECTED REGION ID(SlsDetectorControl::always_executed_hook) ENABLED START -----*/
    /* clang-format on */
    //	code always executed before all requests
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::always_executed_hook
}

//--------------------------------------------------------
/**
 *	Method      : SlsDetectorControl::read_attr_hardware()
 * Description:  Hardware acquisition for attributes
 */
//--------------------------------------------------------
void SlsDetectorControl::read_attr_hardware(TANGO_UNUSED(std::vector<long> &attr_list))
{
	DEBUG_STREAM << "SlsDetectorControl::read_attr_hardware(std::vector<long> &attr_list) entering... " << std::endl;
	/*----- PROTECTED REGION ID(SlsDetectorControl::read_attr_hardware) ENABLED START -----*/
    /* clang-format on */
    //	Add your own code
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::read_attr_hardware
}
//--------------------------------------------------------
/**
 *	Method      : SlsDetectorControl::write_attr_hardware()
 * Description:  Hardware writing for attributes
 */
//--------------------------------------------------------
void SlsDetectorControl::write_attr_hardware(TANGO_UNUSED(std::vector<long> &attr_list))
{
	DEBUG_STREAM << "SlsDetectorControl::write_attr_hardware(std::vector<long> &attr_list) entering... " << std::endl;
	/*----- PROTECTED REGION ID(SlsDetectorControl::write_attr_hardware) ENABLED START -----*/
    /* clang-format on */
    //	Add your own code
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::write_attr_hardware
}

//--------------------------------------------------------
/**
 *	Read attribute acquisition_index related method
 *
 *
 *	Data type:	Tango::DevLong64
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void SlsDetectorControl::read_acquisition_index(Tango::Attribute &attr)
{
	DEBUG_STREAM << "SlsDetectorControl::read_acquisition_index(Tango::Attribute &attr) entering... " << std::endl;
	/*----- PROTECTED REGION ID(SlsDetectorControl::read_acquisition_index) ENABLED START -----*/
    /* clang-format on */
    *attr_acquisition_index_read = detector_ptr->getAcquisitionIndex().front();
    attr.set_value(attr_acquisition_index_read);
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::read_acquisition_index
}
//--------------------------------------------------------
/**
 *	Write attribute acquisition_index related method
 *
 *
 *	Data type:	Tango::DevLong64
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void SlsDetectorControl::write_acquisition_index(Tango::WAttribute &attr)
{
	DEBUG_STREAM << "SlsDetectorControl::write_acquisition_index(Tango::WAttribute &attr) entering... " << std::endl;
	//	Retrieve write value
	Tango::DevLong64	w_val;
	attr.get_write_value(w_val);
	/*----- PROTECTED REGION ID(SlsDetectorControl::write_acquisition_index) ENABLED START -----*/
    /* clang-format on */
    detector_ptr->setAcquisitionIndex(w_val);
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::write_acquisition_index
}
//--------------------------------------------------------
/**
 *	Read attribute detector_type related method
 *
 *
 *	Data type:	Tango::DevString
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void SlsDetectorControl::read_detector_type(Tango::Attribute &attr)
{
	DEBUG_STREAM << "SlsDetectorControl::read_detector_type(Tango::Attribute &attr) entering... " << std::endl;
	/*----- PROTECTED REGION ID(SlsDetectorControl::read_detector_type) ENABLED START -----*/
    /* clang-format on */
    attr_detector_type_read = new Tango::DevString;
    auto detector_type = detector_ptr->getDetectorType().front();
    *attr_detector_type_read = Tango::string_dup(sls::ToString(detector_type));
    attr.set_value(attr_detector_type_read);
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::read_detector_type
}
//--------------------------------------------------------
/**
 *	Read attribute dynamic_range related method
 *
 *
 *	Data type:	Tango::DevLong
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void SlsDetectorControl::read_dynamic_range(Tango::Attribute &attr)
{
	DEBUG_STREAM << "SlsDetectorControl::read_dynamic_range(Tango::Attribute &attr) entering... " << std::endl;
	/*----- PROTECTED REGION ID(SlsDetectorControl::read_dynamic_range) ENABLED START -----*/
    /* clang-format on */
    *attr_dynamic_range_read = detector_ptr->getDynamicRange().front();
    attr.set_value(attr_dynamic_range_read);
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::read_dynamic_range
}
//--------------------------------------------------------
/**
 *	Write attribute dynamic_range related method
 *
 *
 *	Data type:	Tango::DevLong
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void SlsDetectorControl::write_dynamic_range(Tango::WAttribute &attr)
{
	DEBUG_STREAM << "SlsDetectorControl::write_dynamic_range(Tango::WAttribute &attr) entering... " << std::endl;
	//	Retrieve write value
	Tango::DevLong	w_val;
	attr.get_write_value(w_val);
	/*----- PROTECTED REGION ID(SlsDetectorControl::write_dynamic_range) ENABLED START -----*/
    /* clang-format on */
    detector_ptr->setDynamicRange(w_val);
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::write_dynamic_range
}
//--------------------------------------------------------
/**
 *	Read attribute exptime related method
 *
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void SlsDetectorControl::read_exptime(Tango::Attribute &attr)
{
	DEBUG_STREAM << "SlsDetectorControl::read_exptime(Tango::Attribute &attr) entering... " << std::endl;
	/*----- PROTECTED REGION ID(SlsDetectorControl::read_exptime) ENABLED START -----*/
    /* clang-format on */
    //	Set the attribute value
    auto exptime = detector_ptr->getExptime().front();
    *attr_exptime_read = std::chrono::duration<double>(exptime).count();
    attr.set_value(attr_exptime_read);
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::read_exptime
}
//--------------------------------------------------------
/**
 *	Write attribute exptime related method
 *
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void SlsDetectorControl::write_exptime(Tango::WAttribute &attr)
{
	DEBUG_STREAM << "SlsDetectorControl::write_exptime(Tango::WAttribute &attr) entering... " << std::endl;
	//	Retrieve write value
	Tango::DevDouble	w_val;
	attr.get_write_value(w_val);
	/*----- PROTECTED REGION ID(SlsDetectorControl::write_exptime) ENABLED START -----*/
    /* clang-format on */
    auto exptime = std::chrono::round<std::chrono::nanoseconds>(w_val * 1s);
    detector_ptr->setExptime(exptime);
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::write_exptime
}
//--------------------------------------------------------
/**
 *	Read attribute file_name related method
 *
 *
 *	Data type:	Tango::DevString
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void SlsDetectorControl::read_file_name(Tango::Attribute &attr)
{
	DEBUG_STREAM << "SlsDetectorControl::read_file_name(Tango::Attribute &attr) entering... " << std::endl;
	/*----- PROTECTED REGION ID(SlsDetectorControl::read_file_name) ENABLED START -----*/
    /* clang-format on */
    // default run File Name: [file name prefix]_d[module index]_f[file index]_[acquisition index].[file format] eg.
    // run_d0_f0_5.raw
    std::string file_name_prefix = detector_ptr->getFileNamePrefix().front();
    int module_index = 0;
    auto file_index = detector_ptr->getAcquisitionIndex().front();
    auto file_format = detector_ptr->getFileFormat().front();
    // Actually, the index after f (subFileIndex) can be more than zero if more frames are acquired than the number of
    // frames per file but this will be known only during the file writing.
    std::string full_string =
        file_name_prefix + "_d" + std::to_string(module_index) + "_f0_" + std::to_string(file_index);
    *attr_file_name_read = Tango::string_dup(full_string);
    attr.set_value(attr_file_name_read);
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::read_file_name
}
//--------------------------------------------------------
/**
 *	Read attribute file_name_prefix related method
 *
 *
 *	Data type:	Tango::DevString
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void SlsDetectorControl::read_file_name_prefix(Tango::Attribute &attr)
{
	DEBUG_STREAM << "SlsDetectorControl::read_file_name_prefix(Tango::Attribute &attr) entering... " << std::endl;
	/*----- PROTECTED REGION ID(SlsDetectorControl::read_file_name_prefix) ENABLED START -----*/
    /* clang-format on */
    *attr_file_name_prefix_read = Tango::string_dup(detector_ptr->getFileNamePrefix().front());
    attr.set_value(attr_file_name_prefix_read);
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::read_file_name_prefix
}
//--------------------------------------------------------
/**
 *	Write attribute file_name_prefix related method
 *
 *
 *	Data type:	Tango::DevString
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void SlsDetectorControl::write_file_name_prefix(Tango::WAttribute &attr)
{
	DEBUG_STREAM << "SlsDetectorControl::write_file_name_prefix(Tango::WAttribute &attr) entering... " << std::endl;
	//	Retrieve write value
	Tango::DevString	w_val;
	attr.get_write_value(w_val);
	/*----- PROTECTED REGION ID(SlsDetectorControl::write_file_name_prefix) ENABLED START -----*/
    /* clang-format on */
    detector_ptr->setFileNamePrefix(w_val);
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::write_file_name_prefix
}
//--------------------------------------------------------
/**
 *	Read attribute file_overwrite related method
 *
 *
 *	Data type:	Tango::DevBoolean
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void SlsDetectorControl::read_file_overwrite(Tango::Attribute &attr)
{
	DEBUG_STREAM << "SlsDetectorControl::read_file_overwrite(Tango::Attribute &attr) entering... " << std::endl;
	/*----- PROTECTED REGION ID(SlsDetectorControl::read_file_overwrite) ENABLED START -----*/
    /* clang-format on */
    *attr_file_overwrite_read = detector_ptr->getFileOverWrite().front();
    attr.set_value(attr_file_overwrite_read);
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::read_file_overwrite
}
//--------------------------------------------------------
/**
 *	Write attribute file_overwrite related method
 *
 *
 *	Data type:	Tango::DevBoolean
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void SlsDetectorControl::write_file_overwrite(Tango::WAttribute &attr)
{
	DEBUG_STREAM << "SlsDetectorControl::write_file_overwrite(Tango::WAttribute &attr) entering... " << std::endl;
	//	Retrieve write value
	Tango::DevBoolean	w_val;
	attr.get_write_value(w_val);
	/*----- PROTECTED REGION ID(SlsDetectorControl::write_file_overwrite) ENABLED START -----*/
    /* clang-format on */
    detector_ptr->setFileOverWrite(w_val);
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::write_file_overwrite
}
//--------------------------------------------------------
/**
 *	Read attribute file_path related method
 *
 *
 *	Data type:	Tango::DevString
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void SlsDetectorControl::read_file_path(Tango::Attribute &attr)
{
	DEBUG_STREAM << "SlsDetectorControl::read_file_path(Tango::Attribute &attr) entering... " << std::endl;
	/*----- PROTECTED REGION ID(SlsDetectorControl::read_file_path) ENABLED START -----*/
    /* clang-format on */
    *attr_file_path_read = Tango::string_dup(detector_ptr->getFilePath().front());
    attr.set_value(attr_file_path_read);
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::read_file_path
}
//--------------------------------------------------------
/**
 *	Write attribute file_path related method
 *
 *
 *	Data type:	Tango::DevString
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void SlsDetectorControl::write_file_path(Tango::WAttribute &attr)
{
	DEBUG_STREAM << "SlsDetectorControl::write_file_path(Tango::WAttribute &attr) entering... " << std::endl;
	//	Retrieve write value
	Tango::DevString	w_val;
	attr.get_write_value(w_val);
	/*----- PROTECTED REGION ID(SlsDetectorControl::write_file_path) ENABLED START -----*/
    /* clang-format on */
    detector_ptr->setFilePath(w_val);
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::write_file_path
}
//--------------------------------------------------------
/**
 *	Read attribute file_write related method
 *
 *
 *	Data type:	Tango::DevBoolean
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void SlsDetectorControl::read_file_write(Tango::Attribute &attr)
{
	DEBUG_STREAM << "SlsDetectorControl::read_file_write(Tango::Attribute &attr) entering... " << std::endl;
	/*----- PROTECTED REGION ID(SlsDetectorControl::read_file_write) ENABLED START -----*/
    /* clang-format on */
    *attr_file_write_read = detector_ptr->getFileWrite().front();
    attr.set_value(attr_file_write_read);
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::read_file_write
}
//--------------------------------------------------------
/**
 *	Write attribute file_write related method
 *
 *
 *	Data type:	Tango::DevBoolean
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void SlsDetectorControl::write_file_write(Tango::WAttribute &attr)
{
	DEBUG_STREAM << "SlsDetectorControl::write_file_write(Tango::WAttribute &attr) entering... " << std::endl;
	//	Retrieve write value
	Tango::DevBoolean	w_val;
	attr.get_write_value(w_val);
	/*----- PROTECTED REGION ID(SlsDetectorControl::write_file_write) ENABLED START -----*/
    /* clang-format on */
    detector_ptr->setFileWrite(w_val);
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::write_file_write
}
//--------------------------------------------------------
/**
 *	Read attribute firmware_version related method
 *
 *
 *	Data type:	Tango::DevLong64
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void SlsDetectorControl::read_firmware_version(Tango::Attribute &attr)
{
	DEBUG_STREAM << "SlsDetectorControl::read_firmware_version(Tango::Attribute &attr) entering... " << std::endl;
	/*----- PROTECTED REGION ID(SlsDetectorControl::read_firmware_version) ENABLED START -----*/
    /* clang-format on */
    *attr_firmware_version_read = detector_ptr->getFirmwareVersion().front();
    attr.set_value(attr_firmware_version_read);
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::read_firmware_version
}
//--------------------------------------------------------
/**
 *	Read attribute high_voltage related method
 *
 *
 *	Data type:	Tango::DevLong
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void SlsDetectorControl::read_high_voltage(Tango::Attribute &attr)
{
	DEBUG_STREAM << "SlsDetectorControl::read_high_voltage(Tango::Attribute &attr) entering... " << std::endl;
	/*----- PROTECTED REGION ID(SlsDetectorControl::read_high_voltage) ENABLED START -----*/
    /* clang-format on */
    *attr_high_voltage_read = detector_ptr->getHighVoltage().front();
    attr.set_value(attr_high_voltage_read);
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::read_high_voltage
}
//--------------------------------------------------------
/**
 *	Write attribute high_voltage related method
 *
 *
 *	Data type:	Tango::DevLong
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void SlsDetectorControl::write_high_voltage(Tango::WAttribute &attr)
{
	DEBUG_STREAM << "SlsDetectorControl::write_high_voltage(Tango::WAttribute &attr) entering... " << std::endl;
	//	Retrieve write value
	Tango::DevLong	w_val;
	attr.get_write_value(w_val);
	/*----- PROTECTED REGION ID(SlsDetectorControl::write_high_voltage) ENABLED START -----*/
    /* clang-format on */
    detector_ptr->setHighVoltage(w_val);
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::write_high_voltage
}
//--------------------------------------------------------
/**
 *	Read attribute hostname related method
 *
 *
 *	Data type:	Tango::DevString
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void SlsDetectorControl::read_hostname(Tango::Attribute &attr)
{
	DEBUG_STREAM << "SlsDetectorControl::read_hostname(Tango::Attribute &attr) entering... " << std::endl;
	/*----- PROTECTED REGION ID(SlsDetectorControl::read_hostname) ENABLED START -----*/
    /* clang-format on */
    *attr_hostname_read = Tango::string_dup(detector_ptr->getHostname().front());
    attr.set_value(attr_hostname_read);
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::read_hostname
}
//--------------------------------------------------------
/**
 *	Read attribute master_file_write related method
 *
 *
 *	Data type:	Tango::DevBoolean
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void SlsDetectorControl::read_master_file_write(Tango::Attribute &attr)
{
	DEBUG_STREAM << "SlsDetectorControl::read_master_file_write(Tango::Attribute &attr) entering... " << std::endl;
	/*----- PROTECTED REGION ID(SlsDetectorControl::read_master_file_write) ENABLED START -----*/
    /* clang-format on */
    *attr_master_file_write_read = detector_ptr->getMasterFileWrite();
    attr.set_value(attr_master_file_write_read);
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::read_master_file_write
}
//--------------------------------------------------------
/**
 *	Write attribute master_file_write related method
 *
 *
 *	Data type:	Tango::DevBoolean
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void SlsDetectorControl::write_master_file_write(Tango::WAttribute &attr)
{
	DEBUG_STREAM << "SlsDetectorControl::write_master_file_write(Tango::WAttribute &attr) entering... " << std::endl;
	//	Retrieve write value
	Tango::DevBoolean	w_val;
	attr.get_write_value(w_val);
	/*----- PROTECTED REGION ID(SlsDetectorControl::write_master_file_write) ENABLED START -----*/
    /* clang-format on */
    detector_ptr->setMasterFileWrite(w_val);
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::write_master_file_write
}
//--------------------------------------------------------
/**
 *	Read attribute num_frames related method
 *
 *
 *	Data type:	Tango::DevLong64
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void SlsDetectorControl::read_num_frames(Tango::Attribute &attr)
{
	DEBUG_STREAM << "SlsDetectorControl::read_num_frames(Tango::Attribute &attr) entering... " << std::endl;
	/*----- PROTECTED REGION ID(SlsDetectorControl::read_num_frames) ENABLED START -----*/
    /* clang-format on */
    *attr_num_frames_read = detector_ptr->getNumberOfFrames().front();
    attr.set_value(attr_num_frames_read);
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::read_num_frames
}
//--------------------------------------------------------
/**
 *	Write attribute num_frames related method
 *
 *
 *	Data type:	Tango::DevLong64
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void SlsDetectorControl::write_num_frames(Tango::WAttribute &attr)
{
	DEBUG_STREAM << "SlsDetectorControl::write_num_frames(Tango::WAttribute &attr) entering... " << std::endl;
	//	Retrieve write value
	Tango::DevLong64	w_val;
	attr.get_write_value(w_val);
	/*----- PROTECTED REGION ID(SlsDetectorControl::write_num_frames) ENABLED START -----*/
    /* clang-format on */
    detector_ptr->setNumberOfFrames(w_val);
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::write_num_frames
}
//--------------------------------------------------------
/**
 *	Read attribute num_frames_per_file related method
 *
 *
 *	Data type:	Tango::DevLong
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void SlsDetectorControl::read_num_frames_per_file(Tango::Attribute &attr)
{
	DEBUG_STREAM << "SlsDetectorControl::read_num_frames_per_file(Tango::Attribute &attr) entering... " << std::endl;
	/*----- PROTECTED REGION ID(SlsDetectorControl::read_num_frames_per_file) ENABLED START -----*/
    /* clang-format on */
    //	Set the attribute value
    *attr_num_frames_per_file_read = detector_ptr->getFramesPerFile().front();
    attr.set_value(attr_num_frames_per_file_read);
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::read_num_frames_per_file
}
//--------------------------------------------------------
/**
 *	Write attribute num_frames_per_file related method
 *
 *
 *	Data type:	Tango::DevLong
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void SlsDetectorControl::write_num_frames_per_file(Tango::WAttribute &attr)
{
	DEBUG_STREAM << "SlsDetectorControl::write_num_frames_per_file(Tango::WAttribute &attr) entering... " << std::endl;
	//	Retrieve write value
	Tango::DevLong	w_val;
	attr.get_write_value(w_val);
	/*----- PROTECTED REGION ID(SlsDetectorControl::write_num_frames_per_file) ENABLED START -----*/
    /* clang-format on */
    detector_ptr->setFramesPerFile(w_val);
    /*----- PROTECTED REGION END -----*/ //	SlsDetectorControl::write_num_frames_per_file
}

//--------------------------------------------------------
/**
 *	Read attribute num_triggers related method
 *
 *
 *	Data type:	Tango::DevLong64
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void SlsDetectorControl::read_num_triggers(Tango::Attribute &attr)
{
    DEBUG_STREAM << "SlsDetectorControl::read_num_triggers(Tango::Attribute &attr) entering... " << std::endl;
    /*----- PROTECTED REGION ID(SlsDetectorControl::read_num_triggers) ENABLED START -----*/
    /* clang-format on */
    *attr_num_triggers_read = detector_ptr->getNumberOfTriggers().front();
    attr.set_value(attr_num_triggers_read);
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::read_num_triggers
}
//--------------------------------------------------------
/**
 *	Write attribute num_triggers related method
 *
 *
 *	Data type:	Tango::DevLong64
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void SlsDetectorControl::write_num_triggers(Tango::WAttribute &attr)
{
	DEBUG_STREAM << "SlsDetectorControl::write_num_triggers(Tango::WAttribute &attr) entering... " << std::endl;
	//	Retrieve write value
	Tango::DevLong64	w_val;
	attr.get_write_value(w_val);
	/*----- PROTECTED REGION ID(SlsDetectorControl::write_num_triggers) ENABLED START -----*/
    /* clang-format on */
    detector_ptr->setNumberOfTriggers(w_val);
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::write_num_triggers
}
//--------------------------------------------------------
/**
 *	Read attribute package_version related method
 *
 *
 *	Data type:	Tango::DevString
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void SlsDetectorControl::read_package_version(Tango::Attribute &attr)
{
	DEBUG_STREAM << "SlsDetectorControl::read_package_version(Tango::Attribute &attr) entering... " << std::endl;
	/*----- PROTECTED REGION ID(SlsDetectorControl::read_package_version) ENABLED START -----*/
    /* clang-format on */
    *attr_package_version_read = Tango::string_dup(sls::ToString(detector_ptr->getPackageVersion()));
    attr.set_value(attr_package_version_read);
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::read_package_version
}
//--------------------------------------------------------
/**
 *	Read attribute period related method
 *
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void SlsDetectorControl::read_period(Tango::Attribute &attr)
{
	DEBUG_STREAM << "SlsDetectorControl::read_period(Tango::Attribute &attr) entering... " << std::endl;
	/*----- PROTECTED REGION ID(SlsDetectorControl::read_period) ENABLED START -----*/
    /* clang-format on */
    *attr_period_read = std::chrono::duration<double>(detector_ptr->getPeriod().front()).count();
    attr.set_value(attr_period_read);
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::read_period
}
//--------------------------------------------------------
/**
 *	Write attribute period related method
 *
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void SlsDetectorControl::write_period(Tango::WAttribute &attr)
{
	DEBUG_STREAM << "SlsDetectorControl::write_period(Tango::WAttribute &attr) entering... " << std::endl;
	//	Retrieve write value
	Tango::DevDouble	w_val;
	attr.get_write_value(w_val);
	/*----- PROTECTED REGION ID(SlsDetectorControl::write_period) ENABLED START -----*/
    /* clang-format on */
    auto period = std::chrono::round<std::chrono::nanoseconds>(w_val * 1s);
    detector_ptr->setPeriod(period);
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::write_period
}
//--------------------------------------------------------
/**
 *	Read attribute rx_zmq_data_stream related method
 *
 *
 *	Data type:	Tango::DevBoolean
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void SlsDetectorControl::read_rx_zmq_data_stream(Tango::Attribute &attr)
{
	DEBUG_STREAM << "SlsDetectorControl::read_rx_zmq_data_stream(Tango::Attribute &attr) entering... " << std::endl;
	/*----- PROTECTED REGION ID(SlsDetectorControl::read_rx_zmq_data_stream) ENABLED START -----*/
    /* clang-format on */
    *attr_rx_zmq_data_stream_read = detector_ptr->getRxZmqDataStream().front();
    attr.set_value(attr_rx_zmq_data_stream_read);
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::read_rx_zmq_data_stream
}
//--------------------------------------------------------
/**
 *	Write attribute rx_zmq_data_stream related method
 *
 *
 *	Data type:	Tango::DevBoolean
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void SlsDetectorControl::write_rx_zmq_data_stream(Tango::WAttribute &attr)
{
	DEBUG_STREAM << "SlsDetectorControl::write_rx_zmq_data_stream(Tango::WAttribute &attr) entering... " << std::endl;
	//	Retrieve write value
	Tango::DevBoolean	w_val;
	attr.get_write_value(w_val);
	/*----- PROTECTED REGION ID(SlsDetectorControl::write_rx_zmq_data_stream) ENABLED START -----*/
    /* clang-format on */
    detector_ptr->setRxZmqDataStream(w_val);
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::write_rx_zmq_data_stream
}
//--------------------------------------------------------
/**
 *	Read attribute temperature_fpga related method
 *
 *
 *	Data type:	Tango::DevLong
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void SlsDetectorControl::read_temperature_fpga(Tango::Attribute &attr)
{
	DEBUG_STREAM << "SlsDetectorControl::read_temperature_fpga(Tango::Attribute &attr) entering... " << std::endl;
	/*----- PROTECTED REGION ID(SlsDetectorControl::read_temperature_fpga) ENABLED START -----*/
    /* clang-format on */
    *attr_temperature_fpga_read = detector_ptr->getTemperature(dacIndex::TEMPERATURE_FPGA).front();
    attr.set_value(attr_temperature_fpga_read);
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::read_temperature_fpga
}
//--------------------------------------------------------
/**
 *	Read attribute num_missing_packets related method
 *
 *
 *	Data type:	Tango::DevLong64
 *	Attr type:	Spectrum max = 2
 */
//--------------------------------------------------------
void SlsDetectorControl::read_num_missing_packets(Tango::Attribute &attr)
{
	DEBUG_STREAM << "SlsDetectorControl::read_num_missing_packets(Tango::Attribute &attr) entering... " << std::endl;
	/*----- PROTECTED REGION ID(SlsDetectorControl::read_num_missing_packets) ENABLED START -----*/
    /* clang-format on */
    auto num_missing_packets = detector_ptr->getNumMissingPackets().front();
    auto array_size = std::min(num_missing_packets.size(), static_cast<size_t>(num_missing_packetsAttrib::X_DATA_SIZE));
    for(auto i = 0; i < array_size; ++i)
    {
        attr_num_missing_packets_read[i] = num_missing_packets[i];
    }
    attr.set_value(attr_num_missing_packets_read, array_size);
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::read_num_missing_packets
}

//--------------------------------------------------------
/**
 *	Read attribute adc_phase related method
 *
 *
 *	Data type:	Tango::DevLong
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void SlsDetectorControl::read_adc_phase(Tango::Attribute &attr)
{
	DEBUG_STREAM << "SlsDetectorControl::read_adc_phase(Tango::Attribute &attr) entering... " << std::endl;
	Tango::DevLong	*att_value = get_adc_phase_data_ptr(attr.get_name());
	/*----- PROTECTED REGION ID(SlsDetectorControl::read_adc_phase) ENABLED START -----*/
    /* clang-format on */
    *att_value = detector_ptr->getADCPhaseInDegrees().front();
    attr.set_value(att_value);
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::read_adc_phase
}
//--------------------------------------------------------
/**
 *	Write attribute adc_phase related method
 *
 *
 *	Data type:	Tango::DevLong
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void SlsDetectorControl::write_adc_phase(Tango::WAttribute &attr)
{
	DEBUG_STREAM << "SlsDetectorControl::write_adc_phase(Tango::WAttribute &attr) entering... " << std::endl;
	//	Retrieve write value
	Tango::DevLong	w_val;
	attr.get_write_value(w_val);
	/*----- PROTECTED REGION ID(SlsDetectorControl::write_adc_phase) ENABLED START -----*/
    /* clang-format on */
    detector_ptr->setADCPhaseInDegrees(w_val);
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::write_adc_phase
}
//--------------------------------------------------------
/**
 *	Read attribute delay_after_trigger related method
 *
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void SlsDetectorControl::read_delay_after_trigger(Tango::Attribute &attr)
{
	DEBUG_STREAM << "SlsDetectorControl::read_delay_after_trigger(Tango::Attribute &attr) entering... " << std::endl;
	Tango::DevDouble	*att_value = get_delay_after_trigger_data_ptr(attr.get_name());
	/*----- PROTECTED REGION ID(SlsDetectorControl::read_delay_after_trigger) ENABLED START -----*/
    /* clang-format on */
    auto delay_after_trigger = detector_ptr->getDelayAfterTrigger().front();
    *att_value = std::chrono::duration<double>(delay_after_trigger).count();
    attr.set_value(att_value);
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::read_delay_after_trigger
}
//--------------------------------------------------------
/**
 *	Write attribute delay_after_trigger related method
 *
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void SlsDetectorControl::write_delay_after_trigger(Tango::WAttribute &attr)
{
	DEBUG_STREAM << "SlsDetectorControl::write_delay_after_trigger(Tango::WAttribute &attr) entering... " << std::endl;
	//	Retrieve write value
	Tango::DevDouble	w_val;
	attr.get_write_value(w_val);
	/*----- PROTECTED REGION ID(SlsDetectorControl::write_delay_after_trigger) ENABLED START -----*/
    /* clang-format on */
    auto delay_after_trigger = std::chrono::round<std::chrono::nanoseconds>(w_val * 1s);
    detector_ptr->setDelayAfterTrigger(delay_after_trigger);
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::write_delay_after_trigger
}
//--------------------------------------------------------
/**
 *	Read attribute detector_setting related method
 *
 *
 *	Data type:	Tango::DevEnum (detector_settingEnum)
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void SlsDetectorControl::read_detector_setting(Tango::Attribute &attr)
{
	DEBUG_STREAM << "SlsDetectorControl::read_detector_setting(Tango::Attribute &attr) entering... " << std::endl;
	Tango::DevEnum	*att_value = get_detector_setting_data_ptr(attr.get_name());
	/*----- PROTECTED REGION ID(SlsDetectorControl::read_detector_setting) ENABLED START -----*/
    /* clang-format on */
    auto det_setting = detector_ptr->getSettings().front();
    *att_value = detectorSettingsAdapter_ptr->toTangoEnum(det_setting);
    attr.set_value(att_value);
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::read_detector_setting
}
//--------------------------------------------------------
/**
 *	Write attribute detector_setting related method
 *
 *
 *	Data type:	Tango::DevEnum (detector_settingEnum)
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void SlsDetectorControl::write_detector_setting(Tango::WAttribute &attr)
{
	DEBUG_STREAM << "SlsDetectorControl::write_detector_setting(Tango::WAttribute &attr) entering... " << std::endl;
	//	Retrieve write value
	detector_settingEnum	w_val;
	attr.get_write_value(w_val);
	/*----- PROTECTED REGION ID(SlsDetectorControl::write_detector_setting) ENABLED START -----*/
    /* clang-format on */
    auto det_setting = detectorSettingsAdapter_ptr->toSlsEnum(static_cast<Tango::DevEnum>(w_val));
    detector_ptr->setSettings(det_setting); /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::write_detector_setting
}
//--------------------------------------------------------
/**
 *	Read attribute detector_status related method
 *
 *
 *	Data type:	Tango::DevEnum (detector_statusEnum)
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void SlsDetectorControl::read_detector_status(Tango::Attribute &attr)
{
	DEBUG_STREAM << "SlsDetectorControl::read_detector_status(Tango::Attribute &attr) entering... " << std::endl;
	Tango::DevEnum	*att_value = get_detector_status_data_ptr(attr.get_name());
	/*----- PROTECTED REGION ID(SlsDetectorControl::read_detector_status) ENABLED START -----*/
    /* clang-format on */
    auto det_status = detector_ptr->getDetectorStatus().front();
    *att_value = detStatusAdapter_ptr->toTangoEnum(det_status);
    attr.set_value(att_value);
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::read_detector_status
}
//--------------------------------------------------------
/**
 *	Read attribute file_format related method
 *
 *
 *	Data type:	Tango::DevEnum (file_formatEnum)
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void SlsDetectorControl::read_file_format(Tango::Attribute &attr)
{
	DEBUG_STREAM << "SlsDetectorControl::read_file_format(Tango::Attribute &attr) entering... " << std::endl;
	Tango::DevEnum	*att_value = get_file_format_data_ptr(attr.get_name());
	/*----- PROTECTED REGION ID(SlsDetectorControl::read_file_format) ENABLED START -----*/
    /* clang-format on */
    auto file_format = detector_ptr->getFileFormat().front();
    *att_value = fileFormatAdapter_ptr->toTangoEnum(file_format);
    attr.set_value(att_value);
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::read_file_format
}
//--------------------------------------------------------
/**
 *	Write attribute file_format related method
 *
 *
 *	Data type:	Tango::DevEnum (file_formatEnum)
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void SlsDetectorControl::write_file_format(Tango::WAttribute &attr)
{
	DEBUG_STREAM << "SlsDetectorControl::write_file_format(Tango::WAttribute &attr) entering... " << std::endl;
	//	Retrieve write value
	file_formatEnum	w_val;
	attr.get_write_value(w_val);
	/*----- PROTECTED REGION ID(SlsDetectorControl::write_file_format) ENABLED START -----*/
    /* clang-format on */
    auto file_format = fileFormatAdapter_ptr->toSlsEnum(static_cast<Tango::DevEnum>(w_val));
    try
    {
        detector_ptr->setFileFormat(file_format);
    }
    catch(sls::RuntimeError &e)
    {
        // Tango DevFailed exception must be thrown in case of error
        Tango::Except::throw_exception("TangoException", e.what(), "SlsDetectorControl::write_file_format");
    }
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::write_file_format
}
//--------------------------------------------------------
/**
 *	Read attribute num_frames_left related method
 *
 *
 *	Data type:	Tango::DevLong64
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void SlsDetectorControl::read_num_frames_left(Tango::Attribute &attr)
{
	DEBUG_STREAM << "SlsDetectorControl::read_num_frames_left(Tango::Attribute &attr) entering... " << std::endl;
	Tango::DevLong64	*att_value = get_num_frames_left_data_ptr(attr.get_name());
	/*----- PROTECTED REGION ID(SlsDetectorControl::read_num_frames_left) ENABLED START -----*/
    /* clang-format on */
    *att_value = detector_ptr->getNumberOfFramesLeft().front();
    attr.set_value(att_value);
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::read_num_frames_left
}
//--------------------------------------------------------
/**
 *	Read attribute num_triggers_left related method
 *
 *
 *	Data type:	Tango::DevLong
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void SlsDetectorControl::read_num_triggers_left(Tango::Attribute &attr)
{
	DEBUG_STREAM << "SlsDetectorControl::read_num_triggers_left(Tango::Attribute &attr) entering... " << std::endl;
	Tango::DevLong	*att_value = get_num_triggers_left_data_ptr(attr.get_name());
	/*----- PROTECTED REGION ID(SlsDetectorControl::read_num_triggers_left) ENABLED START -----*/
    /* clang-format on */
    *att_value = detector_ptr->getNumberOfTriggersLeft().front();
    attr.set_value(att_value);
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::read_num_triggers_left
}
//--------------------------------------------------------
/**
 *	Read attribute power_chip related method
 *
 *
 *	Data type:	Tango::DevBoolean
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void SlsDetectorControl::read_power_chip(Tango::Attribute &attr)
{
	DEBUG_STREAM << "SlsDetectorControl::read_power_chip(Tango::Attribute &attr) entering... " << std::endl;
	Tango::DevBoolean	*att_value = get_power_chip_data_ptr(attr.get_name());
	/*----- PROTECTED REGION ID(SlsDetectorControl::read_power_chip) ENABLED START -----*/
    /* clang-format on */
    *att_value = detector_ptr->getPowerChip().front();
    attr.set_value(att_value);
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::read_power_chip
}
//--------------------------------------------------------
/**
 *	Write attribute power_chip related method
 *
 *
 *	Data type:	Tango::DevBoolean
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void SlsDetectorControl::write_power_chip(Tango::WAttribute &attr)
{
	DEBUG_STREAM << "SlsDetectorControl::write_power_chip(Tango::WAttribute &attr) entering... " << std::endl;
	//	Retrieve write value
	Tango::DevBoolean	w_val;
	attr.get_write_value(w_val);
	/*----- PROTECTED REGION ID(SlsDetectorControl::write_power_chip) ENABLED START -----*/
    /* clang-format on */
    detector_ptr->setPowerChip(w_val);
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::write_power_chip
}
//--------------------------------------------------------
/**
 *	Read attribute readout_speed related method
 *
 *
 *	Data type:	Tango::DevEnum (readout_speedEnum)
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void SlsDetectorControl::read_readout_speed(Tango::Attribute &attr)
{
	DEBUG_STREAM << "SlsDetectorControl::read_readout_speed(Tango::Attribute &attr) entering... " << std::endl;
	Tango::DevEnum	*att_value = get_readout_speed_data_ptr(attr.get_name());
	/*----- PROTECTED REGION ID(SlsDetectorControl::read_readout_speed) ENABLED START -----*/
    /* clang-format on */
    auto readout_speed = detector_ptr->getReadoutSpeed().front();
    *att_value = readoutSpeedAdapter_ptr->toTangoEnum(readout_speed);
    attr.set_value(att_value);
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::read_readout_speed
}
//--------------------------------------------------------
/**
 *	Write attribute readout_speed related method
 *
 *
 *	Data type:	Tango::DevEnum (readout_speedEnum)
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void SlsDetectorControl::write_readout_speed(Tango::WAttribute &attr)
{
	DEBUG_STREAM << "SlsDetectorControl::write_readout_speed(Tango::WAttribute &attr) entering... " << std::endl;
	//	Retrieve write value
	readout_speedEnum	w_val;
	attr.get_write_value(w_val);
	/*----- PROTECTED REGION ID(SlsDetectorControl::write_readout_speed) ENABLED START -----*/
    /* clang-format on */
    auto sls_readout_speed = readoutSpeedAdapter_ptr->toSlsEnum(static_cast<Tango::DevEnum>(w_val));
    detector_ptr->setReadoutSpeed(sls_readout_speed);
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::write_readout_speed
}
//--------------------------------------------------------
/**
 *	Read attribute receiver_status related method
 *
 *
 *	Data type:	Tango::DevEnum (receiver_statusEnum)
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void SlsDetectorControl::read_receiver_status(Tango::Attribute &attr)
{
	DEBUG_STREAM << "SlsDetectorControl::read_receiver_status(Tango::Attribute &attr) entering... " << std::endl;
	Tango::DevEnum	*att_value = get_receiver_status_data_ptr(attr.get_name());
	/*----- PROTECTED REGION ID(SlsDetectorControl::read_receiver_status) ENABLED START -----*/
    /* clang-format on */
    auto receiver_status = detector_ptr->getReceiverStatus().front();
    *att_value = recStatusAdapter_ptr->toTangoEnum(receiver_status);
    attr.set_value(att_value);
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::read_receiver_status
}
//--------------------------------------------------------
/**
 *	Read attribute temperature_10ge related method
 *
 *
 *	Data type:	Tango::DevLong
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void SlsDetectorControl::read_temperature_10ge(Tango::Attribute &attr)
{
	DEBUG_STREAM << "SlsDetectorControl::read_temperature_10ge(Tango::Attribute &attr) entering... " << std::endl;
	Tango::DevLong	*att_value = get_temperature_10ge_data_ptr(attr.get_name());
	/*----- PROTECTED REGION ID(SlsDetectorControl::read_temperature_10ge) ENABLED START -----*/
    /* clang-format on */
    *att_value = detector_ptr->getTemperature(dacIndex::TEMPERATURE_10GE).front();
    attr.set_value(att_value);
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::read_temperature_10ge
}
//--------------------------------------------------------
/**
 *	Read attribute temperature_adc related method
 *
 *
 *	Data type:	Tango::DevLong
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void SlsDetectorControl::read_temperature_adc(Tango::Attribute &attr)
{
	DEBUG_STREAM << "SlsDetectorControl::read_temperature_adc(Tango::Attribute &attr) entering... " << std::endl;
	Tango::DevLong	*att_value = get_temperature_adc_data_ptr(attr.get_name());
	/*----- PROTECTED REGION ID(SlsDetectorControl::read_temperature_adc) ENABLED START -----*/
    /* clang-format on */
    *att_value = detector_ptr->getTemperature(dacIndex::TEMPERATURE_ADC).front();
    attr.set_value(att_value);
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::read_temperature_adc
}
//--------------------------------------------------------
/**
 *	Read attribute temperature_dcdc related method
 *
 *
 *	Data type:	Tango::DevLong
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void SlsDetectorControl::read_temperature_dcdc(Tango::Attribute &attr)
{
	DEBUG_STREAM << "SlsDetectorControl::read_temperature_dcdc(Tango::Attribute &attr) entering... " << std::endl;
	Tango::DevLong	*att_value = get_temperature_dcdc_data_ptr(attr.get_name());
	/*----- PROTECTED REGION ID(SlsDetectorControl::read_temperature_dcdc) ENABLED START -----*/
    /* clang-format on */
    *att_value = detector_ptr->getTemperature(dacIndex::TEMPERATURE_DCDC).front();
    attr.set_value(att_value);
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::read_temperature_dcdc
}
//--------------------------------------------------------
/**
 *	Read attribute temperature_fpga2 related method
 *
 *
 *	Data type:	Tango::DevLong
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void SlsDetectorControl::read_temperature_fpga2(Tango::Attribute &attr)
{
	DEBUG_STREAM << "SlsDetectorControl::read_temperature_fpga2(Tango::Attribute &attr) entering... " << std::endl;
	Tango::DevLong	*att_value = get_temperature_fpga2_data_ptr(attr.get_name());
	/*----- PROTECTED REGION ID(SlsDetectorControl::read_temperature_fpga2) ENABLED START -----*/
    /* clang-format on */
    *att_value = detector_ptr->getTemperature(dacIndex::TEMPERATURE_FPGA2).front();
    attr.set_value(att_value);
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::read_temperature_fpga2
}
//--------------------------------------------------------
/**
 *	Read attribute temperature_fpga3 related method
 *
 *
 *	Data type:	Tango::DevLong
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void SlsDetectorControl::read_temperature_fpga3(Tango::Attribute &attr)
{
	DEBUG_STREAM << "SlsDetectorControl::read_temperature_fpga3(Tango::Attribute &attr) entering... " << std::endl;
	Tango::DevLong	*att_value = get_temperature_fpga3_data_ptr(attr.get_name());
	/*----- PROTECTED REGION ID(SlsDetectorControl::read_temperature_fpga3) ENABLED START -----*/
    /* clang-format on */
    *att_value = detector_ptr->getTemperature(dacIndex::TEMPERATURE_FPGA3).front();
    attr.set_value(att_value);
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::read_temperature_fpga3
}
//--------------------------------------------------------
/**
 *	Read attribute temperature_fpgaext related method
 *
 *
 *	Data type:	Tango::DevLong
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void SlsDetectorControl::read_temperature_fpgaext(Tango::Attribute &attr)
{
	DEBUG_STREAM << "SlsDetectorControl::read_temperature_fpgaext(Tango::Attribute &attr) entering... " << std::endl;
	Tango::DevLong	*att_value = get_temperature_fpgaext_data_ptr(attr.get_name());
	/*----- PROTECTED REGION ID(SlsDetectorControl::read_temperature_fpgaext) ENABLED START -----*/
    /* clang-format on */
    *att_value = detector_ptr->getTemperature(dacIndex::TEMPERATURE_FPGAEXT).front();
    attr.set_value(att_value);
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::read_temperature_fpgaext
}
//--------------------------------------------------------
/**
 *	Read attribute temperature_sodl related method
 *
 *
 *	Data type:	Tango::DevLong
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void SlsDetectorControl::read_temperature_sodl(Tango::Attribute &attr)
{
	DEBUG_STREAM << "SlsDetectorControl::read_temperature_sodl(Tango::Attribute &attr) entering... " << std::endl;
	Tango::DevLong	*att_value = get_temperature_sodl_data_ptr(attr.get_name());
	/*----- PROTECTED REGION ID(SlsDetectorControl::read_temperature_sodl) ENABLED START -----*/
    /* clang-format on */
    *att_value = detector_ptr->getTemperature(dacIndex::TEMPERATURE_SODL).front();
    attr.set_value(att_value);
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::read_temperature_sodl
}
//--------------------------------------------------------
/**
 *	Read attribute temperature_sodr related method
 *
 *
 *	Data type:	Tango::DevLong
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void SlsDetectorControl::read_temperature_sodr(Tango::Attribute &attr)
{
	DEBUG_STREAM << "SlsDetectorControl::read_temperature_sodr(Tango::Attribute &attr) entering... " << std::endl;
	Tango::DevLong	*att_value = get_temperature_sodr_data_ptr(attr.get_name());
	/*----- PROTECTED REGION ID(SlsDetectorControl::read_temperature_sodr) ENABLED START -----*/
    /* clang-format on */
    *att_value = detector_ptr->getTemperature(dacIndex::TEMPERATURE_SODR).front();
    attr.set_value(att_value);
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::read_temperature_sodr
}
//--------------------------------------------------------
/**
 *	Read attribute tengiga related method
 *
 *
 *	Data type:	Tango::DevBoolean
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void SlsDetectorControl::read_tengiga(Tango::Attribute &attr)
{
	DEBUG_STREAM << "SlsDetectorControl::read_tengiga(Tango::Attribute &attr) entering... " << std::endl;
	Tango::DevBoolean	*att_value = get_tengiga_data_ptr(attr.get_name());
	/*----- PROTECTED REGION ID(SlsDetectorControl::read_tengiga) ENABLED START -----*/
    /* clang-format on */
    auto tengiga = detector_ptr->getTenGiga().front();
    *att_value = tengiga;
    attr.set_value(att_value);
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::read_tengiga
}
//--------------------------------------------------------
/**
 *	Write attribute tengiga related method
 *
 *
 *	Data type:	Tango::DevBoolean
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void SlsDetectorControl::write_tengiga(Tango::WAttribute &attr)
{
	DEBUG_STREAM << "SlsDetectorControl::write_tengiga(Tango::WAttribute &attr) entering... " << std::endl;
	//	Retrieve write value
	Tango::DevBoolean	w_val;
	attr.get_write_value(w_val);
	/*----- PROTECTED REGION ID(SlsDetectorControl::write_tengiga) ENABLED START -----*/
    /* clang-format on */
    detector_ptr->setTenGiga(w_val);
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::write_tengiga
}
//--------------------------------------------------------
/**
 *	Read attribute timing_mode related method
 *
 *
 *	Data type:	Tango::DevEnum (timing_modeEnum)
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void SlsDetectorControl::read_timing_mode(Tango::Attribute &attr)
{
	DEBUG_STREAM << "SlsDetectorControl::read_timing_mode(Tango::Attribute &attr) entering... " << std::endl;
	Tango::DevEnum	*att_value = get_timing_mode_data_ptr(attr.get_name());
	/*----- PROTECTED REGION ID(SlsDetectorControl::read_timing_mode) ENABLED START -----*/
    /* clang-format on */
    auto timing_mode = detector_ptr->getTimingMode().front();
    *att_value = timingModeAdapter_ptr->toTangoEnum(timing_mode);
    attr.set_value(att_value);
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::read_timing_mode
}
//--------------------------------------------------------
/**
 *	Write attribute timing_mode related method
 *
 *
 *	Data type:	Tango::DevEnum (timing_modeEnum)
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void SlsDetectorControl::write_timing_mode(Tango::WAttribute &attr)
{
	DEBUG_STREAM << "SlsDetectorControl::write_timing_mode(Tango::WAttribute &attr) entering... " << std::endl;
	//	Retrieve write value
	timing_modeEnum	w_val;
	attr.get_write_value(w_val);
	/*----- PROTECTED REGION ID(SlsDetectorControl::write_timing_mode) ENABLED START -----*/
    /* clang-format on */
    auto sls_timing_mode = timingModeAdapter_ptr->toSlsEnum(static_cast<Tango::DevEnum>(w_val));
    detector_ptr->setTimingMode(sls_timing_mode);
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::write_timing_mode
}
//--------------------------------------------------------
/**
 *	Read attribute threshold_energy related method
 *
 *
 *	Data type:	Tango::DevLong
 *	Attr type:	Spectrum max = 3
 */
//--------------------------------------------------------
void SlsDetectorControl::read_threshold_energy(Tango::Attribute &attr)
{
	DEBUG_STREAM << "SlsDetectorControl::read_threshold_energy(Tango::Attribute &attr) entering... " << std::endl;
	Tango::DevLong	*att_value = get_threshold_energy_data_ptr(attr.get_name());
	/*----- PROTECTED REGION ID(SlsDetectorControl::read_threshold_energy) ENABLED START -----*/
    /* clang-format on */
    auto threshold_energy = detector_ptr->getAllThresholdEnergy().front();
    auto array_size = std::min(threshold_energy.size(), static_cast<size_t>(threshold_energyAttrib::X_DATA_SIZE));
    for(size_t i = 0; i < array_size; ++i)
    {
        att_value[i] = threshold_energy[i];
    }
    attr.set_value(att_value, array_size);
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::read_threshold_energy
}
//--------------------------------------------------------
/**
 *	Write attribute threshold_energy related method
 *
 *
 *	Data type:	Tango::DevLong
 *	Attr type:	Spectrum max = 3
 */
//--------------------------------------------------------
void SlsDetectorControl::write_threshold_energy(Tango::WAttribute &attr)
{
	DEBUG_STREAM << "SlsDetectorControl::write_threshold_energy(Tango::WAttribute &attr) entering... " << std::endl;
	//	Retrieve number of write values
	int	w_length = attr.get_write_value_length();

	//	Retrieve pointer on write values (Do not delete !)
	const Tango::DevLong	*w_val;
	attr.get_write_value(w_val);
	/*----- PROTECTED REGION ID(SlsDetectorControl::write_threshold_energy) ENABLED START -----*/
    /* clang-format on */
    std::array<int, threshold_energyAttrib::X_DATA_SIZE> threshold_energy_array;
    std::copy(w_val, w_val + threshold_energyAttrib::X_DATA_SIZE, threshold_energy_array.begin());
    detector_ptr->setThresholdEnergy(threshold_energy_array);
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::write_threshold_energy
}
//--------------------------------------------------------
/**
 *	Method      : SlsDetectorControl::add_dynamic_attributes()
 * Description:  Create the dynamic attributes if any
 *                for specified device.
 */
//--------------------------------------------------------
void SlsDetectorControl::add_dynamic_attributes()
{
	//	Example to add dynamic attribute:
	//	Copy inside the following protected area to create instance(s) at startup.
	//	add_adc_phase_dynamic_attribute("Myadc_phaseAttribute");
	//	add_delay_after_trigger_dynamic_attribute("Mydelay_after_triggerAttribute");
	//	add_detector_setting_dynamic_attribute("Mydetector_settingAttribute");
	//	add_detector_status_dynamic_attribute("Mydetector_statusAttribute");
	//	add_file_format_dynamic_attribute("Myfile_formatAttribute");
	//	add_num_frames_left_dynamic_attribute("Mynum_frames_leftAttribute");
	//	add_num_triggers_left_dynamic_attribute("Mynum_triggers_leftAttribute");
	//	add_power_chip_dynamic_attribute("Mypower_chipAttribute");
	//	add_readout_speed_dynamic_attribute("Myreadout_speedAttribute");
	//	add_receiver_status_dynamic_attribute("Myreceiver_statusAttribute");
	//	add_temperature_10ge_dynamic_attribute("Mytemperature_10geAttribute");
	//	add_temperature_adc_dynamic_attribute("Mytemperature_adcAttribute");
	//	add_temperature_dcdc_dynamic_attribute("Mytemperature_dcdcAttribute");
	//	add_temperature_fpga2_dynamic_attribute("Mytemperature_fpga2Attribute");
	//	add_temperature_fpga3_dynamic_attribute("Mytemperature_fpga3Attribute");
	//	add_temperature_fpgaext_dynamic_attribute("Mytemperature_fpgaextAttribute");
	//	add_temperature_sodl_dynamic_attribute("Mytemperature_sodlAttribute");
	//	add_temperature_sodr_dynamic_attribute("Mytemperature_sodrAttribute");
	//	add_tengiga_dynamic_attribute("MytengigaAttribute");
	//	add_timing_mode_dynamic_attribute("Mytiming_modeAttribute");
	//	add_threshold_energy_dynamic_attribute("Mythreshold_energyAttribute");

	/*----- PROTECTED REGION ID(SlsDetectorControl::add_dynamic_attributes) ENABLED START -----*/
    /* clang-format on */
    for(auto &[k, v] : attributesInfo)
    {
        if(v.available)
        {
            v.registerFunction(k);
        }
    }
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::add_dynamic_attributes
}

//--------------------------------------------------------
/**
 *	Command start_acquire related method
 *
 *
 */
//--------------------------------------------------------
void SlsDetectorControl::start_acquire()
{
	DEBUG_STREAM << "SlsDetectorControl::start_acquire()  - " << device_name << std::endl;
	/*----- PROTECTED REGION ID(SlsDetectorControl::start_acquire) ENABLED START -----*/
    /* clang-format on */
    detector_ptr->startReceiver();
    detector_ptr->startDetector();
    // A detector takes a while after startDetector() execution to change its
    // state. So if there is no delay after startDetector() and self.get_state()
    // check it's very probable that detector will be still in ON mode (even not
    // started to acquire.)
    std::this_thread::sleep_for(0.1s);
    set_state(Tango::RUNNING);
    std::thread(&SlsDetectorControl::check_stop_in_background_acquisition, this).detach();
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::start_acquire
}
//--------------------------------------------------------
/**
 *	Command start_detector related method
 *
 *
 */
//--------------------------------------------------------
void SlsDetectorControl::start_detector()
{
	DEBUG_STREAM << "SlsDetectorControl::start_detector()  - " << device_name << std::endl;
	/*----- PROTECTED REGION ID(SlsDetectorControl::start_detector) ENABLED START -----*/
    /* clang-format on */
    detector_ptr->startDetector();
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::start_detector
}
//--------------------------------------------------------
/**
 *	Command start_receiver related method
 *
 *
 */
//--------------------------------------------------------
void SlsDetectorControl::start_receiver()
{
	DEBUG_STREAM << "SlsDetectorControl::start_receiver()  - " << device_name << std::endl;
	/*----- PROTECTED REGION ID(SlsDetectorControl::start_receiver) ENABLED START -----*/
    /* clang-format on */
    detector_ptr->startReceiver();
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::start_receiver
}
//--------------------------------------------------------
/**
 *	Command stop_acquire related method
 *
 *
 */
//--------------------------------------------------------
void SlsDetectorControl::stop_acquire()
{
	DEBUG_STREAM << "SlsDetectorControl::stop_acquire()  - " << device_name << std::endl;
	/*----- PROTECTED REGION ID(SlsDetectorControl::stop_acquire) ENABLED START -----*/
    /* clang-format on */
    detector_ptr->stopDetector();
    detector_ptr->stopReceiver();
    detector_ptr->clearAcquiringFlag();
    /* A detector might take a while after stopDetector() execution to change its state
     * back to IDLE. Moreover, we need to update the counter of acquisition index.
     * To allow user to differentiate between the acquisition process and the time we
     * updating the acquisition index, we set the state to MOVING during this time.
     */
    set_state(Tango::MOVING);
    std::this_thread::sleep_for(0.1s);
    if(detector_ptr->getFileWrite().front())
    {
        auto acquisitionIndex = detector_ptr->getAcquisitionIndex().front();
        detector_ptr->setAcquisitionIndex(acquisitionIndex + 1);
    }
    set_state(Tango::ON);
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::stop_acquire
}
//--------------------------------------------------------
/**
 *	Command stop_detector related method
 *
 *
 */
//--------------------------------------------------------
void SlsDetectorControl::stop_detector()
{
	DEBUG_STREAM << "SlsDetectorControl::stop_detector()  - " << device_name << std::endl;
	/*----- PROTECTED REGION ID(SlsDetectorControl::stop_detector) ENABLED START -----*/
    /* clang-format on */
    detector_ptr->stopDetector();
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::stop_detector
}
//--------------------------------------------------------
/**
 *	Command stop_receiver related method
 *
 *
 */
//--------------------------------------------------------
void SlsDetectorControl::stop_receiver()
{
	DEBUG_STREAM << "SlsDetectorControl::stop_receiver()  - " << device_name << std::endl;
	/*----- PROTECTED REGION ID(SlsDetectorControl::stop_receiver) ENABLED START -----*/
    /* clang-format on */
    detector_ptr->stopReceiver();
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::stop_receiver
}
//--------------------------------------------------------
/**
 *	Command load_trimbits related method
 *
 *
 *	@param argin
 */
//--------------------------------------------------------
void SlsDetectorControl::load_trimbits(Tango::DevString argin, Tango::Command &command)
{
	DEBUG_STREAM << "SlsDetectorControl::" << command.get_name() << "  - " << device_name << std::endl;
	/*----- PROTECTED REGION ID(SlsDetectorControl::load_trimbits) ENABLED START -----*/
    /* clang-format on */
    auto trimbits_file = std::string(argin);
    detector_ptr->loadTrimbits(trimbits_file);
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::load_trimbits
}
//--------------------------------------------------------
/**
 *	Method      : SlsDetectorControl::add_dynamic_commands()
 * Description:  Create the dynamic commands if any
 *                for specified device.
 */
//--------------------------------------------------------
void SlsDetectorControl::add_dynamic_commands()
{
	//	Example to add dynamic command:
	//	Copy inside the following protected area to instantiate at startup.
	//	add_load_trimbits_dynamic_command("Myload_trimbitsCommand", true);

	/*----- PROTECTED REGION ID(SlsDetectorControl::add_dynamic_commands) ENABLED START -----*/
    /* clang-format on */
    for(auto &[k, v] : commandsInfo)
    {
        if(v.available)
        {
            v.registerFunction(k);
        }
    }
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::add_dynamic_commands
}

/*----- PROTECTED REGION ID(SlsDetectorControl::namespace_ending) ENABLED START -----*/
/* clang-format on */

void SlsDetectorControl::check_stop_in_background_acquisition()
{
    runStatus det_status = detector_ptr->getDetectorStatus().front();
    while(det_status != runStatus::IDLE && det_status != runStatus::RUN_FINISHED && det_status != runStatus::STOPPED)
    {
        std::this_thread::sleep_for(0.1s);
        det_status = detector_ptr->getDetectorStatus().front();
    }
    stop_acquire();
}

void SlsDetectorControl::add_detector_status_dynamic_attribute(
    std::string attname, std::unique_ptr<SlsTangoEnumAdapter<runStatus>> &slsEnumAdapter_ptr)
{
    //	Attribute : detector_status
    detector_statusAttrib *detector_status = new detector_statusAttrib(attname);
    Tango::UserDefaultAttrProp detector_status_prop;
    //	description	not set for detector_status
    //	label	not set for detector_status
    //	unit	not set for detector_status
    //	standard_unit	not set for detector_status
    //	display_unit	not set for detector_status
    //	format	not set for detector_status
    //	max_value	not set for detector_status
    //	min_value	not set for detector_status
    //	max_alarm	not set for detector_status
    //	min_alarm	not set for detector_status
    //	max_warning	not set for detector_status
    //	min_warning	not set for detector_status
    //	delta_t	not set for detector_status
    //	delta_val	not set for detector_status
    detector_status_prop.set_enum_labels(slsEnumAdapter_ptr->slsEnumLabels);
    detector_status->set_default_properties(detector_status_prop);
    //	Not Polled
    detector_status->set_disp_level(Tango::EXPERT);
    //	Not Memorized
    detector_status_data.insert(make_pair(attname, 0));
    add_attribute(detector_status);
}

void SlsDetectorControl::add_receiver_status_dynamic_attribute(
    std::string attname, std::unique_ptr<SlsTangoEnumAdapter<runStatus>> &slsEnumAdapter_ptr)
{
    //	Attribute : receiver_status
    receiver_statusAttrib *receiver_status = new receiver_statusAttrib(attname);
    Tango::UserDefaultAttrProp receiver_status_prop;
    //	description	not set for receiver_status
    //	label	not set for receiver_status
    //	unit	not set for receiver_status
    //	standard_unit	not set for receiver_status
    //	display_unit	not set for receiver_status
    //	format	not set for receiver_status
    //	max_value	not set for receiver_status
    //	min_value	not set for receiver_status
    //	max_alarm	not set for receiver_status
    //	min_alarm	not set for receiver_status
    //	max_warning	not set for receiver_status
    //	min_warning	not set for receiver_status
    //	delta_t	not set for receiver_status
    //	delta_val	not set for receiver_status
    receiver_status_prop.set_enum_labels(slsEnumAdapter_ptr->slsEnumLabels);
    receiver_status->set_default_properties(receiver_status_prop);
    //	Not Polled
    receiver_status->set_disp_level(Tango::EXPERT);
    //	Not Memorized
    receiver_status_data.insert(make_pair(attname, 0));
    add_attribute(receiver_status);
}

void SlsDetectorControl::add_readout_speed_dynamic_attribute(
    std::string attname, std::unique_ptr<SlsTangoEnumAdapter<speedLevel>> &slsEnumAdapter_ptr)
{
    //	Attribute : readout_speed
    readout_speedAttrib *readout_speed = new readout_speedAttrib(attname);
    Tango::UserDefaultAttrProp readout_speed_prop;
    //	description	not set for readout_speed
    //	label	not set for readout_speed
    //	unit	not set for readout_speed
    //	standard_unit	not set for readout_speed
    //	display_unit	not set for readout_speed
    //	format	not set for readout_speed
    //	max_value	not set for readout_speed
    //	min_value	not set for readout_speed
    //	max_alarm	not set for readout_speed
    //	min_alarm	not set for readout_speed
    //	max_warning	not set for readout_speed
    //	min_warning	not set for readout_speed
    //	delta_t	not set for readout_speed
    //	delta_val	not set for readout_speed
    readout_speed_prop.set_enum_labels(slsEnumAdapter_ptr->slsEnumLabels);
    readout_speed->set_default_properties(readout_speed_prop);
    //	Not Polled
    readout_speed->set_disp_level(Tango::OPERATOR);
    //	Not Memorized
    readout_speed_data.insert(make_pair(attname, 0));
    add_attribute(readout_speed);
}

void SlsDetectorControl::add_detector_setting_dynamic_attribute(
    std::string attname, std::unique_ptr<SlsTangoEnumAdapter<detectorSettings>> &slsEnumAdapter_ptr)
{
    //	Attribute : detector_setting
    detector_settingAttrib *detector_setting = new detector_settingAttrib(attname);
    Tango::UserDefaultAttrProp detector_setting_prop;
    //	description	not set for detector_setting
    //	label	not set for detector_setting
    //	unit	not set for detector_setting
    //	standard_unit	not set for detector_setting
    //	display_unit	not set for detector_setting
    //	format	not set for detector_setting
    //	max_value	not set for detector_setting
    //	min_value	not set for detector_setting
    //	max_alarm	not set for detector_setting
    //	min_alarm	not set for detector_setting
    //	max_warning	not set for detector_setting
    //	min_warning	not set for detector_setting
    //	delta_t	not set for detector_setting
    //	delta_val	not set for detector_setting
    detector_setting_prop.set_enum_labels(slsEnumAdapter_ptr->slsEnumLabels);
    detector_setting->set_default_properties(detector_setting_prop);
    //	Not Polled
    detector_setting->set_disp_level(Tango::OPERATOR);
    //	Not Memorized
    detector_setting_data.insert(make_pair(attname, 0));
    add_attribute(detector_setting);
}

void SlsDetectorControl::add_timing_mode_dynamic_attribute(
    std::string attname, std::unique_ptr<SlsTangoEnumAdapter<timingMode>> &slsEnumAdapter_ptr)
{
    //	Attribute : timing_mode
    timing_modeAttrib *timing_mode = new timing_modeAttrib(attname);
    Tango::UserDefaultAttrProp timing_mode_prop;
    //	description	not set for timing_mode
    //	label	not set for timing_mode
    //	unit	not set for detector_setting
    //	standard_unit	not set for detector_setting
    //	display_unit	not set for detector_setting
    //	format	not set for detector_setting
    //	max_value	not set for detector_setting
    //	min_value	not set for detector_setting
    //	max_alarm	not set for detector_setting
    //	min_alarm	not set for detector_setting
    //	max_warning	not set for detector_setting
    //	min_warning	not set for detector_setting
    //	delta_t	not set for detector_setting
    //	delta_val	not set for detector_setting
    timing_mode_prop.set_enum_labels(slsEnumAdapter_ptr->slsEnumLabels);
    timing_mode->set_default_properties(timing_mode_prop);
    //	Not Polled
    timing_mode->set_disp_level(Tango::OPERATOR);
    //	Not Memorized
    timing_mode_data.insert(make_pair(attname, 0));
    add_attribute(timing_mode);
}

void SlsDetectorControl::add_file_format_dynamic_attribute(
    std::string attname, std::unique_ptr<SlsTangoEnumAdapter<fileFormat>> &slsEnumAdapter_ptr)
{
    //	Attribute : file_format
    file_formatAttrib *file_format = new file_formatAttrib(attname);
    Tango::UserDefaultAttrProp file_format_prop;
    //	description	not set for file_format
    //	label	not set for file_format
    //	unit	not set for file_format
    //	standard_unit	not set for file_format
    //	display_unit	not set for file_format
    //	format	not set for file_format
    //	max_value	not set for file_format
    //	min_value	not set for file_format
    //	max_alarm	not set for file_format
    //	min_alarm	not set for file_format
    //	max_warning	not set for file_format
    //	min_warning	not set for file_format
    //	delta_t	not set for file_format
    //	delta_val	not set for file_format
    file_format_prop.set_enum_labels(slsEnumAdapter_ptr->slsEnumLabels);
    file_format->set_default_properties(file_format_prop);
    //	Not Polled
    file_format->set_disp_level(Tango::OPERATOR);
    //	Not Memorized
    file_format_data.insert(make_pair(attname, 0));
    add_attribute(file_format);
}

/* clang-format off */// //--------------------------------------------------------
// /**
//  *	Read attribute scalar_attribute related method
//  *
//  *
//  *	Data type:	Tango::DevBoolean
//  *	Attr type:	Scalar
//  */
// //--------------------------------------------------------
// void SlsDetectorControl::read_scalar_attribute(Tango::Attribute &attr)
// {
// 	DEBUG_STREAM << "SlsDetectorControl::read_scalar_attribute(Tango::Attribute &attr) entering... " << std::endl;
// 	/* clang-format on */
// 	//	Set the attribute value
// 	attr.set_value(attr_scalar_attribute_read);
// 	/* clang-format off */
// }

// //--------------------------------------------------------
// /**
//  *	Write attribute scalar_attribute related method
//  *
//  *
//  *	Data type:	Tango::DevBoolean
//  *	Attr type:	Scalar
//  */
// //--------------------------------------------------------
// void SlsDetectorControl::write_scalar_attribute(Tango::WAttribute &attr)
// {
// 	DEBUG_STREAM << "SlsDetectorControl::write_scalar_attribute(Tango::WAttribute &attr) entering... " << std::endl;
// 	//	Retrieve write value
// 	Tango::DevBoolean	w_val;
// 	attr.get_write_value(w_val);
// 	/* clang-format on */
// 	//	Add your own code
// 	/* clang-format off */
// }

// //--------------------------------------------------------
// /**
//  *	Read attribute file_format related method
//  *
//  *
//  *	Data type:	Tango::DevEnum (file_formatEnum)
//  *	Attr type:	Scalar
//  */
// //--------------------------------------------------------
// void SlsDetectorControl::read_file_format(Tango::Attribute &attr)
// {
// 	DEBUG_STREAM << "SlsDetectorControl::read_file_format(Tango::Attribute &attr) entering... " << std::endl;
// 	/* clang-format on */
// 	//	Set the attribute value
// 	attr.set_value(attr_file_format_read);
// 	/* clang-format off */
// }

// //--------------------------------------------------------
// /**
//  *	Write attribute file_format related method
//  *
//  *
//  *	Data type:	Tango::DevEnum (file_formatEnum)
//  *	Attr type:	Scalar
//  */
// //--------------------------------------------------------
// void SlsDetectorControl::write_file_format(Tango::WAttribute &attr)
// {
// 	DEBUG_STREAM << "SlsDetectorControl::write_file_format(Tango::WAttribute &attr) entering... " << std::endl;
// 	//	Retrieve write value
// 	file_formatEnum	w_val;
// 	attr.get_write_value(w_val);
// 	/* clang-format on */
// 	//	Add your own code
// 	/* clang-format off */
// }

// //--------------------------------------------------------
// /**
//  *	Read attribute full_file_name related method
//  *
//  *
//  *	Data type:	Tango::DevString
//  *	Attr type:	Scalar
//  */
// //--------------------------------------------------------
// void SlsDetectorControl::read_full_file_name(Tango::Attribute &attr)
// {
// 	DEBUG_STREAM << "SlsDetectorControl::read_full_file_name(Tango::Attribute &attr) entering... " << std::endl;
//     /* clang-format on */
// 	// build string
// 	// default run File Name: [file name prefix]_d[module index]_f[file index]_[acquisition index].[file format] eg. run_d0_f0_5.raw
// 	std::string file_name_prefix = detector_ptr->getFileNamePrefix().front();
// 	int module_index = 0;
// 	auto file_index = detector_ptr->getAcquisitionIndex().front();
// 	auto file_format = detector_ptr->getFileFormat().front();
// 	std::string full_string = file_name_prefix + "_d" + std::to_string(module_index) + "_f" + std::to_string(file_index) + "_" + std::to_string(file_format);
// 	*attr_full_file_name_read = Tango::string_dup(full_string);
// 	attr.set_value(attr_full_file_name_read);
//     /* clang-format off */
// }

// //--------------------------------------------------------
// /**
//  *	Read attribute detector_status related method
//  *
//  *
//  *	Data type:	Tango::DevEnum (detector_statusEnum)
//  *	Attr type:	Scalar
//  */
// //--------------------------------------------------------
// void SlsDetectorControl::read_detector_status(Tango::Attribute &attr)
// {
// 	DEBUG_STREAM << "SlsDetectorControl::read_detector_status(Tango::Attribute &attr) entering... " << std::endl;
// 	/* clang-format on */
// 	//	Set the attribute value
// 	attr.set_value(attr_detector_status_read);
// 	/* clang-format off */
// }

// //--------------------------------------------------------
// /**
//  *	Read attribute receiver_status related method
//  *
//  *
//  *	Data type:	Tango::DevEnum (receiver_statusEnum)
//  *	Attr type:	Scalar
//  */
// //--------------------------------------------------------
// void SlsDetectorControl::read_receiver_status(Tango::Attribute &attr)
// {
// 	DEBUG_STREAM << "SlsDetectorControl::read_receiver_status(Tango::Attribute &attr) entering... " << std::endl;
// 	/* clang-format on */
// 	//	Set the attribute value
// 	attr.set_value(attr_receiver_status_read);
// 	/* clang-format off */
// }


/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::namespace_ending
} //	namespace
