/*----- PROTECTED REGION ID(SlsDetectorControlClass.h) ENABLED START -----*/
/* clang-format on */
//=============================================================================
//
// file :        SlsDetectorControlClass.h
//
// description : Include for the SlsDetectorControl root class.
//               This class is the singleton class for
//                the SlsDetectorControl device class.
//               It contains all properties and methods which the
//               SlsDetectorControl requires only once e.g. the commands.
//
// project :     tango-slsdetectorcontrol
//
// This file is part of Tango device class.
//
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the MIT licence.
//
//
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================

#ifndef SlsDetectorControlClass_H
#define SlsDetectorControlClass_H

#include "SlsDetectorControl.h"
#include <tango/tango.h>

/* clang-format off */
/*----- PROTECTED REGION END -----*/	//	SlsDetectorControlClass.h


namespace SlsDetectorControl_ns
{
/*----- PROTECTED REGION ID(SlsDetectorControlClass::classes for dynamic creation) ENABLED START -----*/
/* clang-format on */

/* clang-format off */
/*----- PROTECTED REGION END -----*/	//	SlsDetectorControlClass::classes for dynamic creation

//=========================================
//	Define classes for attributes
//=========================================
//	Attribute acquisition_index class definition
class acquisition_indexAttrib: public Tango::Attr
{
public:
	acquisition_indexAttrib():Attr("acquisition_index",
			Tango::DEV_LONG64, Tango::READ_WRITE) {};
	~acquisition_indexAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<SlsDetectorControl *>(dev))->read_acquisition_index(att);}
	virtual void write(Tango::DeviceImpl *dev,Tango::WAttribute &att)
		{(static_cast<SlsDetectorControl *>(dev))->write_acquisition_index(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<SlsDetectorControl *>(dev))->is_acquisition_index_allowed(ty);}
};

//	Attribute detector_type class definition
class detector_typeAttrib: public Tango::Attr
{
public:
	detector_typeAttrib():Attr("detector_type",
			Tango::DEV_STRING, Tango::READ) {};
	~detector_typeAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<SlsDetectorControl *>(dev))->read_detector_type(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<SlsDetectorControl *>(dev))->is_detector_type_allowed(ty);}
};

//	Attribute dynamic_range class definition
class dynamic_rangeAttrib: public Tango::Attr
{
public:
	dynamic_rangeAttrib():Attr("dynamic_range",
			Tango::DEV_LONG, Tango::READ_WRITE) {};
	~dynamic_rangeAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<SlsDetectorControl *>(dev))->read_dynamic_range(att);}
	virtual void write(Tango::DeviceImpl *dev,Tango::WAttribute &att)
		{(static_cast<SlsDetectorControl *>(dev))->write_dynamic_range(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<SlsDetectorControl *>(dev))->is_dynamic_range_allowed(ty);}
};

//	Attribute exptime class definition
class exptimeAttrib: public Tango::Attr
{
public:
	exptimeAttrib():Attr("exptime",
			Tango::DEV_DOUBLE, Tango::READ_WRITE) {};
	~exptimeAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<SlsDetectorControl *>(dev))->read_exptime(att);}
	virtual void write(Tango::DeviceImpl *dev,Tango::WAttribute &att)
		{(static_cast<SlsDetectorControl *>(dev))->write_exptime(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<SlsDetectorControl *>(dev))->is_exptime_allowed(ty);}
};

//	Attribute file_name class definition
class file_nameAttrib: public Tango::Attr
{
public:
	file_nameAttrib():Attr("file_name",
			Tango::DEV_STRING, Tango::READ) {};
	~file_nameAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<SlsDetectorControl *>(dev))->read_file_name(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<SlsDetectorControl *>(dev))->is_file_name_allowed(ty);}
};

//	Attribute file_name_prefix class definition
class file_name_prefixAttrib: public Tango::Attr
{
public:
	file_name_prefixAttrib():Attr("file_name_prefix",
			Tango::DEV_STRING, Tango::READ_WRITE) {};
	~file_name_prefixAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<SlsDetectorControl *>(dev))->read_file_name_prefix(att);}
	virtual void write(Tango::DeviceImpl *dev,Tango::WAttribute &att)
		{(static_cast<SlsDetectorControl *>(dev))->write_file_name_prefix(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<SlsDetectorControl *>(dev))->is_file_name_prefix_allowed(ty);}
};

//	Attribute file_overwrite class definition
class file_overwriteAttrib: public Tango::Attr
{
public:
	file_overwriteAttrib():Attr("file_overwrite",
			Tango::DEV_BOOLEAN, Tango::READ_WRITE) {};
	~file_overwriteAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<SlsDetectorControl *>(dev))->read_file_overwrite(att);}
	virtual void write(Tango::DeviceImpl *dev,Tango::WAttribute &att)
		{(static_cast<SlsDetectorControl *>(dev))->write_file_overwrite(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<SlsDetectorControl *>(dev))->is_file_overwrite_allowed(ty);}
};

//	Attribute file_path class definition
class file_pathAttrib: public Tango::Attr
{
public:
	file_pathAttrib():Attr("file_path",
			Tango::DEV_STRING, Tango::READ_WRITE) {};
	~file_pathAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<SlsDetectorControl *>(dev))->read_file_path(att);}
	virtual void write(Tango::DeviceImpl *dev,Tango::WAttribute &att)
		{(static_cast<SlsDetectorControl *>(dev))->write_file_path(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<SlsDetectorControl *>(dev))->is_file_path_allowed(ty);}
};

//	Attribute file_write class definition
class file_writeAttrib: public Tango::Attr
{
public:
	file_writeAttrib():Attr("file_write",
			Tango::DEV_BOOLEAN, Tango::READ_WRITE) {};
	~file_writeAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<SlsDetectorControl *>(dev))->read_file_write(att);}
	virtual void write(Tango::DeviceImpl *dev,Tango::WAttribute &att)
		{(static_cast<SlsDetectorControl *>(dev))->write_file_write(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<SlsDetectorControl *>(dev))->is_file_write_allowed(ty);}
};

//	Attribute firmware_version class definition
class firmware_versionAttrib: public Tango::Attr
{
public:
	firmware_versionAttrib():Attr("firmware_version",
			Tango::DEV_LONG64, Tango::READ) {};
	~firmware_versionAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<SlsDetectorControl *>(dev))->read_firmware_version(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<SlsDetectorControl *>(dev))->is_firmware_version_allowed(ty);}
};

//	Attribute high_voltage class definition
class high_voltageAttrib: public Tango::Attr
{
public:
	high_voltageAttrib():Attr("high_voltage",
			Tango::DEV_LONG, Tango::READ_WRITE) {};
	~high_voltageAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<SlsDetectorControl *>(dev))->read_high_voltage(att);}
	virtual void write(Tango::DeviceImpl *dev,Tango::WAttribute &att)
		{(static_cast<SlsDetectorControl *>(dev))->write_high_voltage(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<SlsDetectorControl *>(dev))->is_high_voltage_allowed(ty);}
};

//	Attribute hostname class definition
class hostnameAttrib: public Tango::Attr
{
public:
	hostnameAttrib():Attr("hostname",
			Tango::DEV_STRING, Tango::READ) {};
	~hostnameAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<SlsDetectorControl *>(dev))->read_hostname(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<SlsDetectorControl *>(dev))->is_hostname_allowed(ty);}
};

//	Attribute master_file_write class definition
class master_file_writeAttrib: public Tango::Attr
{
public:
	master_file_writeAttrib():Attr("master_file_write",
			Tango::DEV_BOOLEAN, Tango::READ_WRITE) {};
	~master_file_writeAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<SlsDetectorControl *>(dev))->read_master_file_write(att);}
	virtual void write(Tango::DeviceImpl *dev,Tango::WAttribute &att)
		{(static_cast<SlsDetectorControl *>(dev))->write_master_file_write(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<SlsDetectorControl *>(dev))->is_master_file_write_allowed(ty);}
};

//	Attribute num_frames class definition
class num_framesAttrib: public Tango::Attr
{
public:
	num_framesAttrib():Attr("num_frames",
			Tango::DEV_LONG64, Tango::READ_WRITE) {};
	~num_framesAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<SlsDetectorControl *>(dev))->read_num_frames(att);}
	virtual void write(Tango::DeviceImpl *dev,Tango::WAttribute &att)
		{(static_cast<SlsDetectorControl *>(dev))->write_num_frames(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<SlsDetectorControl *>(dev))->is_num_frames_allowed(ty);}
};

//	Attribute num_frames_per_file class definition
class num_frames_per_fileAttrib: public Tango::Attr
{
public:
	num_frames_per_fileAttrib():Attr("num_frames_per_file",
			Tango::DEV_LONG, Tango::READ_WRITE) {};
	~num_frames_per_fileAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<SlsDetectorControl *>(dev))->read_num_frames_per_file(att);}
	virtual void write(Tango::DeviceImpl *dev,Tango::WAttribute &att)
		{(static_cast<SlsDetectorControl *>(dev))->write_num_frames_per_file(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<SlsDetectorControl *>(dev))->is_num_frames_per_file_allowed(ty);}
};

//	Attribute num_triggers class definition
class num_triggersAttrib: public Tango::Attr
{
public:
	num_triggersAttrib():Attr("num_triggers",
			Tango::DEV_LONG64, Tango::READ_WRITE) {};
	~num_triggersAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<SlsDetectorControl *>(dev))->read_num_triggers(att);}
	virtual void write(Tango::DeviceImpl *dev,Tango::WAttribute &att)
		{(static_cast<SlsDetectorControl *>(dev))->write_num_triggers(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<SlsDetectorControl *>(dev))->is_num_triggers_allowed(ty);}
};

//	Attribute package_version class definition
class package_versionAttrib: public Tango::Attr
{
public:
	package_versionAttrib():Attr("package_version",
			Tango::DEV_STRING, Tango::READ) {};
	~package_versionAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<SlsDetectorControl *>(dev))->read_package_version(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<SlsDetectorControl *>(dev))->is_package_version_allowed(ty);}
};

//	Attribute period class definition
class periodAttrib: public Tango::Attr
{
public:
	periodAttrib():Attr("period",
			Tango::DEV_DOUBLE, Tango::READ_WRITE) {};
	~periodAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<SlsDetectorControl *>(dev))->read_period(att);}
	virtual void write(Tango::DeviceImpl *dev,Tango::WAttribute &att)
		{(static_cast<SlsDetectorControl *>(dev))->write_period(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<SlsDetectorControl *>(dev))->is_period_allowed(ty);}
};

//	Attribute rx_zmq_data_stream class definition
class rx_zmq_data_streamAttrib: public Tango::Attr
{
public:
	rx_zmq_data_streamAttrib():Attr("rx_zmq_data_stream",
			Tango::DEV_BOOLEAN, Tango::READ_WRITE) {};
	~rx_zmq_data_streamAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<SlsDetectorControl *>(dev))->read_rx_zmq_data_stream(att);}
	virtual void write(Tango::DeviceImpl *dev,Tango::WAttribute &att)
		{(static_cast<SlsDetectorControl *>(dev))->write_rx_zmq_data_stream(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<SlsDetectorControl *>(dev))->is_rx_zmq_data_stream_allowed(ty);}
};

//	Attribute temperature_fpga class definition
class temperature_fpgaAttrib: public Tango::Attr
{
public:
	temperature_fpgaAttrib():Attr("temperature_fpga",
			Tango::DEV_LONG, Tango::READ) {};
	~temperature_fpgaAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<SlsDetectorControl *>(dev))->read_temperature_fpga(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<SlsDetectorControl *>(dev))->is_temperature_fpga_allowed(ty);}
};

//	Attribute num_missing_packets class definition
class num_missing_packetsAttrib: public Tango::SpectrumAttr
{
public:
	// Constants for num_missing_packets attribute
	constexpr static long X_DATA_SIZE = 2;
	num_missing_packetsAttrib():SpectrumAttr("num_missing_packets",
			Tango::DEV_LONG64, Tango::READ, num_missing_packetsAttrib::X_DATA_SIZE) {};
	~num_missing_packetsAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<SlsDetectorControl *>(dev))->read_num_missing_packets(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<SlsDetectorControl *>(dev))->is_num_missing_packets_allowed(ty);}
};


//=========================================
//	Define classes for dynamic attributes
//=========================================
//	Attribute adc_phase class definition
class adc_phaseAttrib: public Tango::Attr
{
public:
	adc_phaseAttrib(const std::string &att_name):Attr(att_name.c_str(),
			Tango::DEV_LONG, Tango::READ_WRITE) {};
	~adc_phaseAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<SlsDetectorControl *>(dev))->read_adc_phase(att);}
	virtual void write(Tango::DeviceImpl *dev,Tango::WAttribute &att)
		{(static_cast<SlsDetectorControl *>(dev))->write_adc_phase(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<SlsDetectorControl *>(dev))->is_adc_phase_allowed(ty);}
};

//	Attribute delay_after_trigger class definition
class delay_after_triggerAttrib: public Tango::Attr
{
public:
	delay_after_triggerAttrib(const std::string &att_name):Attr(att_name.c_str(),
			Tango::DEV_DOUBLE, Tango::READ_WRITE) {};
	~delay_after_triggerAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<SlsDetectorControl *>(dev))->read_delay_after_trigger(att);}
	virtual void write(Tango::DeviceImpl *dev,Tango::WAttribute &att)
		{(static_cast<SlsDetectorControl *>(dev))->write_delay_after_trigger(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<SlsDetectorControl *>(dev))->is_delay_after_trigger_allowed(ty);}
};

//	Attribute detector_setting class definition
class detector_settingAttrib: public Tango::Attr
{
public:
	detector_settingAttrib(const std::string &att_name):Attr(att_name.c_str(),
			Tango::DEV_ENUM, Tango::READ_WRITE) {};
	~detector_settingAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<SlsDetectorControl *>(dev))->read_detector_setting(att);}
	virtual void write(Tango::DeviceImpl *dev,Tango::WAttribute &att)
		{(static_cast<SlsDetectorControl *>(dev))->write_detector_setting(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<SlsDetectorControl *>(dev))->is_detector_setting_allowed(ty);}
	virtual bool same_type(const std::type_info &in_type) {return typeid(detector_settingEnum) == in_type;}
	virtual std::string get_enum_type() {return std::string("detector_settingEnum");}
};

//	Attribute detector_status class definition
class detector_statusAttrib: public Tango::Attr
{
public:
	detector_statusAttrib(const std::string &att_name):Attr(att_name.c_str(),
			Tango::DEV_ENUM, Tango::READ) {};
	~detector_statusAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<SlsDetectorControl *>(dev))->read_detector_status(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<SlsDetectorControl *>(dev))->is_detector_status_allowed(ty);}
	virtual bool same_type(const std::type_info &in_type) {return typeid(detector_statusEnum) == in_type;}
	virtual std::string get_enum_type() {return std::string("detector_statusEnum");}
};

//	Attribute file_format class definition
class file_formatAttrib: public Tango::Attr
{
public:
	file_formatAttrib(const std::string &att_name):Attr(att_name.c_str(),
			Tango::DEV_ENUM, Tango::READ_WRITE) {};
	~file_formatAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<SlsDetectorControl *>(dev))->read_file_format(att);}
	virtual void write(Tango::DeviceImpl *dev,Tango::WAttribute &att)
		{(static_cast<SlsDetectorControl *>(dev))->write_file_format(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<SlsDetectorControl *>(dev))->is_file_format_allowed(ty);}
	virtual bool same_type(const std::type_info &in_type) {return typeid(file_formatEnum) == in_type;}
	virtual std::string get_enum_type() {return std::string("file_formatEnum");}
};

//	Attribute num_frames_left class definition
class num_frames_leftAttrib: public Tango::Attr
{
public:
	num_frames_leftAttrib(const std::string &att_name):Attr(att_name.c_str(),
			Tango::DEV_LONG64, Tango::READ) {};
	~num_frames_leftAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<SlsDetectorControl *>(dev))->read_num_frames_left(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<SlsDetectorControl *>(dev))->is_num_frames_left_allowed(ty);}
};

//	Attribute num_triggers_left class definition
class num_triggers_leftAttrib: public Tango::Attr
{
public:
	num_triggers_leftAttrib(const std::string &att_name):Attr(att_name.c_str(),
			Tango::DEV_LONG, Tango::READ) {};
	~num_triggers_leftAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<SlsDetectorControl *>(dev))->read_num_triggers_left(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<SlsDetectorControl *>(dev))->is_num_triggers_left_allowed(ty);}
};

//	Attribute power_chip class definition
class power_chipAttrib: public Tango::Attr
{
public:
	power_chipAttrib(const std::string &att_name):Attr(att_name.c_str(),
			Tango::DEV_BOOLEAN, Tango::READ_WRITE) {};
	~power_chipAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<SlsDetectorControl *>(dev))->read_power_chip(att);}
	virtual void write(Tango::DeviceImpl *dev,Tango::WAttribute &att)
		{(static_cast<SlsDetectorControl *>(dev))->write_power_chip(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<SlsDetectorControl *>(dev))->is_power_chip_allowed(ty);}
};

//	Attribute readout_speed class definition
class readout_speedAttrib: public Tango::Attr
{
public:
	readout_speedAttrib(const std::string &att_name):Attr(att_name.c_str(),
			Tango::DEV_ENUM, Tango::READ_WRITE) {};
	~readout_speedAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<SlsDetectorControl *>(dev))->read_readout_speed(att);}
	virtual void write(Tango::DeviceImpl *dev,Tango::WAttribute &att)
		{(static_cast<SlsDetectorControl *>(dev))->write_readout_speed(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<SlsDetectorControl *>(dev))->is_readout_speed_allowed(ty);}
	virtual bool same_type(const std::type_info &in_type) {return typeid(readout_speedEnum) == in_type;}
	virtual std::string get_enum_type() {return std::string("readout_speedEnum");}
};

//	Attribute receiver_status class definition
class receiver_statusAttrib: public Tango::Attr
{
public:
	receiver_statusAttrib(const std::string &att_name):Attr(att_name.c_str(),
			Tango::DEV_ENUM, Tango::READ) {};
	~receiver_statusAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<SlsDetectorControl *>(dev))->read_receiver_status(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<SlsDetectorControl *>(dev))->is_receiver_status_allowed(ty);}
	virtual bool same_type(const std::type_info &in_type) {return typeid(receiver_statusEnum) == in_type;}
	virtual std::string get_enum_type() {return std::string("receiver_statusEnum");}
};

//	Attribute temperature_10ge class definition
class temperature_10geAttrib: public Tango::Attr
{
public:
	temperature_10geAttrib(const std::string &att_name):Attr(att_name.c_str(),
			Tango::DEV_LONG, Tango::READ) {};
	~temperature_10geAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<SlsDetectorControl *>(dev))->read_temperature_10ge(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<SlsDetectorControl *>(dev))->is_temperature_10ge_allowed(ty);}
};

//	Attribute temperature_adc class definition
class temperature_adcAttrib: public Tango::Attr
{
public:
	temperature_adcAttrib(const std::string &att_name):Attr(att_name.c_str(),
			Tango::DEV_LONG, Tango::READ) {};
	~temperature_adcAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<SlsDetectorControl *>(dev))->read_temperature_adc(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<SlsDetectorControl *>(dev))->is_temperature_adc_allowed(ty);}
};

//	Attribute temperature_dcdc class definition
class temperature_dcdcAttrib: public Tango::Attr
{
public:
	temperature_dcdcAttrib(const std::string &att_name):Attr(att_name.c_str(),
			Tango::DEV_LONG, Tango::READ) {};
	~temperature_dcdcAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<SlsDetectorControl *>(dev))->read_temperature_dcdc(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<SlsDetectorControl *>(dev))->is_temperature_dcdc_allowed(ty);}
};

//	Attribute temperature_fpga2 class definition
class temperature_fpga2Attrib: public Tango::Attr
{
public:
	temperature_fpga2Attrib(const std::string &att_name):Attr(att_name.c_str(),
			Tango::DEV_LONG, Tango::READ) {};
	~temperature_fpga2Attrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<SlsDetectorControl *>(dev))->read_temperature_fpga2(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<SlsDetectorControl *>(dev))->is_temperature_fpga2_allowed(ty);}
};

//	Attribute temperature_fpga3 class definition
class temperature_fpga3Attrib: public Tango::Attr
{
public:
	temperature_fpga3Attrib(const std::string &att_name):Attr(att_name.c_str(),
			Tango::DEV_LONG, Tango::READ) {};
	~temperature_fpga3Attrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<SlsDetectorControl *>(dev))->read_temperature_fpga3(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<SlsDetectorControl *>(dev))->is_temperature_fpga3_allowed(ty);}
};

//	Attribute temperature_fpgaext class definition
class temperature_fpgaextAttrib: public Tango::Attr
{
public:
	temperature_fpgaextAttrib(const std::string &att_name):Attr(att_name.c_str(),
			Tango::DEV_LONG, Tango::READ) {};
	~temperature_fpgaextAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<SlsDetectorControl *>(dev))->read_temperature_fpgaext(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<SlsDetectorControl *>(dev))->is_temperature_fpgaext_allowed(ty);}
};

//	Attribute temperature_sodl class definition
class temperature_sodlAttrib: public Tango::Attr
{
public:
	temperature_sodlAttrib(const std::string &att_name):Attr(att_name.c_str(),
			Tango::DEV_LONG, Tango::READ) {};
	~temperature_sodlAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<SlsDetectorControl *>(dev))->read_temperature_sodl(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<SlsDetectorControl *>(dev))->is_temperature_sodl_allowed(ty);}
};

//	Attribute temperature_sodr class definition
class temperature_sodrAttrib: public Tango::Attr
{
public:
	temperature_sodrAttrib(const std::string &att_name):Attr(att_name.c_str(),
			Tango::DEV_LONG, Tango::READ) {};
	~temperature_sodrAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<SlsDetectorControl *>(dev))->read_temperature_sodr(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<SlsDetectorControl *>(dev))->is_temperature_sodr_allowed(ty);}
};

//	Attribute tengiga class definition
class tengigaAttrib: public Tango::Attr
{
public:
	tengigaAttrib(const std::string &att_name):Attr(att_name.c_str(),
			Tango::DEV_BOOLEAN, Tango::READ_WRITE) {};
	~tengigaAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<SlsDetectorControl *>(dev))->read_tengiga(att);}
	virtual void write(Tango::DeviceImpl *dev,Tango::WAttribute &att)
		{(static_cast<SlsDetectorControl *>(dev))->write_tengiga(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<SlsDetectorControl *>(dev))->is_tengiga_allowed(ty);}
};

//	Attribute timing_mode class definition
class timing_modeAttrib: public Tango::Attr
{
public:
	timing_modeAttrib(const std::string &att_name):Attr(att_name.c_str(),
			Tango::DEV_ENUM, Tango::READ_WRITE) {};
	~timing_modeAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<SlsDetectorControl *>(dev))->read_timing_mode(att);}
	virtual void write(Tango::DeviceImpl *dev,Tango::WAttribute &att)
		{(static_cast<SlsDetectorControl *>(dev))->write_timing_mode(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<SlsDetectorControl *>(dev))->is_timing_mode_allowed(ty);}
	virtual bool same_type(const std::type_info &in_type) {return typeid(timing_modeEnum) == in_type;}
	virtual std::string get_enum_type() {return std::string("timing_modeEnum");}
};

//	Attribute threshold_energy class definition
class threshold_energyAttrib: public Tango::SpectrumAttr
{
public:
	// Constants for threshold_energy attribute
	constexpr static long X_DATA_SIZE = 3;
	threshold_energyAttrib(const std::string &att_name):SpectrumAttr(att_name.c_str(),
			Tango::DEV_LONG, Tango::READ_WRITE, threshold_energyAttrib::X_DATA_SIZE) {};
	~threshold_energyAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<SlsDetectorControl *>(dev))->read_threshold_energy(att);}
	virtual void write(Tango::DeviceImpl *dev,Tango::WAttribute &att)
		{(static_cast<SlsDetectorControl *>(dev))->write_threshold_energy(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<SlsDetectorControl *>(dev))->is_threshold_energy_allowed(ty);}
};


//=========================================
//	Define classes for commands
//=========================================
//	Command start_acquire class definition
class start_acquireClass : public Tango::Command
{
public:
	start_acquireClass(const char   *cmd_name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out,
				   const char        *in_desc,
				   const char        *out_desc,
				   Tango::DispLevel  level)
	:Command(cmd_name,in,out,in_desc,out_desc, level)	{};

	start_acquireClass(const char   *cmd_name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out)
	:Command(cmd_name,in,out)	{};
	~start_acquireClass() {};

	virtual CORBA::Any *execute (Tango::DeviceImpl *dev, const CORBA::Any &any);
	virtual bool is_allowed (Tango::DeviceImpl *dev, const CORBA::Any &any)
	{return (static_cast<SlsDetectorControl *>(dev))->is_start_acquire_allowed(any);}
};

//	Command start_detector class definition
class start_detectorClass : public Tango::Command
{
public:
	start_detectorClass(const char   *cmd_name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out,
				   const char        *in_desc,
				   const char        *out_desc,
				   Tango::DispLevel  level)
	:Command(cmd_name,in,out,in_desc,out_desc, level)	{};

	start_detectorClass(const char   *cmd_name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out)
	:Command(cmd_name,in,out)	{};
	~start_detectorClass() {};

	virtual CORBA::Any *execute (Tango::DeviceImpl *dev, const CORBA::Any &any);
	virtual bool is_allowed (Tango::DeviceImpl *dev, const CORBA::Any &any)
	{return (static_cast<SlsDetectorControl *>(dev))->is_start_detector_allowed(any);}
};

//	Command start_receiver class definition
class start_receiverClass : public Tango::Command
{
public:
	start_receiverClass(const char   *cmd_name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out,
				   const char        *in_desc,
				   const char        *out_desc,
				   Tango::DispLevel  level)
	:Command(cmd_name,in,out,in_desc,out_desc, level)	{};

	start_receiverClass(const char   *cmd_name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out)
	:Command(cmd_name,in,out)	{};
	~start_receiverClass() {};

	virtual CORBA::Any *execute (Tango::DeviceImpl *dev, const CORBA::Any &any);
	virtual bool is_allowed (Tango::DeviceImpl *dev, const CORBA::Any &any)
	{return (static_cast<SlsDetectorControl *>(dev))->is_start_receiver_allowed(any);}
};

//	Command stop_acquire class definition
class stop_acquireClass : public Tango::Command
{
public:
	stop_acquireClass(const char   *cmd_name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out,
				   const char        *in_desc,
				   const char        *out_desc,
				   Tango::DispLevel  level)
	:Command(cmd_name,in,out,in_desc,out_desc, level)	{};

	stop_acquireClass(const char   *cmd_name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out)
	:Command(cmd_name,in,out)	{};
	~stop_acquireClass() {};

	virtual CORBA::Any *execute (Tango::DeviceImpl *dev, const CORBA::Any &any);
	virtual bool is_allowed (Tango::DeviceImpl *dev, const CORBA::Any &any)
	{return (static_cast<SlsDetectorControl *>(dev))->is_stop_acquire_allowed(any);}
};

//	Command stop_detector class definition
class stop_detectorClass : public Tango::Command
{
public:
	stop_detectorClass(const char   *cmd_name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out,
				   const char        *in_desc,
				   const char        *out_desc,
				   Tango::DispLevel  level)
	:Command(cmd_name,in,out,in_desc,out_desc, level)	{};

	stop_detectorClass(const char   *cmd_name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out)
	:Command(cmd_name,in,out)	{};
	~stop_detectorClass() {};

	virtual CORBA::Any *execute (Tango::DeviceImpl *dev, const CORBA::Any &any);
	virtual bool is_allowed (Tango::DeviceImpl *dev, const CORBA::Any &any)
	{return (static_cast<SlsDetectorControl *>(dev))->is_stop_detector_allowed(any);}
};

//	Command stop_receiver class definition
class stop_receiverClass : public Tango::Command
{
public:
	stop_receiverClass(const char   *cmd_name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out,
				   const char        *in_desc,
				   const char        *out_desc,
				   Tango::DispLevel  level)
	:Command(cmd_name,in,out,in_desc,out_desc, level)	{};

	stop_receiverClass(const char   *cmd_name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out)
	:Command(cmd_name,in,out)	{};
	~stop_receiverClass() {};

	virtual CORBA::Any *execute (Tango::DeviceImpl *dev, const CORBA::Any &any);
	virtual bool is_allowed (Tango::DeviceImpl *dev, const CORBA::Any &any)
	{return (static_cast<SlsDetectorControl *>(dev))->is_stop_receiver_allowed(any);}
};


//=========================================
//	Define classes for dynamic commands
//=========================================
//	Command load_trimbits class definition
class load_trimbitsClass : public Tango::Command
{
public:
	load_trimbitsClass(const char   *cmd_name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out,
				   const char        *in_desc,
				   const char        *out_desc,
				   Tango::DispLevel  level)
	:Command(cmd_name,in,out,in_desc,out_desc, level)	{};

	load_trimbitsClass(const char   *cmd_name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out)
	:Command(cmd_name,in,out)	{};
	~load_trimbitsClass() {};

	virtual CORBA::Any *execute (Tango::DeviceImpl *dev, const CORBA::Any &any);
	virtual bool is_allowed (Tango::DeviceImpl *dev, const CORBA::Any &any)
	{return (static_cast<SlsDetectorControl *>(dev))->is_load_trimbits_allowed(any);}
};


/**
 *	The SlsDetectorControlClass singleton definition
 */

#ifdef _TG_WINDOWS_
class __declspec(dllexport)  SlsDetectorControlClass : public Tango::DeviceClass
#else
class SlsDetectorControlClass : public Tango::DeviceClass
#endif
{
	/*----- PROTECTED REGION ID(SlsDetectorControlClass::Additional DServer data members) ENABLED START -----*/
    /* clang-format on */
    //	Add your own code
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControlClass::Additional DServer data members

	public:
		//	write class properties data members
		Tango::DbData	cl_prop;
		Tango::DbData	cl_def_prop;
		Tango::DbData	dev_def_prop;
		//	Method prototypes
		static SlsDetectorControlClass *init(const char *);
		static SlsDetectorControlClass *instance();
		~SlsDetectorControlClass();
		Tango::DbDatum	get_class_property(std::string &);
		Tango::DbDatum	get_default_device_property(std::string &);
		Tango::DbDatum	get_default_class_property(std::string &);

	protected:
		SlsDetectorControlClass(std::string &);
		static SlsDetectorControlClass *_instance;
		void command_factory();
		void attribute_factory(std::vector<Tango::Attr *> &);
		void pipe_factory();
		void write_class_property();
		void set_default_property();
		void get_class_property();
		std::string get_cvstag();
		std::string get_cvsroot();

	private:
		void device_factory(TANGO_UNUSED(const Tango::DevVarStringArray *));
		void create_static_attribute_list(std::vector<Tango::Attr *> &);
		void erase_dynamic_attributes(const Tango::DevVarStringArray *,std::vector<Tango::Attr *> &);
		std::vector<std::string>	defaultAttList;
		Tango::Attr *get_attr_object_by_name(std::vector<Tango::Attr *> &att_list, std::string attname);
};

}	//	End of namespace

#endif   //	SlsDetectorControl_H
