/*----- PROTECTED REGION ID(SlsDetectorControlStateMachine.cpp) ENABLED START
 * -----*/
/* clang-format on */
//=============================================================================
//
// file :        SlsDetectorControlStateMachine.cpp
//
// description : State machine file for the SlsDetectorControl class
//
// project :     tango-slsdetectorcontrol
//
// This file is part of Tango device class.
//
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the MIT licence.
//
//
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================

#include "SlsDetectorControl.h"

/* clang-format off */
/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::SlsDetectorControlStateMachine.cpp

//================================================================
//  States  |  Description
//================================================================
//  ON      |  
//  OFF     |  
//  MOVING  |  
//  FAULT   |  


namespace SlsDetectorControl_ns
{
//=================================================
//		Attributes Allowed Methods
//=================================================

//--------------------------------------------------------
/**
 *	Method      : SlsDetectorControl::is_acquisition_index_allowed()
 * Description:  Execution allowed for acquisition_index attribute
 */
//--------------------------------------------------------
bool SlsDetectorControl::is_acquisition_index_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for acquisition_index attribute in Write access.
	/*----- PROTECTED REGION ID(SlsDetectorControl::acquisition_indexStateAllowed_WRITE) ENABLED START -----*/
    /* clang-format on */
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::acquisition_indexStateAllowed_WRITE

	//	Not any excluded states for acquisition_index attribute in read access.
	/*----- PROTECTED REGION ID(SlsDetectorControl::acquisition_indexStateAllowed_READ) ENABLED START -----*/
    /* clang-format on */
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::acquisition_indexStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SlsDetectorControl::is_detector_type_allowed()
 * Description:  Execution allowed for detector_type attribute
 */
//--------------------------------------------------------
bool SlsDetectorControl::is_detector_type_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for detector_type attribute in read access.
	/*----- PROTECTED REGION ID(SlsDetectorControl::detector_typeStateAllowed_READ) ENABLED START -----*/
    /* clang-format on */
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::detector_typeStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SlsDetectorControl::is_dynamic_range_allowed()
 * Description:  Execution allowed for dynamic_range attribute
 */
//--------------------------------------------------------
bool SlsDetectorControl::is_dynamic_range_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for dynamic_range attribute in Write access.
	/*----- PROTECTED REGION ID(SlsDetectorControl::dynamic_rangeStateAllowed_WRITE) ENABLED START -----*/
    /* clang-format on */
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::dynamic_rangeStateAllowed_WRITE

	//	Not any excluded states for dynamic_range attribute in read access.
	/*----- PROTECTED REGION ID(SlsDetectorControl::dynamic_rangeStateAllowed_READ) ENABLED START -----*/
    /* clang-format on */
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::dynamic_rangeStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SlsDetectorControl::is_exptime_allowed()
 * Description:  Execution allowed for exptime attribute
 */
//--------------------------------------------------------
bool SlsDetectorControl::is_exptime_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for exptime attribute in Write access.
	/*----- PROTECTED REGION ID(SlsDetectorControl::exptimeStateAllowed_WRITE) ENABLED START -----*/
    /* clang-format on */
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::exptimeStateAllowed_WRITE

	//	Not any excluded states for exptime attribute in read access.
	/*----- PROTECTED REGION ID(SlsDetectorControl::exptimeStateAllowed_READ) ENABLED START -----*/
    /* clang-format on */
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::exptimeStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SlsDetectorControl::is_file_name_allowed()
 * Description:  Execution allowed for file_name attribute
 */
//--------------------------------------------------------
bool SlsDetectorControl::is_file_name_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for file_name attribute in Write access.
	/*----- PROTECTED REGION ID(SlsDetectorControl::file_nameStateAllowed_WRITE) ENABLED START -----*/
    /* clang-format on */
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::file_nameStateAllowed_WRITE

	//	Not any excluded states for file_name attribute in read access.
	/*----- PROTECTED REGION ID(SlsDetectorControl::file_nameStateAllowed_READ) ENABLED START -----*/
    /* clang-format on */
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::file_nameStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SlsDetectorControl::is_file_name_prefix_allowed()
 * Description:  Execution allowed for file_name_prefix attribute
 */
//--------------------------------------------------------
bool SlsDetectorControl::is_file_name_prefix_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for file_name_prefix attribute in Write access.
	/*----- PROTECTED REGION ID(SlsDetectorControl::file_name_prefixStateAllowed_WRITE) ENABLED START -----*/
    /* clang-format on */
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::file_name_prefixStateAllowed_WRITE

	//	Not any excluded states for file_name_prefix attribute in read access.
	/*----- PROTECTED REGION ID(SlsDetectorControl::file_name_prefixStateAllowed_READ) ENABLED START -----*/
    /* clang-format on */
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::file_name_prefixStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SlsDetectorControl::is_file_overwrite_allowed()
 * Description:  Execution allowed for file_overwrite attribute
 */
//--------------------------------------------------------
bool SlsDetectorControl::is_file_overwrite_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for file_overwrite attribute in Write access.
	/*----- PROTECTED REGION ID(SlsDetectorControl::file_overwriteStateAllowed_WRITE) ENABLED START -----*/
    /* clang-format on */
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::file_overwriteStateAllowed_WRITE

	//	Not any excluded states for file_overwrite attribute in read access.
	/*----- PROTECTED REGION ID(SlsDetectorControl::file_overwriteStateAllowed_READ) ENABLED START -----*/
    /* clang-format on */
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::file_overwriteStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SlsDetectorControl::is_file_path_allowed()
 * Description:  Execution allowed for file_path attribute
 */
//--------------------------------------------------------
bool SlsDetectorControl::is_file_path_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for file_path attribute in Write access.
	/*----- PROTECTED REGION ID(SlsDetectorControl::file_pathStateAllowed_WRITE) ENABLED START -----*/
    /* clang-format on */
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::file_pathStateAllowed_WRITE

	//	Not any excluded states for file_path attribute in read access.
	/*----- PROTECTED REGION ID(SlsDetectorControl::file_pathStateAllowed_READ) ENABLED START -----*/
    /* clang-format on */
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::file_pathStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SlsDetectorControl::is_file_write_allowed()
 * Description:  Execution allowed for file_write attribute
 */
//--------------------------------------------------------
bool SlsDetectorControl::is_file_write_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for file_write attribute in Write access.
	/*----- PROTECTED REGION ID(SlsDetectorControl::file_writeStateAllowed_WRITE) ENABLED START -----*/
    /* clang-format on */
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::file_writeStateAllowed_WRITE

	//	Not any excluded states for file_write attribute in read access.
	/*----- PROTECTED REGION ID(SlsDetectorControl::file_writeStateAllowed_READ) ENABLED START -----*/
    /* clang-format on */
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::file_writeStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SlsDetectorControl::is_firmware_version_allowed()
 * Description:  Execution allowed for firmware_version attribute
 */
//--------------------------------------------------------
bool SlsDetectorControl::is_firmware_version_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for firmware_version attribute in read access.
	/*----- PROTECTED REGION ID(SlsDetectorControl::firmware_versionStateAllowed_READ) ENABLED START -----*/
    /* clang-format on */
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::firmware_versionStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SlsDetectorControl::is_full_file_name_allowed()
 * Description:  Execution allowed for full_file_name attribute
 */
//--------------------------------------------------------
bool SlsDetectorControl::is_full_file_name_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for full_file_name attribute in read access.
	/*----- PROTECTED REGION ID(SlsDetectorControl::full_file_nameStateAllowed_READ) ENABLED START -----*/
    /* clang-format on */
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::full_file_nameStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SlsDetectorControl::is_high_voltage_allowed()
 * Description:  Execution allowed for high_voltage attribute
 */
//--------------------------------------------------------
bool SlsDetectorControl::is_high_voltage_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for high_voltage attribute in Write access.
	/*----- PROTECTED REGION ID(SlsDetectorControl::high_voltageStateAllowed_WRITE) ENABLED START -----*/
    /* clang-format on */
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::high_voltageStateAllowed_WRITE

	//	Not any excluded states for high_voltage attribute in read access.
	/*----- PROTECTED REGION ID(SlsDetectorControl::high_voltageStateAllowed_READ) ENABLED START -----*/
    /* clang-format on */
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::high_voltageStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SlsDetectorControl::is_hostname_allowed()
 * Description:  Execution allowed for hostname attribute
 */
//--------------------------------------------------------
bool SlsDetectorControl::is_hostname_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for hostname attribute in read access.
	/*----- PROTECTED REGION ID(SlsDetectorControl::hostnameStateAllowed_READ) ENABLED START -----*/
    /* clang-format on */
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::hostnameStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SlsDetectorControl::is_master_file_write_allowed()
 * Description:  Execution allowed for master_file_write attribute
 */
//--------------------------------------------------------
bool SlsDetectorControl::is_master_file_write_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for master_file_write attribute in Write access.
	/*----- PROTECTED REGION ID(SlsDetectorControl::master_file_writeStateAllowed_WRITE) ENABLED START -----*/
    /* clang-format on */
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::master_file_writeStateAllowed_WRITE

	//	Not any excluded states for master_file_write attribute in read access.
	/*----- PROTECTED REGION ID(SlsDetectorControl::master_file_writeStateAllowed_READ) ENABLED START -----*/
    /* clang-format on */
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::master_file_writeStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SlsDetectorControl::is_num_frames_allowed()
 * Description:  Execution allowed for num_frames attribute
 */
//--------------------------------------------------------
bool SlsDetectorControl::is_num_frames_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for num_frames attribute in Write access.
	/*----- PROTECTED REGION ID(SlsDetectorControl::num_framesStateAllowed_WRITE) ENABLED START -----*/
    /* clang-format on */
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::num_framesStateAllowed_WRITE

	//	Not any excluded states for num_frames attribute in read access.
	/*----- PROTECTED REGION ID(SlsDetectorControl::num_framesStateAllowed_READ) ENABLED START -----*/
    /* clang-format on */
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::num_framesStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SlsDetectorControl::is_num_frames_per_file_allowed()
 * Description:  Execution allowed for num_frames_per_file attribute
 */
//--------------------------------------------------------
bool SlsDetectorControl::is_num_frames_per_file_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for num_frames_per_file attribute in Write access.
	/*----- PROTECTED REGION ID(SlsDetectorControl::num_frames_per_fileStateAllowed_WRITE) ENABLED START -----*/
    /* clang-format on */
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::num_frames_per_fileStateAllowed_WRITE

	//	Not any excluded states for num_frames_per_file attribute in read access.
	/*----- PROTECTED REGION ID(SlsDetectorControl::num_frames_per_fileStateAllowed_READ) ENABLED START -----*/
    /* clang-format on */
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::num_frames_per_fileStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SlsDetectorControl::is_num_triggers_allowed()
 * Description:  Execution allowed for num_triggers attribute
 */
//--------------------------------------------------------
bool SlsDetectorControl::is_num_triggers_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for num_triggers attribute in Write access.
	/*----- PROTECTED REGION ID(SlsDetectorControl::num_triggersStateAllowed_WRITE) ENABLED START -----*/
    /* clang-format on */
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::num_triggersStateAllowed_WRITE

	//	Not any excluded states for num_triggers attribute in read access.
	/*----- PROTECTED REGION ID(SlsDetectorControl::num_triggersStateAllowed_READ) ENABLED START -----*/
    /* clang-format on */
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::num_triggersStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SlsDetectorControl::is_package_version_allowed()
 * Description:  Execution allowed for package_version attribute
 */
//--------------------------------------------------------
bool SlsDetectorControl::is_package_version_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for package_version attribute in read access.
	/*----- PROTECTED REGION ID(SlsDetectorControl::package_versionStateAllowed_READ) ENABLED START -----*/
    /* clang-format on */
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::package_versionStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SlsDetectorControl::is_period_allowed()
 * Description:  Execution allowed for period attribute
 */
//--------------------------------------------------------
bool SlsDetectorControl::is_period_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for period attribute in Write access.
	/*----- PROTECTED REGION ID(SlsDetectorControl::periodStateAllowed_WRITE) ENABLED START -----*/
    /* clang-format on */
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::periodStateAllowed_WRITE

	//	Not any excluded states for period attribute in read access.
	/*----- PROTECTED REGION ID(SlsDetectorControl::periodStateAllowed_READ) ENABLED START -----*/
    /* clang-format on */
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::periodStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SlsDetectorControl::is_rx_zmq_data_stream_allowed()
 * Description:  Execution allowed for rx_zmq_data_stream attribute
 */
//--------------------------------------------------------
bool SlsDetectorControl::is_rx_zmq_data_stream_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for rx_zmq_data_stream attribute in Write access.
	/*----- PROTECTED REGION ID(SlsDetectorControl::rx_zmq_data_streamStateAllowed_WRITE) ENABLED START -----*/
    /* clang-format on */
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::rx_zmq_data_streamStateAllowed_WRITE

	//	Not any excluded states for rx_zmq_data_stream attribute in read access.
	/*----- PROTECTED REGION ID(SlsDetectorControl::rx_zmq_data_streamStateAllowed_READ) ENABLED START -----*/
    /* clang-format on */
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::rx_zmq_data_streamStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SlsDetectorControl::is_temperature_fpga_allowed()
 * Description:  Execution allowed for temperature_fpga attribute
 */
//--------------------------------------------------------
bool SlsDetectorControl::is_temperature_fpga_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for temperature_fpga attribute in read access.
	/*----- PROTECTED REGION ID(SlsDetectorControl::temperature_fpgaStateAllowed_READ) ENABLED START -----*/
    /* clang-format on */
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::temperature_fpgaStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SlsDetectorControl::is_num_missing_packets_allowed()
 * Description:  Execution allowed for num_missing_packets attribute
 */
//--------------------------------------------------------
bool SlsDetectorControl::is_num_missing_packets_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for num_missing_packets attribute in read access.
	/*----- PROTECTED REGION ID(SlsDetectorControl::num_missing_packetsStateAllowed_READ) ENABLED START -----*/
    /* clang-format on */
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::num_missing_packetsStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SlsDetectorControl::is_adc_phase_allowed()
 * Description:  Execution allowed for adc_phase attribute
 */
//--------------------------------------------------------
bool SlsDetectorControl::is_adc_phase_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for adc_phase attribute in Write access.
	/*----- PROTECTED REGION ID(SlsDetectorControl::adc_phaseStateAllowed_WRITE) ENABLED START -----*/
    /* clang-format on */
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::adc_phaseStateAllowed_WRITE

	//	Not any excluded states for adc_phase attribute in read access.
	/*----- PROTECTED REGION ID(SlsDetectorControl::adc_phaseStateAllowed_READ) ENABLED START -----*/
    /* clang-format on */
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::adc_phaseStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SlsDetectorControl::is_delay_after_trigger_allowed()
 * Description:  Execution allowed for delay_after_trigger attribute
 */
//--------------------------------------------------------
bool SlsDetectorControl::is_delay_after_trigger_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for delay_after_trigger attribute in Write access.
	/*----- PROTECTED REGION ID(SlsDetectorControl::delay_after_triggerStateAllowed_WRITE) ENABLED START -----*/
    /* clang-format on */
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::delay_after_triggerStateAllowed_WRITE

	//	Not any excluded states for delay_after_trigger attribute in read access.
	/*----- PROTECTED REGION ID(SlsDetectorControl::delay_after_triggerStateAllowed_READ) ENABLED START -----*/
    /* clang-format on */
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::delay_after_triggerStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SlsDetectorControl::is_detector_setting_allowed()
 * Description:  Execution allowed for detector_setting attribute
 */
//--------------------------------------------------------
bool SlsDetectorControl::is_detector_setting_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for detector_setting attribute in Write access.
	/*----- PROTECTED REGION ID(SlsDetectorControl::detector_settingStateAllowed_WRITE) ENABLED START -----*/
    /* clang-format on */
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::detector_settingStateAllowed_WRITE

	//	Not any excluded states for detector_setting attribute in read access.
	/*----- PROTECTED REGION ID(SlsDetectorControl::detector_settingStateAllowed_READ) ENABLED START -----*/
    /* clang-format on */
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::detector_settingStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SlsDetectorControl::is_num_frames_left_allowed()
 * Description:  Execution allowed for num_frames_left attribute
 */
//--------------------------------------------------------
bool SlsDetectorControl::is_num_frames_left_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for num_frames_left attribute in read access.
	/*----- PROTECTED REGION ID(SlsDetectorControl::num_frames_leftStateAllowed_READ) ENABLED START -----*/
    /* clang-format on */
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::num_frames_leftStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SlsDetectorControl::is_num_triggers_left_allowed()
 * Description:  Execution allowed for num_triggers_left attribute
 */
//--------------------------------------------------------
bool SlsDetectorControl::is_num_triggers_left_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for num_triggers_left attribute in read access.
	/*----- PROTECTED REGION ID(SlsDetectorControl::num_triggers_leftStateAllowed_READ) ENABLED START -----*/
    /* clang-format on */
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::num_triggers_leftStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SlsDetectorControl::is_power_chip_allowed()
 * Description:  Execution allowed for power_chip attribute
 */
//--------------------------------------------------------
bool SlsDetectorControl::is_power_chip_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for power_chip attribute in Write access.
	/*----- PROTECTED REGION ID(SlsDetectorControl::power_chipStateAllowed_WRITE) ENABLED START -----*/
    /* clang-format on */
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::power_chipStateAllowed_WRITE

	//	Not any excluded states for power_chip attribute in read access.
	/*----- PROTECTED REGION ID(SlsDetectorControl::power_chipStateAllowed_READ) ENABLED START -----*/
    /* clang-format on */
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::power_chipStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SlsDetectorControl::is_readout_speed_allowed()
 * Description:  Execution allowed for readout_speed attribute
 */
//--------------------------------------------------------
bool SlsDetectorControl::is_readout_speed_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for readout_speed attribute in Write access.
	/*----- PROTECTED REGION ID(SlsDetectorControl::readout_speedStateAllowed_WRITE) ENABLED START -----*/
    /* clang-format on */
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::readout_speedStateAllowed_WRITE

	//	Not any excluded states for readout_speed attribute in read access.
	/*----- PROTECTED REGION ID(SlsDetectorControl::readout_speedStateAllowed_READ) ENABLED START -----*/
    /* clang-format on */
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::readout_speedStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SlsDetectorControl::is_temperature_10ge_allowed()
 * Description:  Execution allowed for temperature_10ge attribute
 */
//--------------------------------------------------------
bool SlsDetectorControl::is_temperature_10ge_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for temperature_10ge attribute in read access.
	/*----- PROTECTED REGION ID(SlsDetectorControl::temperature_10geStateAllowed_READ) ENABLED START -----*/
    /* clang-format on */
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::temperature_10geStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SlsDetectorControl::is_temperature_adc_allowed()
 * Description:  Execution allowed for temperature_adc attribute
 */
//--------------------------------------------------------
bool SlsDetectorControl::is_temperature_adc_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for temperature_adc attribute in read access.
	/*----- PROTECTED REGION ID(SlsDetectorControl::temperature_adcStateAllowed_READ) ENABLED START -----*/
    /* clang-format on */
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::temperature_adcStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SlsDetectorControl::is_temperature_dcdc_allowed()
 * Description:  Execution allowed for temperature_dcdc attribute
 */
//--------------------------------------------------------
bool SlsDetectorControl::is_temperature_dcdc_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for temperature_dcdc attribute in read access.
	/*----- PROTECTED REGION ID(SlsDetectorControl::temperature_dcdcStateAllowed_READ) ENABLED START -----*/
    /* clang-format on */
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::temperature_dcdcStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SlsDetectorControl::is_temperature_fpga2_allowed()
 * Description:  Execution allowed for temperature_fpga2 attribute
 */
//--------------------------------------------------------
bool SlsDetectorControl::is_temperature_fpga2_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for temperature_fpga2 attribute in read access.
	/*----- PROTECTED REGION ID(SlsDetectorControl::temperature_fpga2StateAllowed_READ) ENABLED START -----*/
    /* clang-format on */
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::temperature_fpga2StateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SlsDetectorControl::is_temperature_fpga3_allowed()
 * Description:  Execution allowed for temperature_fpga3 attribute
 */
//--------------------------------------------------------
bool SlsDetectorControl::is_temperature_fpga3_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for temperature_fpga3 attribute in read access.
	/*----- PROTECTED REGION ID(SlsDetectorControl::temperature_fpga3StateAllowed_READ) ENABLED START -----*/
    /* clang-format on */
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::temperature_fpga3StateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SlsDetectorControl::is_temperature_fpgaext_allowed()
 * Description:  Execution allowed for temperature_fpgaext attribute
 */
//--------------------------------------------------------
bool SlsDetectorControl::is_temperature_fpgaext_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for temperature_fpgaext attribute in read access.
	/*----- PROTECTED REGION ID(SlsDetectorControl::temperature_fpgaextStateAllowed_READ) ENABLED START -----*/
    /* clang-format on */
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::temperature_fpgaextStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SlsDetectorControl::is_temperature_sodl_allowed()
 * Description:  Execution allowed for temperature_sodl attribute
 */
//--------------------------------------------------------
bool SlsDetectorControl::is_temperature_sodl_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for temperature_sodl attribute in read access.
	/*----- PROTECTED REGION ID(SlsDetectorControl::temperature_sodlStateAllowed_READ) ENABLED START -----*/
    /* clang-format on */
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::temperature_sodlStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SlsDetectorControl::is_temperature_sodr_allowed()
 * Description:  Execution allowed for temperature_sodr attribute
 */
//--------------------------------------------------------
bool SlsDetectorControl::is_temperature_sodr_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for temperature_sodr attribute in read access.
	/*----- PROTECTED REGION ID(SlsDetectorControl::temperature_sodrStateAllowed_READ) ENABLED START -----*/
    /* clang-format on */
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::temperature_sodrStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SlsDetectorControl::is_tengiga_allowed()
 * Description:  Execution allowed for tengiga attribute
 */
//--------------------------------------------------------
bool SlsDetectorControl::is_tengiga_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for tengiga attribute in Write access.
	/*----- PROTECTED REGION ID(SlsDetectorControl::tengigaStateAllowed_WRITE) ENABLED START -----*/
    /* clang-format on */
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::tengigaStateAllowed_WRITE

	//	Not any excluded states for tengiga attribute in read access.
	/*----- PROTECTED REGION ID(SlsDetectorControl::tengigaStateAllowed_READ) ENABLED START -----*/
    /* clang-format on */
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::tengigaStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SlsDetectorControl::is_timing_mode_allowed()
 * Description:  Execution allowed for timing_mode attribute
 */
//--------------------------------------------------------
bool SlsDetectorControl::is_timing_mode_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for timing_mode attribute in Write access.
	/*----- PROTECTED REGION ID(SlsDetectorControl::timing_modeStateAllowed_WRITE) ENABLED START -----*/
    /* clang-format on */
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::timing_modeStateAllowed_WRITE

	//	Not any excluded states for timing_mode attribute in read access.
	/*----- PROTECTED REGION ID(SlsDetectorControl::timing_modeStateAllowed_READ) ENABLED START -----*/
    /* clang-format on */
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::timing_modeStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SlsDetectorControl::is_threshold_energy_allowed()
 * Description:  Execution allowed for threshold_energy attribute
 */
//--------------------------------------------------------
bool SlsDetectorControl::is_threshold_energy_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for threshold_energy attribute in Write access.
	/*----- PROTECTED REGION ID(SlsDetectorControl::threshold_energyStateAllowed_WRITE) ENABLED START -----*/
    /* clang-format on */
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::threshold_energyStateAllowed_WRITE

	//	Not any excluded states for threshold_energy attribute in read access.
	/*----- PROTECTED REGION ID(SlsDetectorControl::threshold_energyStateAllowed_READ) ENABLED START -----*/
    /* clang-format on */
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::threshold_energyStateAllowed_READ
	return true;
}


//=================================================
//		Commands Allowed Methods
//=================================================

//--------------------------------------------------------
/**
 *	Method      : SlsDetectorControl::is_start_acquire_allowed()
 * Description:  Execution allowed for start_acquire attribute
 */
//--------------------------------------------------------
bool SlsDetectorControl::is_start_acquire_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for start_acquire command.
	/*----- PROTECTED REGION ID(SlsDetectorControl::start_acquireStateAllowed) ENABLED START -----*/
    /* clang-format on */
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::start_acquireStateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SlsDetectorControl::is_stop_acquire_allowed()
 * Description:  Execution allowed for stop_acquire attribute
 */
//--------------------------------------------------------
bool SlsDetectorControl::is_stop_acquire_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for stop_acquire command.
	/*----- PROTECTED REGION ID(SlsDetectorControl::stop_acquireStateAllowed) ENABLED START -----*/
    /* clang-format on */
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::stop_acquireStateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SlsDetectorControl::is_start_receiver_allowed()
 * Description:  Execution allowed for start_receiver attribute
 */
//--------------------------------------------------------
bool SlsDetectorControl::is_start_receiver_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for start_receiver command.
	/*----- PROTECTED REGION ID(SlsDetectorControl::start_receiverStateAllowed) ENABLED START -----*/
    /* clang-format on */
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::start_receiverStateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SlsDetectorControl::is_stop_receiver_allowed()
 * Description:  Execution allowed for stop_receiver attribute
 */
//--------------------------------------------------------
bool SlsDetectorControl::is_stop_receiver_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for stop_receiver command.
	/*----- PROTECTED REGION ID(SlsDetectorControl::stop_receiverStateAllowed) ENABLED START -----*/
    /* clang-format on */
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::stop_receiverStateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SlsDetectorControl::is_start_detector_allowed()
 * Description:  Execution allowed for start_detector attribute
 */
//--------------------------------------------------------
bool SlsDetectorControl::is_start_detector_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for start_detector command.
	/*----- PROTECTED REGION ID(SlsDetectorControl::start_detectorStateAllowed) ENABLED START -----*/
    /* clang-format on */
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::start_detectorStateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SlsDetectorControl::is_stop_detector_allowed()
 * Description:  Execution allowed for stop_detector attribute
 */
//--------------------------------------------------------
bool SlsDetectorControl::is_stop_detector_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for stop_detector command.
	/*----- PROTECTED REGION ID(SlsDetectorControl::stop_detectorStateAllowed) ENABLED START -----*/
    /* clang-format on */
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::stop_detectorStateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SlsDetectorControl::is_load_trimbits_allowed()
 * Description:  Execution allowed for load_trimbits attribute
 */
//--------------------------------------------------------
bool SlsDetectorControl::is_load_trimbits_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for load_trimbits command.
	/*----- PROTECTED REGION ID(SlsDetectorControl::load_trimbitsStateAllowed) ENABLED START -----*/
    /* clang-format on */
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::load_trimbitsStateAllowed
	return true;
}


/*----- PROTECTED REGION ID(SlsDetectorControl::SlsDetectorControlStateAllowed.AdditionalMethods) ENABLED START -----*/
/* clang-format on */
//	Additional Methods
/* clang-format off */
/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::SlsDetectorControlStateAllowed.AdditionalMethods

}	//	End of namespace
