/*----- PROTECTED REGION ID(SlsDetectorControl::DynAttrUtils.cpp) ENABLED START
 * -----*/
/* clang-format on */
//=============================================================================
//
// file :        SlsDetectorControlDynAttrUtils.cpp
//
// description : Dynamic attributes utilities file for the SlsDetectorControl
// class
//
// project :     tango-slsdetectorcontrol
//
// This file is part of Tango device class.
//
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the MIT licence.
//
//
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================

#include "SlsDetectorControl.h"
#include "SlsDetectorControlClass.h"

/* clang-format off */
/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::DynAttrUtils.cpp

//================================================================
//  Attributes managed are:
//================================================================
//  adc_phase            |  Tango::DevLong	Scalar
//  delay_after_trigger  |  Tango::DevDouble	Scalar
//  detector_setting     |  Tango::DevEnum	Scalar
//  detector_status      |  Tango::DevEnum	Scalar
//  file_format          |  Tango::DevEnum	Scalar
//  num_frames_left      |  Tango::DevLong64	Scalar
//  num_triggers_left    |  Tango::DevLong	Scalar
//  power_chip           |  Tango::DevBoolean	Scalar
//  readout_speed        |  Tango::DevEnum	Scalar
//  receiver_status      |  Tango::DevEnum	Scalar
//  temperature_10ge     |  Tango::DevLong	Scalar
//  temperature_adc      |  Tango::DevLong	Scalar
//  temperature_dcdc     |  Tango::DevLong	Scalar
//  temperature_fpga2    |  Tango::DevLong	Scalar
//  temperature_fpga3    |  Tango::DevLong	Scalar
//  temperature_fpgaext  |  Tango::DevLong	Scalar
//  temperature_sodl     |  Tango::DevLong	Scalar
//  temperature_sodr     |  Tango::DevLong	Scalar
//  tengiga              |  Tango::DevBoolean	Scalar
//  timing_mode          |  Tango::DevEnum	Scalar
//  threshold_energy     |  Tango::DevLong	Spectrum  ( max = 3)
//================================================================

//	For compatibility reason, this file (SlsDetectorControlDynAttrUtils)
//	manage also the dynamic command utilities.
//================================================================
//  The following table gives the correspondence
//  between command and method names.
//
//  Command name   |  Method name
//================================================================
//  load_trimbits  |  load_trimbits
//================================================================

namespace SlsDetectorControl_ns
{
//=============================================================
//	Add/Remove dynamic attribute methods
//=============================================================

//--------------------------------------------------------
/**
 *	Add a adc_phase dynamic attribute.
 *
 *  parameter attname: attribute name to be created and added.
 */
//--------------------------------------------------------
void SlsDetectorControl::add_adc_phase_dynamic_attribute(std::string attname)
{
	//	Attribute : adc_phase
	adc_phaseAttrib	*adc_phase = new adc_phaseAttrib(attname);
	Tango::UserDefaultAttrProp	adc_phase_prop;
	//	description	not set for adc_phase
	//	label	not set for adc_phase
	adc_phase_prop.set_unit("°");
	//	standard_unit	not set for adc_phase
	//	display_unit	not set for adc_phase
	//	format	not set for adc_phase
	//	max_value	not set for adc_phase
	//	min_value	not set for adc_phase
	//	max_alarm	not set for adc_phase
	//	min_alarm	not set for adc_phase
	//	max_warning	not set for adc_phase
	//	min_warning	not set for adc_phase
	//	delta_t	not set for adc_phase
	//	delta_val	not set for adc_phase
	/*----- PROTECTED REGION ID(SlsDetectorControl::att_adc_phase_dynamic_attribute) ENABLED START -----*/
    /* clang-format on */
    //	Add your own code
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::att_adc_phase_dynamic_attribute
	adc_phase->set_default_properties(adc_phase_prop);
	//	Not Polled
	adc_phase->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	adc_phase_data.insert(make_pair(attname, 0));
	add_attribute(adc_phase);
}
//--------------------------------------------------------
/**
 *	remove a adc_phase dynamic attribute.
 *
 *  parameter attname: attribute name to be removed.
 */
//--------------------------------------------------------
void SlsDetectorControl::remove_adc_phase_dynamic_attribute(std::string attname)
{
	remove_attribute(attname, true, Tango::Util::instance()->_UseDb);
	map<std::string,Tango::DevLong>::iterator ite;
	if ((ite=adc_phase_data.find(attname))!=adc_phase_data.end())
	{
		/*----- PROTECTED REGION ID(SlsDetectorControl::remove_adc_phase_dynamic_attribute) ENABLED START -----*/
        /* clang-format on */
        //	Add your own code
        /* clang-format off */
		/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::remove_adc_phase_dynamic_attribute
		adc_phase_data.erase(ite);
	}
}
//--------------------------------------------------------
/**
 *	Add a delay_after_trigger dynamic attribute.
 *
 *  parameter attname: attribute name to be created and added.
 */
//--------------------------------------------------------
void SlsDetectorControl::add_delay_after_trigger_dynamic_attribute(std::string attname)
{
	//	Attribute : delay_after_trigger
	delay_after_triggerAttrib	*delay_after_trigger = new delay_after_triggerAttrib(attname);
	Tango::UserDefaultAttrProp	delay_after_trigger_prop;
	//	description	not set for delay_after_trigger
	//	label	not set for delay_after_trigger
	delay_after_trigger_prop.set_unit("s");
	//	standard_unit	not set for delay_after_trigger
	//	display_unit	not set for delay_after_trigger
	delay_after_trigger_prop.set_format("%5.3e");
	//	max_value	not set for delay_after_trigger
	delay_after_trigger_prop.set_min_value("0");
	//	max_alarm	not set for delay_after_trigger
	//	min_alarm	not set for delay_after_trigger
	//	max_warning	not set for delay_after_trigger
	//	min_warning	not set for delay_after_trigger
	//	delta_t	not set for delay_after_trigger
	//	delta_val	not set for delay_after_trigger
	/*----- PROTECTED REGION ID(SlsDetectorControl::att_delay_after_trigger_dynamic_attribute) ENABLED START -----*/
    /* clang-format on */
    //	Add your own code
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::att_delay_after_trigger_dynamic_attribute
	delay_after_trigger->set_default_properties(delay_after_trigger_prop);
	//	Not Polled
	delay_after_trigger->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	delay_after_trigger_data.insert(make_pair(attname, 0.0));
	add_attribute(delay_after_trigger);
}
//--------------------------------------------------------
/**
 *	remove a delay_after_trigger dynamic attribute.
 *
 *  parameter attname: attribute name to be removed.
 */
//--------------------------------------------------------
void SlsDetectorControl::remove_delay_after_trigger_dynamic_attribute(std::string attname)
{
	remove_attribute(attname, true, Tango::Util::instance()->_UseDb);
	map<std::string,Tango::DevDouble>::iterator ite;
	if ((ite=delay_after_trigger_data.find(attname))!=delay_after_trigger_data.end())
	{
		/*----- PROTECTED REGION ID(SlsDetectorControl::remove_delay_after_trigger_dynamic_attribute) ENABLED START -----*/
        /* clang-format on */
        //	Add your own code
        /* clang-format off */
		/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::remove_delay_after_trigger_dynamic_attribute
		delay_after_trigger_data.erase(ite);
	}
}
//--------------------------------------------------------
/**
 *	Add a detector_setting dynamic attribute.
 *
 *  parameter attname: attribute name to be created and added.
 */
//--------------------------------------------------------
void SlsDetectorControl::add_detector_setting_dynamic_attribute(std::string attname)
{
	//	Attribute : detector_setting
	detector_settingAttrib	*detector_setting = new detector_settingAttrib(attname);
	Tango::UserDefaultAttrProp	detector_setting_prop;
	//	description	not set for detector_setting
	//	label	not set for detector_setting
	//	unit	not set for detector_setting
	//	standard_unit	not set for detector_setting
	//	display_unit	not set for detector_setting
	//	format	not set for detector_setting
	//	max_value	not set for detector_setting
	//	min_value	not set for detector_setting
	//	max_alarm	not set for detector_setting
	//	min_alarm	not set for detector_setting
	//	max_warning	not set for detector_setting
	//	min_warning	not set for detector_setting
	//	delta_t	not set for detector_setting
	//	delta_val	not set for detector_setting
	/*----- PROTECTED REGION ID(SlsDetectorControl::att_detector_setting_dynamic_attribute) ENABLED START -----*/
    /* clang-format on */
    //	Add your own code
    // detector_setting_prop.set_enum_labels(settingsListLabels);
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::att_detector_setting_dynamic_attribute
	detector_setting->set_default_properties(detector_setting_prop);
	//	Not Polled
	detector_setting->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	detector_setting_data.insert(make_pair(attname, 0));
	add_attribute(detector_setting);
}
//--------------------------------------------------------
/**
 *	remove a detector_setting dynamic attribute.
 *
 *  parameter attname: attribute name to be removed.
 */
//--------------------------------------------------------
void SlsDetectorControl::remove_detector_setting_dynamic_attribute(std::string attname)
{
	remove_attribute(attname, true, Tango::Util::instance()->_UseDb);
	map<std::string,Tango::DevEnum>::iterator ite;
	if ((ite=detector_setting_data.find(attname))!=detector_setting_data.end())
	{
		/*----- PROTECTED REGION ID(SlsDetectorControl::remove_detector_setting_dynamic_attribute) ENABLED START -----*/
        /* clang-format on */
        //	Add your own code
        /* clang-format off */
		/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::remove_detector_setting_dynamic_attribute
		detector_setting_data.erase(ite);
	}
}
//--------------------------------------------------------
/**
 *	Add a detector_status dynamic attribute.
 *
 *  parameter attname: attribute name to be created and added.
 */
//--------------------------------------------------------
void SlsDetectorControl::add_detector_status_dynamic_attribute(std::string attname)
{
	//	Attribute : detector_status
	detector_statusAttrib	*detector_status = new detector_statusAttrib(attname);
	Tango::UserDefaultAttrProp	detector_status_prop;
	//	description	not set for detector_status
	//	label	not set for detector_status
	//	unit	not set for detector_status
	//	standard_unit	not set for detector_status
	//	display_unit	not set for detector_status
	//	format	not set for detector_status
	//	max_value	not set for detector_status
	//	min_value	not set for detector_status
	//	max_alarm	not set for detector_status
	//	min_alarm	not set for detector_status
	//	max_warning	not set for detector_status
	//	min_warning	not set for detector_status
	//	delta_t	not set for detector_status
	//	delta_val	not set for detector_status
	/*----- PROTECTED REGION ID(SlsDetectorControl::att_detector_status_dynamic_attribute) ENABLED START -----*/
    /* clang-format on */
    //	Add your own code
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::att_detector_status_dynamic_attribute
	detector_status->set_default_properties(detector_status_prop);
	//	Not Polled
	detector_status->set_disp_level(Tango::EXPERT);
	//	Not Memorized
	detector_status_data.insert(make_pair(attname, 0));
	add_attribute(detector_status);
}
//--------------------------------------------------------
/**
 *	remove a detector_status dynamic attribute.
 *
 *  parameter attname: attribute name to be removed.
 */
//--------------------------------------------------------
void SlsDetectorControl::remove_detector_status_dynamic_attribute(std::string attname)
{
	remove_attribute(attname, true, Tango::Util::instance()->_UseDb);
	map<std::string,Tango::DevEnum>::iterator ite;
	if ((ite=detector_status_data.find(attname))!=detector_status_data.end())
	{
		/*----- PROTECTED REGION ID(SlsDetectorControl::remove_detector_status_dynamic_attribute) ENABLED START -----*/
        /* clang-format on */
        //	Add your own code
        /* clang-format off */
		/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::remove_detector_status_dynamic_attribute
		detector_status_data.erase(ite);
	}
}
//--------------------------------------------------------
/**
 *	Add a file_format dynamic attribute.
 *
 *  parameter attname: attribute name to be created and added.
 */
//--------------------------------------------------------
void SlsDetectorControl::add_file_format_dynamic_attribute(std::string attname)
{
	//	Attribute : file_format
	file_formatAttrib	*file_format = new file_formatAttrib(attname);
	Tango::UserDefaultAttrProp	file_format_prop;
	//	description	not set for file_format
	//	label	not set for file_format
	//	unit	not set for file_format
	//	standard_unit	not set for file_format
	//	display_unit	not set for file_format
	//	format	not set for file_format
	//	max_value	not set for file_format
	//	min_value	not set for file_format
	//	max_alarm	not set for file_format
	//	min_alarm	not set for file_format
	//	max_warning	not set for file_format
	//	min_warning	not set for file_format
	//	delta_t	not set for file_format
	//	delta_val	not set for file_format
	/*----- PROTECTED REGION ID(SlsDetectorControl::att_file_format_dynamic_attribute) ENABLED START -----*/
    /* clang-format on */
    //	Add your own code
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::att_file_format_dynamic_attribute
	file_format->set_default_properties(file_format_prop);
	//	Not Polled
	file_format->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	file_format_data.insert(make_pair(attname, 0));
	add_attribute(file_format);
}
//--------------------------------------------------------
/**
 *	remove a file_format dynamic attribute.
 *
 *  parameter attname: attribute name to be removed.
 */
//--------------------------------------------------------
void SlsDetectorControl::remove_file_format_dynamic_attribute(std::string attname)
{
	remove_attribute(attname, true, Tango::Util::instance()->_UseDb);
	map<std::string,Tango::DevEnum>::iterator ite;
	if ((ite=file_format_data.find(attname))!=file_format_data.end())
	{
		/*----- PROTECTED REGION ID(SlsDetectorControl::remove_file_format_dynamic_attribute) ENABLED START -----*/
        /* clang-format on */
        //	Add your own code
        /* clang-format off */
		/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::remove_file_format_dynamic_attribute
		file_format_data.erase(ite);
	}
}
//--------------------------------------------------------
/**
 *	Add a num_frames_left dynamic attribute.
 *
 *  parameter attname: attribute name to be created and added.
 */
//--------------------------------------------------------
void SlsDetectorControl::add_num_frames_left_dynamic_attribute(std::string attname)
{
	//	Attribute : num_frames_left
	num_frames_leftAttrib	*num_frames_left = new num_frames_leftAttrib(attname);
	Tango::UserDefaultAttrProp	num_frames_left_prop;
	//	description	not set for num_frames_left
	//	label	not set for num_frames_left
	//	unit	not set for num_frames_left
	//	standard_unit	not set for num_frames_left
	//	display_unit	not set for num_frames_left
	//	format	not set for num_frames_left
	//	max_value	not set for num_frames_left
	//	min_value	not set for num_frames_left
	//	max_alarm	not set for num_frames_left
	//	min_alarm	not set for num_frames_left
	//	max_warning	not set for num_frames_left
	//	min_warning	not set for num_frames_left
	//	delta_t	not set for num_frames_left
	//	delta_val	not set for num_frames_left
	/*----- PROTECTED REGION ID(SlsDetectorControl::att_num_frames_left_dynamic_attribute) ENABLED START -----*/
    /* clang-format on */
    //	Add your own code
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::att_num_frames_left_dynamic_attribute
	num_frames_left->set_default_properties(num_frames_left_prop);
	//	Not Polled
	num_frames_left->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	num_frames_left_data.insert(make_pair(attname, 0));
	add_attribute(num_frames_left);
}
//--------------------------------------------------------
/**
 *	remove a num_frames_left dynamic attribute.
 *
 *  parameter attname: attribute name to be removed.
 */
//--------------------------------------------------------
void SlsDetectorControl::remove_num_frames_left_dynamic_attribute(std::string attname)
{
	remove_attribute(attname, true, Tango::Util::instance()->_UseDb);
	map<std::string,Tango::DevLong64>::iterator ite;
	if ((ite=num_frames_left_data.find(attname))!=num_frames_left_data.end())
	{
		/*----- PROTECTED REGION ID(SlsDetectorControl::remove_num_frames_left_dynamic_attribute) ENABLED START -----*/
        /* clang-format on */
        //	Add your own code
        /* clang-format off */
		/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::remove_num_frames_left_dynamic_attribute
		num_frames_left_data.erase(ite);
	}
}
//--------------------------------------------------------
/**
 *	Add a num_triggers_left dynamic attribute.
 *
 *  parameter attname: attribute name to be created and added.
 */
//--------------------------------------------------------
void SlsDetectorControl::add_num_triggers_left_dynamic_attribute(std::string attname)
{
	//	Attribute : num_triggers_left
	num_triggers_leftAttrib	*num_triggers_left = new num_triggers_leftAttrib(attname);
	Tango::UserDefaultAttrProp	num_triggers_left_prop;
	//	description	not set for num_triggers_left
	//	label	not set for num_triggers_left
	//	unit	not set for num_triggers_left
	//	standard_unit	not set for num_triggers_left
	//	display_unit	not set for num_triggers_left
	//	format	not set for num_triggers_left
	//	max_value	not set for num_triggers_left
	//	min_value	not set for num_triggers_left
	//	max_alarm	not set for num_triggers_left
	//	min_alarm	not set for num_triggers_left
	//	max_warning	not set for num_triggers_left
	//	min_warning	not set for num_triggers_left
	//	delta_t	not set for num_triggers_left
	//	delta_val	not set for num_triggers_left
	/*----- PROTECTED REGION ID(SlsDetectorControl::att_num_triggers_left_dynamic_attribute) ENABLED START -----*/
    /* clang-format on */
    //	Add your own code
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::att_num_triggers_left_dynamic_attribute
	num_triggers_left->set_default_properties(num_triggers_left_prop);
	//	Not Polled
	num_triggers_left->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	num_triggers_left_data.insert(make_pair(attname, 0));
	add_attribute(num_triggers_left);
}
//--------------------------------------------------------
/**
 *	remove a num_triggers_left dynamic attribute.
 *
 *  parameter attname: attribute name to be removed.
 */
//--------------------------------------------------------
void SlsDetectorControl::remove_num_triggers_left_dynamic_attribute(std::string attname)
{
	remove_attribute(attname, true, Tango::Util::instance()->_UseDb);
	map<std::string,Tango::DevLong>::iterator ite;
	if ((ite=num_triggers_left_data.find(attname))!=num_triggers_left_data.end())
	{
		/*----- PROTECTED REGION ID(SlsDetectorControl::remove_num_triggers_left_dynamic_attribute) ENABLED START -----*/
        /* clang-format on */
        //	Add your own code
        /* clang-format off */
		/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::remove_num_triggers_left_dynamic_attribute
		num_triggers_left_data.erase(ite);
	}
}
//--------------------------------------------------------
/**
 *	Add a power_chip dynamic attribute.
 *
 *  parameter attname: attribute name to be created and added.
 */
//--------------------------------------------------------
void SlsDetectorControl::add_power_chip_dynamic_attribute(std::string attname)
{
	//	Attribute : power_chip
	power_chipAttrib	*power_chip = new power_chipAttrib(attname);
	Tango::UserDefaultAttrProp	power_chip_prop;
	//	description	not set for power_chip
	//	label	not set for power_chip
	//	unit	not set for power_chip
	//	standard_unit	not set for power_chip
	//	display_unit	not set for power_chip
	//	format	not set for power_chip
	//	max_value	not set for power_chip
	//	min_value	not set for power_chip
	//	max_alarm	not set for power_chip
	//	min_alarm	not set for power_chip
	//	max_warning	not set for power_chip
	//	min_warning	not set for power_chip
	//	delta_t	not set for power_chip
	//	delta_val	not set for power_chip
	/*----- PROTECTED REGION ID(SlsDetectorControl::att_power_chip_dynamic_attribute) ENABLED START -----*/
    /* clang-format on */
    //	Add your own code
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::att_power_chip_dynamic_attribute
	power_chip->set_default_properties(power_chip_prop);
	//	Not Polled
	power_chip->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	power_chip_data.insert(make_pair(attname, false));
	add_attribute(power_chip);
}
//--------------------------------------------------------
/**
 *	remove a power_chip dynamic attribute.
 *
 *  parameter attname: attribute name to be removed.
 */
//--------------------------------------------------------
void SlsDetectorControl::remove_power_chip_dynamic_attribute(std::string attname)
{
	remove_attribute(attname, true, Tango::Util::instance()->_UseDb);
	map<std::string,Tango::DevBoolean>::iterator ite;
	if ((ite=power_chip_data.find(attname))!=power_chip_data.end())
	{
		/*----- PROTECTED REGION ID(SlsDetectorControl::remove_power_chip_dynamic_attribute) ENABLED START -----*/
        /* clang-format on */
        //	Add your own code
        /* clang-format off */
		/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::remove_power_chip_dynamic_attribute
		power_chip_data.erase(ite);
	}
}
//--------------------------------------------------------
/**
 *	Add a readout_speed dynamic attribute.
 *
 *  parameter attname: attribute name to be created and added.
 */
//--------------------------------------------------------
void SlsDetectorControl::add_readout_speed_dynamic_attribute(std::string attname)
{
	//	Attribute : readout_speed
	readout_speedAttrib	*readout_speed = new readout_speedAttrib(attname);
	Tango::UserDefaultAttrProp	readout_speed_prop;
	//	description	not set for readout_speed
	//	label	not set for readout_speed
	//	unit	not set for readout_speed
	//	standard_unit	not set for readout_speed
	//	display_unit	not set for readout_speed
	//	format	not set for readout_speed
	//	max_value	not set for readout_speed
	//	min_value	not set for readout_speed
	//	max_alarm	not set for readout_speed
	//	min_alarm	not set for readout_speed
	//	max_warning	not set for readout_speed
	//	min_warning	not set for readout_speed
	//	delta_t	not set for readout_speed
	//	delta_val	not set for readout_speed
	/*----- PROTECTED REGION ID(SlsDetectorControl::att_readout_speed_dynamic_attribute) ENABLED START -----*/
    /* clang-format on */
    //	Add your own code
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::att_readout_speed_dynamic_attribute
	readout_speed->set_default_properties(readout_speed_prop);
	//	Not Polled
	readout_speed->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	readout_speed_data.insert(make_pair(attname, 0));
	add_attribute(readout_speed);
}
//--------------------------------------------------------
/**
 *	remove a readout_speed dynamic attribute.
 *
 *  parameter attname: attribute name to be removed.
 */
//--------------------------------------------------------
void SlsDetectorControl::remove_readout_speed_dynamic_attribute(std::string attname)
{
	remove_attribute(attname, true, Tango::Util::instance()->_UseDb);
	map<std::string,Tango::DevEnum>::iterator ite;
	if ((ite=readout_speed_data.find(attname))!=readout_speed_data.end())
	{
		/*----- PROTECTED REGION ID(SlsDetectorControl::remove_readout_speed_dynamic_attribute) ENABLED START -----*/
        /* clang-format on */
        //	Add your own code
        /* clang-format off */
		/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::remove_readout_speed_dynamic_attribute
		readout_speed_data.erase(ite);
	}
}
//--------------------------------------------------------
/**
 *	Add a receiver_status dynamic attribute.
 *
 *  parameter attname: attribute name to be created and added.
 */
//--------------------------------------------------------
void SlsDetectorControl::add_receiver_status_dynamic_attribute(std::string attname)
{
	//	Attribute : receiver_status
	receiver_statusAttrib	*receiver_status = new receiver_statusAttrib(attname);
	Tango::UserDefaultAttrProp	receiver_status_prop;
	//	description	not set for receiver_status
	//	label	not set for receiver_status
	//	unit	not set for receiver_status
	//	standard_unit	not set for receiver_status
	//	display_unit	not set for receiver_status
	//	format	not set for receiver_status
	//	max_value	not set for receiver_status
	//	min_value	not set for receiver_status
	//	max_alarm	not set for receiver_status
	//	min_alarm	not set for receiver_status
	//	max_warning	not set for receiver_status
	//	min_warning	not set for receiver_status
	//	delta_t	not set for receiver_status
	//	delta_val	not set for receiver_status
	/*----- PROTECTED REGION ID(SlsDetectorControl::att_receiver_status_dynamic_attribute) ENABLED START -----*/
    /* clang-format on */
    //	Add your own code
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::att_receiver_status_dynamic_attribute
	receiver_status->set_default_properties(receiver_status_prop);
	//	Not Polled
	receiver_status->set_disp_level(Tango::EXPERT);
	//	Not Memorized
	receiver_status_data.insert(make_pair(attname, 0));
	add_attribute(receiver_status);
}
//--------------------------------------------------------
/**
 *	remove a receiver_status dynamic attribute.
 *
 *  parameter attname: attribute name to be removed.
 */
//--------------------------------------------------------
void SlsDetectorControl::remove_receiver_status_dynamic_attribute(std::string attname)
{
	remove_attribute(attname, true, Tango::Util::instance()->_UseDb);
	map<std::string,Tango::DevEnum>::iterator ite;
	if ((ite=receiver_status_data.find(attname))!=receiver_status_data.end())
	{
		/*----- PROTECTED REGION ID(SlsDetectorControl::remove_receiver_status_dynamic_attribute) ENABLED START -----*/
        /* clang-format on */
        //	Add your own code
        /* clang-format off */
		/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::remove_receiver_status_dynamic_attribute
		receiver_status_data.erase(ite);
	}
}
//--------------------------------------------------------
/**
 *	Add a temperature_10ge dynamic attribute.
 *
 *  parameter attname: attribute name to be created and added.
 */
//--------------------------------------------------------
void SlsDetectorControl::add_temperature_10ge_dynamic_attribute(std::string attname)
{
	//	Attribute : temperature_10ge
	temperature_10geAttrib	*temperature_10ge = new temperature_10geAttrib(attname);
	Tango::UserDefaultAttrProp	temperature_10ge_prop;
	//	description	not set for temperature_10ge
	//	label	not set for temperature_10ge
	temperature_10ge_prop.set_unit("°C");
	//	standard_unit	not set for temperature_10ge
	//	display_unit	not set for temperature_10ge
	//	format	not set for temperature_10ge
	//	max_value	not set for temperature_10ge
	//	min_value	not set for temperature_10ge
	//	max_alarm	not set for temperature_10ge
	//	min_alarm	not set for temperature_10ge
	//	max_warning	not set for temperature_10ge
	//	min_warning	not set for temperature_10ge
	//	delta_t	not set for temperature_10ge
	//	delta_val	not set for temperature_10ge
	/*----- PROTECTED REGION ID(SlsDetectorControl::att_temperature_10ge_dynamic_attribute) ENABLED START -----*/
    /* clang-format on */
    //	Add your own code
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::att_temperature_10ge_dynamic_attribute
	temperature_10ge->set_default_properties(temperature_10ge_prop);
	//	Not Polled
	temperature_10ge->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	temperature_10ge_data.insert(make_pair(attname, 0));
	add_attribute(temperature_10ge);
}
//--------------------------------------------------------
/**
 *	remove a temperature_10ge dynamic attribute.
 *
 *  parameter attname: attribute name to be removed.
 */
//--------------------------------------------------------
void SlsDetectorControl::remove_temperature_10ge_dynamic_attribute(std::string attname)
{
	remove_attribute(attname, true, Tango::Util::instance()->_UseDb);
	map<std::string,Tango::DevLong>::iterator ite;
	if ((ite=temperature_10ge_data.find(attname))!=temperature_10ge_data.end())
	{
		/*----- PROTECTED REGION ID(SlsDetectorControl::remove_temperature_10ge_dynamic_attribute) ENABLED START -----*/
        /* clang-format on */
        //	Add your own code
        /* clang-format off */
		/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::remove_temperature_10ge_dynamic_attribute
		temperature_10ge_data.erase(ite);
	}
}
//--------------------------------------------------------
/**
 *	Add a temperature_adc dynamic attribute.
 *
 *  parameter attname: attribute name to be created and added.
 */
//--------------------------------------------------------
void SlsDetectorControl::add_temperature_adc_dynamic_attribute(std::string attname)
{
	//	Attribute : temperature_adc
	temperature_adcAttrib	*temperature_adc = new temperature_adcAttrib(attname);
	Tango::UserDefaultAttrProp	temperature_adc_prop;
	//	description	not set for temperature_adc
	//	label	not set for temperature_adc
	temperature_adc_prop.set_unit("°C");
	//	standard_unit	not set for temperature_adc
	//	display_unit	not set for temperature_adc
	//	format	not set for temperature_adc
	//	max_value	not set for temperature_adc
	//	min_value	not set for temperature_adc
	//	max_alarm	not set for temperature_adc
	//	min_alarm	not set for temperature_adc
	//	max_warning	not set for temperature_adc
	//	min_warning	not set for temperature_adc
	//	delta_t	not set for temperature_adc
	//	delta_val	not set for temperature_adc
	/*----- PROTECTED REGION ID(SlsDetectorControl::att_temperature_adc_dynamic_attribute) ENABLED START -----*/
    /* clang-format on */
    //	Add your own code
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::att_temperature_adc_dynamic_attribute
	temperature_adc->set_default_properties(temperature_adc_prop);
	//	Not Polled
	temperature_adc->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	temperature_adc_data.insert(make_pair(attname, 0));
	add_attribute(temperature_adc);
}
//--------------------------------------------------------
/**
 *	remove a temperature_adc dynamic attribute.
 *
 *  parameter attname: attribute name to be removed.
 */
//--------------------------------------------------------
void SlsDetectorControl::remove_temperature_adc_dynamic_attribute(std::string attname)
{
	remove_attribute(attname, true, Tango::Util::instance()->_UseDb);
	map<std::string,Tango::DevLong>::iterator ite;
	if ((ite=temperature_adc_data.find(attname))!=temperature_adc_data.end())
	{
		/*----- PROTECTED REGION ID(SlsDetectorControl::remove_temperature_adc_dynamic_attribute) ENABLED START -----*/
        /* clang-format on */
        //	Add your own code
        /* clang-format off */
		/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::remove_temperature_adc_dynamic_attribute
		temperature_adc_data.erase(ite);
	}
}
//--------------------------------------------------------
/**
 *	Add a temperature_dcdc dynamic attribute.
 *
 *  parameter attname: attribute name to be created and added.
 */
//--------------------------------------------------------
void SlsDetectorControl::add_temperature_dcdc_dynamic_attribute(std::string attname)
{
	//	Attribute : temperature_dcdc
	temperature_dcdcAttrib	*temperature_dcdc = new temperature_dcdcAttrib(attname);
	Tango::UserDefaultAttrProp	temperature_dcdc_prop;
	//	description	not set for temperature_dcdc
	//	label	not set for temperature_dcdc
	temperature_dcdc_prop.set_unit("°C");
	//	standard_unit	not set for temperature_dcdc
	//	display_unit	not set for temperature_dcdc
	//	format	not set for temperature_dcdc
	//	max_value	not set for temperature_dcdc
	//	min_value	not set for temperature_dcdc
	//	max_alarm	not set for temperature_dcdc
	//	min_alarm	not set for temperature_dcdc
	//	max_warning	not set for temperature_dcdc
	//	min_warning	not set for temperature_dcdc
	//	delta_t	not set for temperature_dcdc
	//	delta_val	not set for temperature_dcdc
	/*----- PROTECTED REGION ID(SlsDetectorControl::att_temperature_dcdc_dynamic_attribute) ENABLED START -----*/
    /* clang-format on */
    //	Add your own code
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::att_temperature_dcdc_dynamic_attribute
	temperature_dcdc->set_default_properties(temperature_dcdc_prop);
	//	Not Polled
	temperature_dcdc->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	temperature_dcdc_data.insert(make_pair(attname, 0));
	add_attribute(temperature_dcdc);
}
//--------------------------------------------------------
/**
 *	remove a temperature_dcdc dynamic attribute.
 *
 *  parameter attname: attribute name to be removed.
 */
//--------------------------------------------------------
void SlsDetectorControl::remove_temperature_dcdc_dynamic_attribute(std::string attname)
{
	remove_attribute(attname, true, Tango::Util::instance()->_UseDb);
	map<std::string,Tango::DevLong>::iterator ite;
	if ((ite=temperature_dcdc_data.find(attname))!=temperature_dcdc_data.end())
	{
		/*----- PROTECTED REGION ID(SlsDetectorControl::remove_temperature_dcdc_dynamic_attribute) ENABLED START -----*/
        /* clang-format on */
        //	Add your own code
        /* clang-format off */
		/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::remove_temperature_dcdc_dynamic_attribute
		temperature_dcdc_data.erase(ite);
	}
}
//--------------------------------------------------------
/**
 *	Add a temperature_fpga2 dynamic attribute.
 *
 *  parameter attname: attribute name to be created and added.
 */
//--------------------------------------------------------
void SlsDetectorControl::add_temperature_fpga2_dynamic_attribute(std::string attname)
{
	//	Attribute : temperature_fpga2
	temperature_fpga2Attrib	*temperature_fpga2 = new temperature_fpga2Attrib(attname);
	Tango::UserDefaultAttrProp	temperature_fpga2_prop;
	//	description	not set for temperature_fpga2
	//	label	not set for temperature_fpga2
	temperature_fpga2_prop.set_unit("°C");
	//	standard_unit	not set for temperature_fpga2
	//	display_unit	not set for temperature_fpga2
	//	format	not set for temperature_fpga2
	//	max_value	not set for temperature_fpga2
	//	min_value	not set for temperature_fpga2
	//	max_alarm	not set for temperature_fpga2
	//	min_alarm	not set for temperature_fpga2
	//	max_warning	not set for temperature_fpga2
	//	min_warning	not set for temperature_fpga2
	//	delta_t	not set for temperature_fpga2
	//	delta_val	not set for temperature_fpga2
	/*----- PROTECTED REGION ID(SlsDetectorControl::att_temperature_fpga2_dynamic_attribute) ENABLED START -----*/
    /* clang-format on */
    //	Add your own code
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::att_temperature_fpga2_dynamic_attribute
	temperature_fpga2->set_default_properties(temperature_fpga2_prop);
	//	Not Polled
	temperature_fpga2->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	temperature_fpga2_data.insert(make_pair(attname, 0));
	add_attribute(temperature_fpga2);
}
//--------------------------------------------------------
/**
 *	remove a temperature_fpga2 dynamic attribute.
 *
 *  parameter attname: attribute name to be removed.
 */
//--------------------------------------------------------
void SlsDetectorControl::remove_temperature_fpga2_dynamic_attribute(std::string attname)
{
	remove_attribute(attname, true, Tango::Util::instance()->_UseDb);
	map<std::string,Tango::DevLong>::iterator ite;
	if ((ite=temperature_fpga2_data.find(attname))!=temperature_fpga2_data.end())
	{
		/*----- PROTECTED REGION ID(SlsDetectorControl::remove_temperature_fpga2_dynamic_attribute) ENABLED START -----*/
        /* clang-format on */
        //	Add your own code
        /* clang-format off */
		/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::remove_temperature_fpga2_dynamic_attribute
		temperature_fpga2_data.erase(ite);
	}
}
//--------------------------------------------------------
/**
 *	Add a temperature_fpga3 dynamic attribute.
 *
 *  parameter attname: attribute name to be created and added.
 */
//--------------------------------------------------------
void SlsDetectorControl::add_temperature_fpga3_dynamic_attribute(std::string attname)
{
	//	Attribute : temperature_fpga3
	temperature_fpga3Attrib	*temperature_fpga3 = new temperature_fpga3Attrib(attname);
	Tango::UserDefaultAttrProp	temperature_fpga3_prop;
	//	description	not set for temperature_fpga3
	//	label	not set for temperature_fpga3
	temperature_fpga3_prop.set_unit("°C");
	//	standard_unit	not set for temperature_fpga3
	//	display_unit	not set for temperature_fpga3
	//	format	not set for temperature_fpga3
	//	max_value	not set for temperature_fpga3
	//	min_value	not set for temperature_fpga3
	//	max_alarm	not set for temperature_fpga3
	//	min_alarm	not set for temperature_fpga3
	//	max_warning	not set for temperature_fpga3
	//	min_warning	not set for temperature_fpga3
	//	delta_t	not set for temperature_fpga3
	//	delta_val	not set for temperature_fpga3
	/*----- PROTECTED REGION ID(SlsDetectorControl::att_temperature_fpga3_dynamic_attribute) ENABLED START -----*/
    /* clang-format on */
    //	Add your own code
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::att_temperature_fpga3_dynamic_attribute
	temperature_fpga3->set_default_properties(temperature_fpga3_prop);
	//	Not Polled
	temperature_fpga3->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	temperature_fpga3_data.insert(make_pair(attname, 0));
	add_attribute(temperature_fpga3);
}
//--------------------------------------------------------
/**
 *	remove a temperature_fpga3 dynamic attribute.
 *
 *  parameter attname: attribute name to be removed.
 */
//--------------------------------------------------------
void SlsDetectorControl::remove_temperature_fpga3_dynamic_attribute(std::string attname)
{
	remove_attribute(attname, true, Tango::Util::instance()->_UseDb);
	map<std::string,Tango::DevLong>::iterator ite;
	if ((ite=temperature_fpga3_data.find(attname))!=temperature_fpga3_data.end())
	{
		/*----- PROTECTED REGION ID(SlsDetectorControl::remove_temperature_fpga3_dynamic_attribute) ENABLED START -----*/
        /* clang-format on */
        //	Add your own code
        /* clang-format off */
		/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::remove_temperature_fpga3_dynamic_attribute
		temperature_fpga3_data.erase(ite);
	}
}
//--------------------------------------------------------
/**
 *	Add a temperature_fpgaext dynamic attribute.
 *
 *  parameter attname: attribute name to be created and added.
 */
//--------------------------------------------------------
void SlsDetectorControl::add_temperature_fpgaext_dynamic_attribute(std::string attname)
{
	//	Attribute : temperature_fpgaext
	temperature_fpgaextAttrib	*temperature_fpgaext = new temperature_fpgaextAttrib(attname);
	Tango::UserDefaultAttrProp	temperature_fpgaext_prop;
	//	description	not set for temperature_fpgaext
	//	label	not set for temperature_fpgaext
	temperature_fpgaext_prop.set_unit("°C");
	//	standard_unit	not set for temperature_fpgaext
	//	display_unit	not set for temperature_fpgaext
	//	format	not set for temperature_fpgaext
	//	max_value	not set for temperature_fpgaext
	//	min_value	not set for temperature_fpgaext
	//	max_alarm	not set for temperature_fpgaext
	//	min_alarm	not set for temperature_fpgaext
	//	max_warning	not set for temperature_fpgaext
	//	min_warning	not set for temperature_fpgaext
	//	delta_t	not set for temperature_fpgaext
	//	delta_val	not set for temperature_fpgaext
	/*----- PROTECTED REGION ID(SlsDetectorControl::att_temperature_fpgaext_dynamic_attribute) ENABLED START -----*/
    /* clang-format on */
    //	Add your own code
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::att_temperature_fpgaext_dynamic_attribute
	temperature_fpgaext->set_default_properties(temperature_fpgaext_prop);
	//	Not Polled
	temperature_fpgaext->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	temperature_fpgaext_data.insert(make_pair(attname, 0));
	add_attribute(temperature_fpgaext);
}
//--------------------------------------------------------
/**
 *	remove a temperature_fpgaext dynamic attribute.
 *
 *  parameter attname: attribute name to be removed.
 */
//--------------------------------------------------------
void SlsDetectorControl::remove_temperature_fpgaext_dynamic_attribute(std::string attname)
{
	remove_attribute(attname, true, Tango::Util::instance()->_UseDb);
	map<std::string,Tango::DevLong>::iterator ite;
	if ((ite=temperature_fpgaext_data.find(attname))!=temperature_fpgaext_data.end())
	{
		/*----- PROTECTED REGION ID(SlsDetectorControl::remove_temperature_fpgaext_dynamic_attribute) ENABLED START -----*/
        /* clang-format on */
        //	Add your own code
        /* clang-format off */
		/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::remove_temperature_fpgaext_dynamic_attribute
		temperature_fpgaext_data.erase(ite);
	}
}
//--------------------------------------------------------
/**
 *	Add a temperature_sodl dynamic attribute.
 *
 *  parameter attname: attribute name to be created and added.
 */
//--------------------------------------------------------
void SlsDetectorControl::add_temperature_sodl_dynamic_attribute(std::string attname)
{
	//	Attribute : temperature_sodl
	temperature_sodlAttrib	*temperature_sodl = new temperature_sodlAttrib(attname);
	Tango::UserDefaultAttrProp	temperature_sodl_prop;
	//	description	not set for temperature_sodl
	//	label	not set for temperature_sodl
	temperature_sodl_prop.set_unit("°C");
	//	standard_unit	not set for temperature_sodl
	//	display_unit	not set for temperature_sodl
	//	format	not set for temperature_sodl
	//	max_value	not set for temperature_sodl
	//	min_value	not set for temperature_sodl
	//	max_alarm	not set for temperature_sodl
	//	min_alarm	not set for temperature_sodl
	//	max_warning	not set for temperature_sodl
	//	min_warning	not set for temperature_sodl
	//	delta_t	not set for temperature_sodl
	//	delta_val	not set for temperature_sodl
	/*----- PROTECTED REGION ID(SlsDetectorControl::att_temperature_sodl_dynamic_attribute) ENABLED START -----*/
    /* clang-format on */
    //	Add your own code
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::att_temperature_sodl_dynamic_attribute
	temperature_sodl->set_default_properties(temperature_sodl_prop);
	//	Not Polled
	temperature_sodl->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	temperature_sodl_data.insert(make_pair(attname, 0));
	add_attribute(temperature_sodl);
}
//--------------------------------------------------------
/**
 *	remove a temperature_sodl dynamic attribute.
 *
 *  parameter attname: attribute name to be removed.
 */
//--------------------------------------------------------
void SlsDetectorControl::remove_temperature_sodl_dynamic_attribute(std::string attname)
{
	remove_attribute(attname, true, Tango::Util::instance()->_UseDb);
	map<std::string,Tango::DevLong>::iterator ite;
	if ((ite=temperature_sodl_data.find(attname))!=temperature_sodl_data.end())
	{
		/*----- PROTECTED REGION ID(SlsDetectorControl::remove_temperature_sodl_dynamic_attribute) ENABLED START -----*/
        /* clang-format on */
        //	Add your own code
        /* clang-format off */
		/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::remove_temperature_sodl_dynamic_attribute
		temperature_sodl_data.erase(ite);
	}
}
//--------------------------------------------------------
/**
 *	Add a temperature_sodr dynamic attribute.
 *
 *  parameter attname: attribute name to be created and added.
 */
//--------------------------------------------------------
void SlsDetectorControl::add_temperature_sodr_dynamic_attribute(std::string attname)
{
	//	Attribute : temperature_sodr
	temperature_sodrAttrib	*temperature_sodr = new temperature_sodrAttrib(attname);
	Tango::UserDefaultAttrProp	temperature_sodr_prop;
	//	description	not set for temperature_sodr
	//	label	not set for temperature_sodr
	temperature_sodr_prop.set_unit("°C");
	//	standard_unit	not set for temperature_sodr
	//	display_unit	not set for temperature_sodr
	//	format	not set for temperature_sodr
	//	max_value	not set for temperature_sodr
	//	min_value	not set for temperature_sodr
	//	max_alarm	not set for temperature_sodr
	//	min_alarm	not set for temperature_sodr
	//	max_warning	not set for temperature_sodr
	//	min_warning	not set for temperature_sodr
	//	delta_t	not set for temperature_sodr
	//	delta_val	not set for temperature_sodr
	/*----- PROTECTED REGION ID(SlsDetectorControl::att_temperature_sodr_dynamic_attribute) ENABLED START -----*/
    /* clang-format on */
    //	Add your own code
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::att_temperature_sodr_dynamic_attribute
	temperature_sodr->set_default_properties(temperature_sodr_prop);
	//	Not Polled
	temperature_sodr->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	temperature_sodr_data.insert(make_pair(attname, 0));
	add_attribute(temperature_sodr);
}
//--------------------------------------------------------
/**
 *	remove a temperature_sodr dynamic attribute.
 *
 *  parameter attname: attribute name to be removed.
 */
//--------------------------------------------------------
void SlsDetectorControl::remove_temperature_sodr_dynamic_attribute(std::string attname)
{
	remove_attribute(attname, true, Tango::Util::instance()->_UseDb);
	map<std::string,Tango::DevLong>::iterator ite;
	if ((ite=temperature_sodr_data.find(attname))!=temperature_sodr_data.end())
	{
		/*----- PROTECTED REGION ID(SlsDetectorControl::remove_temperature_sodr_dynamic_attribute) ENABLED START -----*/
        /* clang-format on */
        //	Add your own code
        /* clang-format off */
		/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::remove_temperature_sodr_dynamic_attribute
		temperature_sodr_data.erase(ite);
	}
}
//--------------------------------------------------------
/**
 *	Add a tengiga dynamic attribute.
 *
 *  parameter attname: attribute name to be created and added.
 */
//--------------------------------------------------------
void SlsDetectorControl::add_tengiga_dynamic_attribute(std::string attname)
{
	//	Attribute : tengiga
	tengigaAttrib	*tengiga = new tengigaAttrib(attname);
	Tango::UserDefaultAttrProp	tengiga_prop;
	//	description	not set for tengiga
	//	label	not set for tengiga
	//	unit	not set for tengiga
	//	standard_unit	not set for tengiga
	//	display_unit	not set for tengiga
	//	format	not set for tengiga
	//	max_value	not set for tengiga
	//	min_value	not set for tengiga
	//	max_alarm	not set for tengiga
	//	min_alarm	not set for tengiga
	//	max_warning	not set for tengiga
	//	min_warning	not set for tengiga
	//	delta_t	not set for tengiga
	//	delta_val	not set for tengiga
	/*----- PROTECTED REGION ID(SlsDetectorControl::att_tengiga_dynamic_attribute) ENABLED START -----*/
    /* clang-format on */
    //	Add your own code
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::att_tengiga_dynamic_attribute
	tengiga->set_default_properties(tengiga_prop);
	//	Not Polled
	tengiga->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	tengiga_data.insert(make_pair(attname, false));
	add_attribute(tengiga);
}
//--------------------------------------------------------
/**
 *	remove a tengiga dynamic attribute.
 *
 *  parameter attname: attribute name to be removed.
 */
//--------------------------------------------------------
void SlsDetectorControl::remove_tengiga_dynamic_attribute(std::string attname)
{
	remove_attribute(attname, true, Tango::Util::instance()->_UseDb);
	map<std::string,Tango::DevBoolean>::iterator ite;
	if ((ite=tengiga_data.find(attname))!=tengiga_data.end())
	{
		/*----- PROTECTED REGION ID(SlsDetectorControl::remove_tengiga_dynamic_attribute) ENABLED START -----*/
        /* clang-format on */
        //	Add your own code
        /* clang-format off */
		/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::remove_tengiga_dynamic_attribute
		tengiga_data.erase(ite);
	}
}
//--------------------------------------------------------
/**
 *	Add a timing_mode dynamic attribute.
 *
 *  parameter attname: attribute name to be created and added.
 */
//--------------------------------------------------------
void SlsDetectorControl::add_timing_mode_dynamic_attribute(std::string attname)
{
	//	Attribute : timing_mode
	timing_modeAttrib	*timing_mode = new timing_modeAttrib(attname);
	Tango::UserDefaultAttrProp	timing_mode_prop;
	//	description	not set for timing_mode
	//	label	not set for timing_mode
	//	unit	not set for timing_mode
	//	standard_unit	not set for timing_mode
	//	display_unit	not set for timing_mode
	//	format	not set for timing_mode
	//	max_value	not set for timing_mode
	//	min_value	not set for timing_mode
	//	max_alarm	not set for timing_mode
	//	min_alarm	not set for timing_mode
	//	max_warning	not set for timing_mode
	//	min_warning	not set for timing_mode
	//	delta_t	not set for timing_mode
	//	delta_val	not set for timing_mode
	/*----- PROTECTED REGION ID(SlsDetectorControl::att_timing_mode_dynamic_attribute) ENABLED START -----*/
    /* clang-format on */
    //	Add your own code
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::att_timing_mode_dynamic_attribute
	timing_mode->set_default_properties(timing_mode_prop);
	//	Not Polled
	timing_mode->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	timing_mode_data.insert(make_pair(attname, 0));
	add_attribute(timing_mode);
}
//--------------------------------------------------------
/**
 *	remove a timing_mode dynamic attribute.
 *
 *  parameter attname: attribute name to be removed.
 */
//--------------------------------------------------------
void SlsDetectorControl::remove_timing_mode_dynamic_attribute(std::string attname)
{
	remove_attribute(attname, true, Tango::Util::instance()->_UseDb);
	map<std::string,Tango::DevEnum>::iterator ite;
	if ((ite=timing_mode_data.find(attname))!=timing_mode_data.end())
	{
		/*----- PROTECTED REGION ID(SlsDetectorControl::remove_timing_mode_dynamic_attribute) ENABLED START -----*/
        /* clang-format on */
        //	Add your own code
        /* clang-format off */
		/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::remove_timing_mode_dynamic_attribute
		timing_mode_data.erase(ite);
	}
}
//--------------------------------------------------------
/**
 *	Add a threshold_energy dynamic attribute.
 *
 *  parameter attname: attribute name to be created and added.
 *  parameter ptr:     memory buffer used to set attribute value.
 *                     If NULL or not specified, buffer will be allocated.
 */
//--------------------------------------------------------
void SlsDetectorControl::add_threshold_energy_dynamic_attribute(std::string attname, Tango::DevLong *ptr)
{
	//	Attribute : threshold_energy
	if (ptr==NULL)
		ptr = new Tango::DevLong[3];
	threshold_energyAttrib	*threshold_energy = new threshold_energyAttrib(attname);
	Tango::UserDefaultAttrProp	threshold_energy_prop;
	//	description	not set for threshold_energy
	//	label	not set for threshold_energy
	//	unit	not set for threshold_energy
	//	standard_unit	not set for threshold_energy
	//	display_unit	not set for threshold_energy
	//	format	not set for threshold_energy
	//	max_value	not set for threshold_energy
	//	min_value	not set for threshold_energy
	//	max_alarm	not set for threshold_energy
	//	min_alarm	not set for threshold_energy
	//	max_warning	not set for threshold_energy
	//	min_warning	not set for threshold_energy
	//	delta_t	not set for threshold_energy
	//	delta_val	not set for threshold_energy
	/*----- PROTECTED REGION ID(SlsDetectorControl::att_threshold_energy_dynamic_attribute) ENABLED START -----*/
    /* clang-format on */
    //	Add your own code
    /* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::att_threshold_energy_dynamic_attribute
	threshold_energy->set_default_properties(threshold_energy_prop);
	//	Not Polled
	threshold_energy->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	threshold_energy_data.insert(make_pair(attname, ptr));
	add_attribute(threshold_energy);
}
//--------------------------------------------------------
/**
 *	remove a threshold_energy dynamic attribute.
 *
 *  parameter attname: attribute name to be removed.
 *  parameter free_it: memory buffer will be freed if true or not specified.
 */
//--------------------------------------------------------
void SlsDetectorControl::remove_threshold_energy_dynamic_attribute(std::string attname, bool free_it)
{
	remove_attribute(attname, true, Tango::Util::instance()->_UseDb);
	map<std::string,Tango::DevLong *>::iterator ite;
	if ((ite=threshold_energy_data.find(attname))!=threshold_energy_data.end())
	{
		/*----- PROTECTED REGION ID(SlsDetectorControl::remove_threshold_energy_dynamic_attribute) ENABLED START -----*/
        /* clang-format on */
        //	Add your own code
        /* clang-format off */
		/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::remove_threshold_energy_dynamic_attribute
		if (free_it)
			delete[] ite->second;
		threshold_energy_data.erase(ite);
	}
}


//============================================================
//	Tool methods to get pointer on attribute data buffer
//============================================================
//--------------------------------------------------------
/**
 *	Return a pointer on adc_phase data.
 *
 *  parameter attname: the specified attribute name.
 */
//--------------------------------------------------------
Tango::DevLong *SlsDetectorControl::get_adc_phase_data_ptr(std::string &name)
{
	map<std::string,Tango::DevLong>::iterator ite;
	if ((ite=adc_phase_data.find(name))==adc_phase_data.end())
	{
		TangoSys_OMemStream	tms;
		tms << "Dynamic attribute " << name << " has not been created";
		Tango::Except::throw_exception(
					(const char *)"ATTRIBUTE_NOT_FOUND",
					tms.str().c_str(),
					(const char *)"SlsDetectorControl::get_adc_phase_data_ptr()");
	}
	return  &(ite->second);
}
//--------------------------------------------------------
/**
 *	Return a pointer on delay_after_trigger data.
 *
 *  parameter attname: the specified attribute name.
 */
//--------------------------------------------------------
Tango::DevDouble *SlsDetectorControl::get_delay_after_trigger_data_ptr(std::string &name)
{
	map<std::string,Tango::DevDouble>::iterator ite;
	if ((ite=delay_after_trigger_data.find(name))==delay_after_trigger_data.end())
	{
		TangoSys_OMemStream	tms;
		tms << "Dynamic attribute " << name << " has not been created";
		Tango::Except::throw_exception(
					(const char *)"ATTRIBUTE_NOT_FOUND",
					tms.str().c_str(),
					(const char *)"SlsDetectorControl::get_delay_after_trigger_data_ptr()");
	}
	return  &(ite->second);
}
//--------------------------------------------------------
/**
 *	Return a pointer on detector_setting data.
 *
 *  parameter attname: the specified attribute name.
 */
//--------------------------------------------------------
Tango::DevEnum *SlsDetectorControl::get_detector_setting_data_ptr(std::string &name)
{
	map<std::string,Tango::DevEnum>::iterator ite;
	if ((ite=detector_setting_data.find(name))==detector_setting_data.end())
	{
		TangoSys_OMemStream	tms;
		tms << "Dynamic attribute " << name << " has not been created";
		Tango::Except::throw_exception(
					(const char *)"ATTRIBUTE_NOT_FOUND",
					tms.str().c_str(),
					(const char *)"SlsDetectorControl::get_detector_setting_data_ptr()");
	}
	return  &(ite->second);
}
//--------------------------------------------------------
/**
 *	Return a pointer on detector_status data.
 *
 *  parameter attname: the specified attribute name.
 */
//--------------------------------------------------------
Tango::DevEnum *SlsDetectorControl::get_detector_status_data_ptr(std::string &name)
{
	map<std::string,Tango::DevEnum>::iterator ite;
	if ((ite=detector_status_data.find(name))==detector_status_data.end())
	{
		TangoSys_OMemStream	tms;
		tms << "Dynamic attribute " << name << " has not been created";
		Tango::Except::throw_exception(
					(const char *)"ATTRIBUTE_NOT_FOUND",
					tms.str().c_str(),
					(const char *)"SlsDetectorControl::get_detector_status_data_ptr()");
	}
	return  &(ite->second);
}
//--------------------------------------------------------
/**
 *	Return a pointer on file_format data.
 *
 *  parameter attname: the specified attribute name.
 */
//--------------------------------------------------------
Tango::DevEnum *SlsDetectorControl::get_file_format_data_ptr(std::string &name)
{
	map<std::string,Tango::DevEnum>::iterator ite;
	if ((ite=file_format_data.find(name))==file_format_data.end())
	{
		TangoSys_OMemStream	tms;
		tms << "Dynamic attribute " << name << " has not been created";
		Tango::Except::throw_exception(
					(const char *)"ATTRIBUTE_NOT_FOUND",
					tms.str().c_str(),
					(const char *)"SlsDetectorControl::get_file_format_data_ptr()");
	}
	return  &(ite->second);
}
//--------------------------------------------------------
/**
 *	Return a pointer on num_frames_left data.
 *
 *  parameter attname: the specified attribute name.
 */
//--------------------------------------------------------
Tango::DevLong64 *SlsDetectorControl::get_num_frames_left_data_ptr(std::string &name)
{
	map<std::string,Tango::DevLong64>::iterator ite;
	if ((ite=num_frames_left_data.find(name))==num_frames_left_data.end())
	{
		TangoSys_OMemStream	tms;
		tms << "Dynamic attribute " << name << " has not been created";
		Tango::Except::throw_exception(
					(const char *)"ATTRIBUTE_NOT_FOUND",
					tms.str().c_str(),
					(const char *)"SlsDetectorControl::get_num_frames_left_data_ptr()");
	}
	return  &(ite->second);
}
//--------------------------------------------------------
/**
 *	Return a pointer on num_triggers_left data.
 *
 *  parameter attname: the specified attribute name.
 */
//--------------------------------------------------------
Tango::DevLong *SlsDetectorControl::get_num_triggers_left_data_ptr(std::string &name)
{
	map<std::string,Tango::DevLong>::iterator ite;
	if ((ite=num_triggers_left_data.find(name))==num_triggers_left_data.end())
	{
		TangoSys_OMemStream	tms;
		tms << "Dynamic attribute " << name << " has not been created";
		Tango::Except::throw_exception(
					(const char *)"ATTRIBUTE_NOT_FOUND",
					tms.str().c_str(),
					(const char *)"SlsDetectorControl::get_num_triggers_left_data_ptr()");
	}
	return  &(ite->second);
}
//--------------------------------------------------------
/**
 *	Return a pointer on power_chip data.
 *
 *  parameter attname: the specified attribute name.
 */
//--------------------------------------------------------
Tango::DevBoolean *SlsDetectorControl::get_power_chip_data_ptr(std::string &name)
{
	map<std::string,Tango::DevBoolean>::iterator ite;
	if ((ite=power_chip_data.find(name))==power_chip_data.end())
	{
		TangoSys_OMemStream	tms;
		tms << "Dynamic attribute " << name << " has not been created";
		Tango::Except::throw_exception(
					(const char *)"ATTRIBUTE_NOT_FOUND",
					tms.str().c_str(),
					(const char *)"SlsDetectorControl::get_power_chip_data_ptr()");
	}
	return  &(ite->second);
}
//--------------------------------------------------------
/**
 *	Return a pointer on readout_speed data.
 *
 *  parameter attname: the specified attribute name.
 */
//--------------------------------------------------------
Tango::DevEnum *SlsDetectorControl::get_readout_speed_data_ptr(std::string &name)
{
	map<std::string,Tango::DevEnum>::iterator ite;
	if ((ite=readout_speed_data.find(name))==readout_speed_data.end())
	{
		TangoSys_OMemStream	tms;
		tms << "Dynamic attribute " << name << " has not been created";
		Tango::Except::throw_exception(
					(const char *)"ATTRIBUTE_NOT_FOUND",
					tms.str().c_str(),
					(const char *)"SlsDetectorControl::get_readout_speed_data_ptr()");
	}
	return  &(ite->second);
}
//--------------------------------------------------------
/**
 *	Return a pointer on receiver_status data.
 *
 *  parameter attname: the specified attribute name.
 */
//--------------------------------------------------------
Tango::DevEnum *SlsDetectorControl::get_receiver_status_data_ptr(std::string &name)
{
	map<std::string,Tango::DevEnum>::iterator ite;
	if ((ite=receiver_status_data.find(name))==receiver_status_data.end())
	{
		TangoSys_OMemStream	tms;
		tms << "Dynamic attribute " << name << " has not been created";
		Tango::Except::throw_exception(
					(const char *)"ATTRIBUTE_NOT_FOUND",
					tms.str().c_str(),
					(const char *)"SlsDetectorControl::get_receiver_status_data_ptr()");
	}
	return  &(ite->second);
}
//--------------------------------------------------------
/**
 *	Return a pointer on temperature_10ge data.
 *
 *  parameter attname: the specified attribute name.
 */
//--------------------------------------------------------
Tango::DevLong *SlsDetectorControl::get_temperature_10ge_data_ptr(std::string &name)
{
	map<std::string,Tango::DevLong>::iterator ite;
	if ((ite=temperature_10ge_data.find(name))==temperature_10ge_data.end())
	{
		TangoSys_OMemStream	tms;
		tms << "Dynamic attribute " << name << " has not been created";
		Tango::Except::throw_exception(
					(const char *)"ATTRIBUTE_NOT_FOUND",
					tms.str().c_str(),
					(const char *)"SlsDetectorControl::get_temperature_10ge_data_ptr()");
	}
	return  &(ite->second);
}
//--------------------------------------------------------
/**
 *	Return a pointer on temperature_adc data.
 *
 *  parameter attname: the specified attribute name.
 */
//--------------------------------------------------------
Tango::DevLong *SlsDetectorControl::get_temperature_adc_data_ptr(std::string &name)
{
	map<std::string,Tango::DevLong>::iterator ite;
	if ((ite=temperature_adc_data.find(name))==temperature_adc_data.end())
	{
		TangoSys_OMemStream	tms;
		tms << "Dynamic attribute " << name << " has not been created";
		Tango::Except::throw_exception(
					(const char *)"ATTRIBUTE_NOT_FOUND",
					tms.str().c_str(),
					(const char *)"SlsDetectorControl::get_temperature_adc_data_ptr()");
	}
	return  &(ite->second);
}
//--------------------------------------------------------
/**
 *	Return a pointer on temperature_dcdc data.
 *
 *  parameter attname: the specified attribute name.
 */
//--------------------------------------------------------
Tango::DevLong *SlsDetectorControl::get_temperature_dcdc_data_ptr(std::string &name)
{
	map<std::string,Tango::DevLong>::iterator ite;
	if ((ite=temperature_dcdc_data.find(name))==temperature_dcdc_data.end())
	{
		TangoSys_OMemStream	tms;
		tms << "Dynamic attribute " << name << " has not been created";
		Tango::Except::throw_exception(
					(const char *)"ATTRIBUTE_NOT_FOUND",
					tms.str().c_str(),
					(const char *)"SlsDetectorControl::get_temperature_dcdc_data_ptr()");
	}
	return  &(ite->second);
}
//--------------------------------------------------------
/**
 *	Return a pointer on temperature_fpga2 data.
 *
 *  parameter attname: the specified attribute name.
 */
//--------------------------------------------------------
Tango::DevLong *SlsDetectorControl::get_temperature_fpga2_data_ptr(std::string &name)
{
	map<std::string,Tango::DevLong>::iterator ite;
	if ((ite=temperature_fpga2_data.find(name))==temperature_fpga2_data.end())
	{
		TangoSys_OMemStream	tms;
		tms << "Dynamic attribute " << name << " has not been created";
		Tango::Except::throw_exception(
					(const char *)"ATTRIBUTE_NOT_FOUND",
					tms.str().c_str(),
					(const char *)"SlsDetectorControl::get_temperature_fpga2_data_ptr()");
	}
	return  &(ite->second);
}
//--------------------------------------------------------
/**
 *	Return a pointer on temperature_fpga3 data.
 *
 *  parameter attname: the specified attribute name.
 */
//--------------------------------------------------------
Tango::DevLong *SlsDetectorControl::get_temperature_fpga3_data_ptr(std::string &name)
{
	map<std::string,Tango::DevLong>::iterator ite;
	if ((ite=temperature_fpga3_data.find(name))==temperature_fpga3_data.end())
	{
		TangoSys_OMemStream	tms;
		tms << "Dynamic attribute " << name << " has not been created";
		Tango::Except::throw_exception(
					(const char *)"ATTRIBUTE_NOT_FOUND",
					tms.str().c_str(),
					(const char *)"SlsDetectorControl::get_temperature_fpga3_data_ptr()");
	}
	return  &(ite->second);
}
//--------------------------------------------------------
/**
 *	Return a pointer on temperature_fpgaext data.
 *
 *  parameter attname: the specified attribute name.
 */
//--------------------------------------------------------
Tango::DevLong *SlsDetectorControl::get_temperature_fpgaext_data_ptr(std::string &name)
{
	map<std::string,Tango::DevLong>::iterator ite;
	if ((ite=temperature_fpgaext_data.find(name))==temperature_fpgaext_data.end())
	{
		TangoSys_OMemStream	tms;
		tms << "Dynamic attribute " << name << " has not been created";
		Tango::Except::throw_exception(
					(const char *)"ATTRIBUTE_NOT_FOUND",
					tms.str().c_str(),
					(const char *)"SlsDetectorControl::get_temperature_fpgaext_data_ptr()");
	}
	return  &(ite->second);
}
//--------------------------------------------------------
/**
 *	Return a pointer on temperature_sodl data.
 *
 *  parameter attname: the specified attribute name.
 */
//--------------------------------------------------------
Tango::DevLong *SlsDetectorControl::get_temperature_sodl_data_ptr(std::string &name)
{
	map<std::string,Tango::DevLong>::iterator ite;
	if ((ite=temperature_sodl_data.find(name))==temperature_sodl_data.end())
	{
		TangoSys_OMemStream	tms;
		tms << "Dynamic attribute " << name << " has not been created";
		Tango::Except::throw_exception(
					(const char *)"ATTRIBUTE_NOT_FOUND",
					tms.str().c_str(),
					(const char *)"SlsDetectorControl::get_temperature_sodl_data_ptr()");
	}
	return  &(ite->second);
}
//--------------------------------------------------------
/**
 *	Return a pointer on temperature_sodr data.
 *
 *  parameter attname: the specified attribute name.
 */
//--------------------------------------------------------
Tango::DevLong *SlsDetectorControl::get_temperature_sodr_data_ptr(std::string &name)
{
	map<std::string,Tango::DevLong>::iterator ite;
	if ((ite=temperature_sodr_data.find(name))==temperature_sodr_data.end())
	{
		TangoSys_OMemStream	tms;
		tms << "Dynamic attribute " << name << " has not been created";
		Tango::Except::throw_exception(
					(const char *)"ATTRIBUTE_NOT_FOUND",
					tms.str().c_str(),
					(const char *)"SlsDetectorControl::get_temperature_sodr_data_ptr()");
	}
	return  &(ite->second);
}
//--------------------------------------------------------
/**
 *	Return a pointer on tengiga data.
 *
 *  parameter attname: the specified attribute name.
 */
//--------------------------------------------------------
Tango::DevBoolean *SlsDetectorControl::get_tengiga_data_ptr(std::string &name)
{
	map<std::string,Tango::DevBoolean>::iterator ite;
	if ((ite=tengiga_data.find(name))==tengiga_data.end())
	{
		TangoSys_OMemStream	tms;
		tms << "Dynamic attribute " << name << " has not been created";
		Tango::Except::throw_exception(
					(const char *)"ATTRIBUTE_NOT_FOUND",
					tms.str().c_str(),
					(const char *)"SlsDetectorControl::get_tengiga_data_ptr()");
	}
	return  &(ite->second);
}
//--------------------------------------------------------
/**
 *	Return a pointer on timing_mode data.
 *
 *  parameter attname: the specified attribute name.
 */
//--------------------------------------------------------
Tango::DevEnum *SlsDetectorControl::get_timing_mode_data_ptr(std::string &name)
{
	map<std::string,Tango::DevEnum>::iterator ite;
	if ((ite=timing_mode_data.find(name))==timing_mode_data.end())
	{
		TangoSys_OMemStream	tms;
		tms << "Dynamic attribute " << name << " has not been created";
		Tango::Except::throw_exception(
					(const char *)"ATTRIBUTE_NOT_FOUND",
					tms.str().c_str(),
					(const char *)"SlsDetectorControl::get_timing_mode_data_ptr()");
	}
	return  &(ite->second);
}
//--------------------------------------------------------
/**
 *	Return a pointer on threshold_energy data.
 *
 *  parameter attname: the specified attribute name.
 */
//--------------------------------------------------------
Tango::DevLong *SlsDetectorControl::get_threshold_energy_data_ptr(std::string &name)
{
	map<std::string,Tango::DevLong *>::iterator ite;
	if ((ite=threshold_energy_data.find(name))==threshold_energy_data.end())
	{
		TangoSys_OMemStream	tms;
		tms << "Dynamic attribute " << name << " has not been created";
		Tango::Except::throw_exception(
					(const char *)"ATTRIBUTE_NOT_FOUND",
					tms.str().c_str(),
					(const char *)"SlsDetectorControl::get_threshold_energy_data_ptr()");
	}
	return  ite->second;
}


//=============================================================
//	Add/Remove dynamic command methods
//=============================================================

//--------------------------------------------------------
/**
 *	Add a load_trimbits dynamic command.
 *
 *  parameter cmdname: command name to be created and added.
 *  parameter device:  Set this flag to true if the command must be added for only this device.
 */
//--------------------------------------------------------
void SlsDetectorControl::add_load_trimbits_dynamic_command(std::string cmdname, bool device)
{
	load_trimbitsClass	*pload_trimbitsCmd =
		new load_trimbitsClass(cmdname.c_str(),
			Tango::DEV_STRING, Tango::DEV_VOID,
			"",
			"",
			Tango::OPERATOR);
	add_command(pload_trimbitsCmd, device);
}
//--------------------------------------------------------
/**
 *	remove a load_trimbits dynamic command.
 *
 *  parameter cmdname: command name to be removed.
 */
//--------------------------------------------------------
void SlsDetectorControl::remove_load_trimbits_dynamic_command(std::string cmdname)
{
	remove_command(cmdname, true);
}

} //	namespace
