/*----- PROTECTED REGION ID(SlsDetectorControl.h) ENABLED START -----*/
/* clang-format on */
//=============================================================================
//
// file :        SlsDetectorControl.h
//
// description : Include file for the SlsDetectorControl class
//
// project :     tango-slsdetectorcontrol
//
// This file is part of Tango device class.
//
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the MIT licence.
//
//
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================

#ifndef SlsDetectorControl_H
#define SlsDetectorControl_H

#include <map>
#include <tango/tango.h>
using std::map;
#include <chrono>
#include <functional>
#include <unordered_map>
#include <string>
#include <variant>
#include <vector>

#include <sls/Detector.h>
#include <sls/Receiver.h>
#include <sls/ToString.h>
#include <sls/sls_detector_defs.h>
#include <sls/sls_detector_exceptions.h>
#include <filesystem>
#include <unistd.h>
#include <csignal>
#include <sys/wait.h>

using std::chrono_literals::operator""s;
using dacIndex = sls::defs::dacIndex;
using detectorType = sls::defs::detectorType;
using speedLevel = sls::defs::speedLevel;
using timingMode = sls::defs::timingMode;
using detectorSettings = sls::defs::detectorSettings;
using fileFormat = sls::defs::fileFormat;
using runStatus = sls::defs::runStatus;
/* clang-format off */
/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl.h

#ifdef TANGO_LOG
	// cppTango after c934adea (Merge branch 'remove-cout-definition' into 'main', 2022-05-23)
	// nothing to do
#else
	// cppTango 9.3-backports and older
	#define TANGO_LOG       cout
	#define TANGO_LOG_INFO  cout2
	#define TANGO_LOG_DEBUG cout3
#endif // TANGO_LOG

/**
 *  SlsDetectorControl class description:
 *    
 */


namespace SlsDetectorControl_ns
{
enum class _detector_settingEnum : short {
} ;
typedef _detector_settingEnum detector_settingEnum;

enum class _detector_statusEnum : short {
} ;
typedef _detector_statusEnum detector_statusEnum;

enum class _file_formatEnum : short {
} ;
typedef _file_formatEnum file_formatEnum;

enum class _readout_speedEnum : short {
} ;
typedef _readout_speedEnum readout_speedEnum;

enum class _receiver_statusEnum : short {
} ;
typedef _receiver_statusEnum receiver_statusEnum;

enum class _timing_modeEnum : short {
} ;
typedef _timing_modeEnum timing_modeEnum;

/*----- PROTECTED REGION ID(SlsDetectorControl::Additional Class Declarations) ENABLED START -----*/
/* clang-format on */

struct attribute_info
{
    bool available;
    std::function<bool()> checkFunction;
    std::function<void(std::string)> registerFunction;
};

template <typename T>
class SlsTangoEnumAdapter
{
    // should collect the enums from the detector to slsEnumList
  public:
    std::vector<T> slsEnumList;
    std::vector<std::string> slsEnumLabels;
    std::unordered_map<short, short> slsEnumToTangoEnumMap;

    SlsTangoEnumAdapter(std::vector<T> slsEnumList) :
        slsEnumList(slsEnumList)
    {
        for(short i = 0; i < slsEnumList.size(); ++i)
        {
            slsEnumToTangoEnumMap.insert({static_cast<short>(slsEnumList[i]), i});
            slsEnumLabels.push_back(sls::ToString(slsEnumList[i]));
        }
    }

    T toSlsEnum(Tango::DevEnum tangoEnum)
    {
        return slsEnumList[tangoEnum];
    }

    Tango::DevEnum toTangoEnum(T slsEnum)
    {
        return slsEnumToTangoEnumMap[slsEnum];
    }
};

/* clang-format off */
/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::Additional Class Declarations

class SlsDetectorControl : public TANGO_BASE_CLASS
{

/*----- PROTECTED REGION ID(SlsDetectorControl::Data Members) ENABLED START -----*/
    /* clang-format on */
  private:
    std::unique_ptr<sls::Detector> detector_ptr;
#if SLS_DET_EMBED_RECEIVER
    std::unique_ptr<sls::Receiver> receiver_ptr;
#endif
    pid_t receiver_pid;

  public:
    /*
     * Some attributes are only available for some detectors.
     * The only robust way to determine if the attribute is available
     * is to try to read it and catch the exception if it is not available.
     */
    map<std::string, attribute_info> attributesInfo = {
        {"adc_phase",
         {true,
          [this]()
          {
              this->detector_ptr->getADCPhase();
              return true;
          },
          [this](std::string name) { this->add_adc_phase_dynamic_attribute(name); }}},
        {"delay_after_trigger",
         {true,
          [this]()
          {
              this->detector_ptr->getDelayAfterTrigger();
              return true;
          },
          [this](std::string name) { this->add_delay_after_trigger_dynamic_attribute(name); }}},
        {"detector_status",
         {true,
          [this]()
          {
              auto status = this->detector_ptr->getDetectorStatus();
              this->detStatusAdapter_ptr =
                  std::make_unique<SlsTangoEnumAdapter<runStatus>>(std::initializer_list{runStatus::IDLE,
                                                                                         runStatus::ERROR,
                                                                                         runStatus::WAITING,
                                                                                         runStatus::RUN_FINISHED,
                                                                                         runStatus::TRANSMITTING,
                                                                                         runStatus::RUNNING,
                                                                                         runStatus::STOPPED});
              return true;
          },
          [this](std::string name) { this->add_detector_status_dynamic_attribute(name, this->detStatusAdapter_ptr); }}},
        {"receiver_status",
         {true,
          [this]()
          {
              auto status = this->detector_ptr->getReceiverStatus();
              this->recStatusAdapter_ptr = std::make_unique<SlsTangoEnumAdapter<runStatus>>(
                  std::initializer_list{runStatus::IDLE, runStatus::TRANSMITTING, runStatus::RUNNING});
              return true;
          },
          [this](std::string name) { this->add_receiver_status_dynamic_attribute(name, this->recStatusAdapter_ptr); }}},
        {"file_format",
         {true,
          [this]()
          {
              this->fileFormatAdapter_ptr = std::make_unique<SlsTangoEnumAdapter<fileFormat>>(
                  std::initializer_list{fileFormat::BINARY, fileFormat::HDF5});
              return true;
          },
          [this](std::string name) { this->add_file_format_dynamic_attribute(name, this->fileFormatAdapter_ptr); }}},
        {"num_frames_left",
         {true,
          [this]()
          {
              this->detector_ptr->getNumberOfFramesLeft();
              return true;
          },
          [this](std::string name) { this->add_num_frames_left_dynamic_attribute(name); }}},
        {"num_triggers_left",
         {true,
          [this]()
          {
              this->detector_ptr->getNumberOfTriggersLeft();
              return true;
          },
          [this](std::string name) { this->add_num_triggers_left_dynamic_attribute(name); }}},
        {"power_chip",
         {true,
          [this]()
          {
              this->detector_ptr->getPowerChip();
              return true;
          },
          [this](std::string name) { this->add_power_chip_dynamic_attribute(name); }}},
        {"readout_speed",
         {true,
          [this]()
          {
              auto list = this->detector_ptr->getReadoutSpeedList();
              this->readoutSpeedAdapter_ptr = std::make_unique<SlsTangoEnumAdapter<speedLevel>>(list);
              return true;
          },
          [this](std::string name)
          { this->add_readout_speed_dynamic_attribute(name, this->readoutSpeedAdapter_ptr); }}},
        {"temperature_adc",
         {true,
          [this]()
          {
              this->detector_ptr->getTemperature(dacIndex::TEMPERATURE_ADC);
              return true;
          },
          [this](std::string name) { this->add_temperature_adc_dynamic_attribute(name); }}},
        {"temperature_fpgaext",
         {true,
          [this]()
          {
              this->detector_ptr->getTemperature(dacIndex::TEMPERATURE_FPGAEXT);
              return true;
          },
          [this](std::string name) { this->add_temperature_fpgaext_dynamic_attribute(name); }}},
        {"temperature_10ge",
         {true,
          [this]()
          {
              this->detector_ptr->getTemperature(dacIndex::TEMPERATURE_10GE);
              return true;
          },
          [this](std::string name) { this->add_temperature_10ge_dynamic_attribute(name); }}},
        {"temperature_dcdc",
         {true,
          [this]()
          {
              this->detector_ptr->getTemperature(dacIndex::TEMPERATURE_DCDC);
              return true;
          },
          [this](std::string name) { this->add_temperature_dcdc_dynamic_attribute(name); }}},
        {"temperature_sodl",
         {true,
          [this]()
          {
              this->detector_ptr->getTemperature(dacIndex::TEMPERATURE_SODL);
              return true;
          },
          [this](std::string name) { this->add_temperature_sodl_dynamic_attribute(name); }}},
        {"temperature_sodr",
         {true,
          [this]()
          {
              this->detector_ptr->getTemperature(dacIndex::TEMPERATURE_SODR);
              return true;
          },
          [this](std::string name) { this->add_temperature_sodr_dynamic_attribute(name); }}},
        {"temperature_fpga2",
         {true,
          [this]()
          {
              this->detector_ptr->getTemperature(dacIndex::TEMPERATURE_FPGA2);
              return true;
          },
          [this](std::string name) { this->add_temperature_fpga2_dynamic_attribute(name); }}},
        {"temperature_fpga3",
         {true,
          [this]()
          {
              this->detector_ptr->getTemperature(dacIndex::TEMPERATURE_FPGA3);
              return true;
          },
          [this](std::string name) { this->add_temperature_fpga3_dynamic_attribute(name); }}},
        {"tengiga",
         {true,
          [this]()
          {
              this->detector_ptr->getTenGiga();
              return true;
          },
          [this](std::string name) { this->add_tengiga_dynamic_attribute(name); }}},
        {"timing_mode",
         {true,
          [this]()
          {
              auto list = this->detector_ptr->getTimingModeList();
              this->timingModeAdapter_ptr = std::make_unique<SlsTangoEnumAdapter<timingMode>>(list);
              return true;
          },
          [this](std::string name) { this->add_timing_mode_dynamic_attribute(name, this->timingModeAdapter_ptr); }}},
        {"detector_setting",
         {true,
          [this]()
          {
              auto list = this->detector_ptr->getSettingsList();
              this->detectorSettingsAdapter_ptr = std::make_unique<SlsTangoEnumAdapter<detectorSettings>>(list);
              // [Eiger] Use threshold command. Settings loaded from file found
              // in settingspath
              return this->detector_ptr->getDetectorType().front() != detectorType::EIGER;
          },
          [this](std::string name)
          { this->add_detector_setting_dynamic_attribute(name, this->detectorSettingsAdapter_ptr); }}}};
    map<std::string, attribute_info> commandsInfo = {
        {"load_trimbits",
         {true,
          [this]()
          {
              auto detector_type = this->detector_ptr->getDetectorType().front();
              return (detector_type == detectorType::EIGER) || (detector_type == detectorType::MYTHEN3);
          },
          [this](std::string name) { this->add_load_trimbits_dynamic_command(name, true); }}}};
    /*
     * Also the list of available values for the same attribute is detector
     * dependent. Thus, this should be determined at runtime as well. Moreover,
     * the tango enums always start from 0 and increase by one, while the sls
     * enums can have different values. Thus, we need to keep a mapping between
     * the tango enum values and the sls enum values.
     */
    std::unique_ptr<SlsTangoEnumAdapter<speedLevel>> readoutSpeedAdapter_ptr;
    std::unique_ptr<SlsTangoEnumAdapter<detectorSettings>> detectorSettingsAdapter_ptr;
    std::unique_ptr<SlsTangoEnumAdapter<timingMode>> timingModeAdapter_ptr;
    std::unique_ptr<SlsTangoEnumAdapter<fileFormat>> fileFormatAdapter_ptr;
    std::unique_ptr<SlsTangoEnumAdapter<runStatus>> detStatusAdapter_ptr;
    std::unique_ptr<SlsTangoEnumAdapter<runStatus>> recStatusAdapter_ptr;
    /* clang-format off */
/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::Data Members

//	Device property data members
public:
	//	ConfigurationPathDevString:	Config file for Detector and Receiver objects from the slsDetectorPackage.
	std::string	configurationPathDevString;
	//	DetectorId:	Detector shared memory id Default value is 0. Can be set to more values for multiple detectors.It is important only if you are controlling multiple detectors from the same pc.
	Tango::DevLong	detectorId;
	//	GainMapPaths:	Gain map files for each module.
	std::vector<std::string>	gainMapPaths;
	//	PixelMaskPaths:	Pixel map files for each module.
	std::vector<std::string>	pixelMaskPaths;
	//	ReceiverPort:	Port for an slsReceiver to run
	Tango::DevULong	receiverPort;
	//	ReceiverExecutablePath:	Path to slsReceiver executable to run on startup (if enabled).
	//  Keep empty to use the embedded slsReceiver.
	//  Default slsReceiver path is: /usr/local/bin/slsReceiver
	std::string	receiverExecutablePath;
	//	StartReceiverOnStartup:	Enable to run slsReceiver on startup of the TangoDS.
	Tango::DevBoolean	startReceiverOnStartup;

	bool	mandatoryNotDefined;

//	Attribute data members
public:
	Tango::DevLong64	*attr_acquisition_index_read;
	Tango::DevString	*attr_detector_type_read;
	Tango::DevLong	*attr_dynamic_range_read;
	Tango::DevDouble	*attr_exptime_read;
	Tango::DevString	*attr_file_name_read;
	Tango::DevString	*attr_file_name_prefix_read;
	Tango::DevBoolean	*attr_file_overwrite_read;
	Tango::DevString	*attr_file_path_read;
	Tango::DevBoolean	*attr_file_write_read;
	Tango::DevLong64	*attr_firmware_version_read;
	Tango::DevLong	*attr_high_voltage_read;
	Tango::DevString	*attr_hostname_read;
	Tango::DevBoolean	*attr_master_file_write_read;
	Tango::DevLong64	*attr_num_frames_read;
	Tango::DevLong	*attr_num_frames_per_file_read;
	Tango::DevLong64	*attr_num_triggers_read;
	Tango::DevString	*attr_package_version_read;
	Tango::DevDouble	*attr_period_read;
	Tango::DevBoolean	*attr_rx_zmq_data_stream_read;
	Tango::DevLong	*attr_temperature_fpga_read;
	Tango::DevLong64	*attr_num_missing_packets_read;

//	Constructors and destructors
public:
	/**
	 * Constructs a newly device object.
	 *
	 *	@param cl	Class.
	 *	@param s 	Device Name
	 */
	SlsDetectorControl(Tango::DeviceClass *cl,std::string &s);
	/**
	 * Constructs a newly device object.
	 *
	 *	@param cl	Class.
	 *	@param s 	Device Name
	 */
	SlsDetectorControl(Tango::DeviceClass *cl,const char *s);
	/**
	 * Constructs a newly device object.
	 *
	 *	@param cl	Class.
	 *	@param s 	Device name
	 *	@param d	Device description.
	 */
	SlsDetectorControl(Tango::DeviceClass *cl,const char *s,const char *d);
	/**
	 * The device object destructor.
	 */
	~SlsDetectorControl();


//	Miscellaneous methods
public:
	/*
	 *	will be called at device destruction or at init command.
	 */
	void delete_device();
	/*
	 *	Initialize the device
	 */
	virtual void init_device();
	/*
	 *	Read the device properties from database
	 */
	void get_device_property();
	/*
	 *	Always executed method before execution command method.
	 */
	virtual void always_executed_hook();

	/*
	 *	Check if mandatory property has been set
	 */
	 void check_mandatory_property(Tango::DbDatum &class_prop, Tango::DbDatum &dev_prop);

//	Attribute methods
public:
	//--------------------------------------------------------
	/*
	 *	Method      : SlsDetectorControl::read_attr_hardware()
	 * Description:  Hardware acquisition for attributes.
	 */
	//--------------------------------------------------------
	virtual void read_attr_hardware(std::vector<long> &attr_list);
	//--------------------------------------------------------
	/*
	 *	Method      : SlsDetectorControl::write_attr_hardware()
	 * Description:  Hardware writing for attributes.
	 */
	//--------------------------------------------------------
	virtual void write_attr_hardware(std::vector<long> &attr_list);

/**
 *	Attribute acquisition_index related methods
 *
 *
 *	Data type:  Tango::DevLong64
 *	Attr type:	Scalar
 */
	virtual void read_acquisition_index(Tango::Attribute &attr);
	virtual void write_acquisition_index(Tango::WAttribute &attr);
	virtual bool is_acquisition_index_allowed(Tango::AttReqType type);
/**
 *	Attribute detector_type related methods
 *
 *
 *	Data type:  Tango::DevString
 *	Attr type:	Scalar
 */
	virtual void read_detector_type(Tango::Attribute &attr);
	virtual bool is_detector_type_allowed(Tango::AttReqType type);
/**
 *	Attribute dynamic_range related methods
 *
 *
 *	Data type:  Tango::DevLong
 *	Attr type:	Scalar
 */
	virtual void read_dynamic_range(Tango::Attribute &attr);
	virtual void write_dynamic_range(Tango::WAttribute &attr);
	virtual bool is_dynamic_range_allowed(Tango::AttReqType type);
/**
 *	Attribute exptime related methods
 *
 *
 *	Data type:  Tango::DevDouble
 *	Attr type:	Scalar
 */
	virtual void read_exptime(Tango::Attribute &attr);
	virtual void write_exptime(Tango::WAttribute &attr);
	virtual bool is_exptime_allowed(Tango::AttReqType type);
/**
 *	Attribute file_name related methods
 *
 *
 *	Data type:  Tango::DevString
 *	Attr type:	Scalar
 */
	virtual void read_file_name(Tango::Attribute &attr);
	virtual bool is_file_name_allowed(Tango::AttReqType type);
/**
 *	Attribute file_name_prefix related methods
 *
 *
 *	Data type:  Tango::DevString
 *	Attr type:	Scalar
 */
	virtual void read_file_name_prefix(Tango::Attribute &attr);
	virtual void write_file_name_prefix(Tango::WAttribute &attr);
	virtual bool is_file_name_prefix_allowed(Tango::AttReqType type);
/**
 *	Attribute file_overwrite related methods
 *
 *
 *	Data type:  Tango::DevBoolean
 *	Attr type:	Scalar
 */
	virtual void read_file_overwrite(Tango::Attribute &attr);
	virtual void write_file_overwrite(Tango::WAttribute &attr);
	virtual bool is_file_overwrite_allowed(Tango::AttReqType type);
/**
 *	Attribute file_path related methods
 *
 *
 *	Data type:  Tango::DevString
 *	Attr type:	Scalar
 */
	virtual void read_file_path(Tango::Attribute &attr);
	virtual void write_file_path(Tango::WAttribute &attr);
	virtual bool is_file_path_allowed(Tango::AttReqType type);
/**
 *	Attribute file_write related methods
 *
 *
 *	Data type:  Tango::DevBoolean
 *	Attr type:	Scalar
 */
	virtual void read_file_write(Tango::Attribute &attr);
	virtual void write_file_write(Tango::WAttribute &attr);
	virtual bool is_file_write_allowed(Tango::AttReqType type);
/**
 *	Attribute firmware_version related methods
 *
 *
 *	Data type:  Tango::DevLong64
 *	Attr type:	Scalar
 */
	virtual void read_firmware_version(Tango::Attribute &attr);
	virtual bool is_firmware_version_allowed(Tango::AttReqType type);
/**
 *	Attribute high_voltage related methods
 *
 *
 *	Data type:  Tango::DevLong
 *	Attr type:	Scalar
 */
	virtual void read_high_voltage(Tango::Attribute &attr);
	virtual void write_high_voltage(Tango::WAttribute &attr);
	virtual bool is_high_voltage_allowed(Tango::AttReqType type);
/**
 *	Attribute hostname related methods
 *
 *
 *	Data type:  Tango::DevString
 *	Attr type:	Scalar
 */
	virtual void read_hostname(Tango::Attribute &attr);
	virtual bool is_hostname_allowed(Tango::AttReqType type);
/**
 *	Attribute master_file_write related methods
 *
 *
 *	Data type:  Tango::DevBoolean
 *	Attr type:	Scalar
 */
	virtual void read_master_file_write(Tango::Attribute &attr);
	virtual void write_master_file_write(Tango::WAttribute &attr);
	virtual bool is_master_file_write_allowed(Tango::AttReqType type);
/**
 *	Attribute num_frames related methods
 *
 *
 *	Data type:  Tango::DevLong64
 *	Attr type:	Scalar
 */
	virtual void read_num_frames(Tango::Attribute &attr);
	virtual void write_num_frames(Tango::WAttribute &attr);
	virtual bool is_num_frames_allowed(Tango::AttReqType type);
/**
 *	Attribute num_frames_per_file related methods
 *
 *
 *	Data type:  Tango::DevLong
 *	Attr type:	Scalar
 */
	virtual void read_num_frames_per_file(Tango::Attribute &attr);
	virtual void write_num_frames_per_file(Tango::WAttribute &attr);
	virtual bool is_num_frames_per_file_allowed(Tango::AttReqType type);
/**
 *	Attribute num_triggers related methods
 *
 *
 *	Data type:  Tango::DevLong64
 *	Attr type:	Scalar
 */
	virtual void read_num_triggers(Tango::Attribute &attr);
	virtual void write_num_triggers(Tango::WAttribute &attr);
	virtual bool is_num_triggers_allowed(Tango::AttReqType type);
/**
 *	Attribute package_version related methods
 *
 *
 *	Data type:  Tango::DevString
 *	Attr type:	Scalar
 */
	virtual void read_package_version(Tango::Attribute &attr);
	virtual bool is_package_version_allowed(Tango::AttReqType type);
/**
 *	Attribute period related methods
 *
 *
 *	Data type:  Tango::DevDouble
 *	Attr type:	Scalar
 */
	virtual void read_period(Tango::Attribute &attr);
	virtual void write_period(Tango::WAttribute &attr);
	virtual bool is_period_allowed(Tango::AttReqType type);
/**
 *	Attribute rx_zmq_data_stream related methods
 *
 *
 *	Data type:  Tango::DevBoolean
 *	Attr type:	Scalar
 */
	virtual void read_rx_zmq_data_stream(Tango::Attribute &attr);
	virtual void write_rx_zmq_data_stream(Tango::WAttribute &attr);
	virtual bool is_rx_zmq_data_stream_allowed(Tango::AttReqType type);
/**
 *	Attribute temperature_fpga related methods
 *
 *
 *	Data type:  Tango::DevLong
 *	Attr type:	Scalar
 */
	virtual void read_temperature_fpga(Tango::Attribute &attr);
	virtual bool is_temperature_fpga_allowed(Tango::AttReqType type);
/**
 *	Attribute num_missing_packets related methods
 *
 *
 *	Data type:  Tango::DevLong64
 *	Attr type:	Spectrum max = 2
 */
	virtual void read_num_missing_packets(Tango::Attribute &attr);
	virtual bool is_num_missing_packets_allowed(Tango::AttReqType type);

//	Dynamic attribute methods
public:

	/**
	 *	Attribute adc_phase related methods
	 *
	 *
	 *	Data type:  Tango::DevLong
	 *	Attr type:	Scalar
	 */
	virtual void read_adc_phase(Tango::Attribute &attr);
	virtual void write_adc_phase(Tango::WAttribute &attr);
	virtual bool is_adc_phase_allowed(Tango::AttReqType type);
	void add_adc_phase_dynamic_attribute(std::string attname);
	void remove_adc_phase_dynamic_attribute(std::string attname);
	Tango::DevLong *get_adc_phase_data_ptr(std::string &name);
	map<std::string,Tango::DevLong>	   adc_phase_data;

	/**
	 *	Attribute delay_after_trigger related methods
	 *
	 *
	 *	Data type:  Tango::DevDouble
	 *	Attr type:	Scalar
	 */
	virtual void read_delay_after_trigger(Tango::Attribute &attr);
	virtual void write_delay_after_trigger(Tango::WAttribute &attr);
	virtual bool is_delay_after_trigger_allowed(Tango::AttReqType type);
	void add_delay_after_trigger_dynamic_attribute(std::string attname);
	void remove_delay_after_trigger_dynamic_attribute(std::string attname);
	Tango::DevDouble *get_delay_after_trigger_data_ptr(std::string &name);
	map<std::string,Tango::DevDouble>	   delay_after_trigger_data;

	/**
	 *	Attribute detector_setting related methods
	 *
	 *
	 *	Data type:  Tango::DevEnum
	 *	Attr type:	Scalar
	 */
	virtual void read_detector_setting(Tango::Attribute &attr);
	virtual void write_detector_setting(Tango::WAttribute &attr);
	virtual bool is_detector_setting_allowed(Tango::AttReqType type);
	void add_detector_setting_dynamic_attribute(std::string attname);
	void remove_detector_setting_dynamic_attribute(std::string attname);
	Tango::DevEnum *get_detector_setting_data_ptr(std::string &name);
	map<std::string,Tango::DevEnum>	   detector_setting_data;

	/**
	 *	Attribute detector_status related methods
	 *
	 *
	 *	Data type:  Tango::DevEnum
	 *	Attr type:	Scalar
	 */
	virtual void read_detector_status(Tango::Attribute &attr);
	virtual bool is_detector_status_allowed(Tango::AttReqType type);
	void add_detector_status_dynamic_attribute(std::string attname);
	void remove_detector_status_dynamic_attribute(std::string attname);
	Tango::DevEnum *get_detector_status_data_ptr(std::string &name);
	map<std::string,Tango::DevEnum>	   detector_status_data;

	/**
	 *	Attribute file_format related methods
	 *
	 *
	 *	Data type:  Tango::DevEnum
	 *	Attr type:	Scalar
	 */
	virtual void read_file_format(Tango::Attribute &attr);
	virtual void write_file_format(Tango::WAttribute &attr);
	virtual bool is_file_format_allowed(Tango::AttReqType type);
	void add_file_format_dynamic_attribute(std::string attname);
	void remove_file_format_dynamic_attribute(std::string attname);
	Tango::DevEnum *get_file_format_data_ptr(std::string &name);
	map<std::string,Tango::DevEnum>	   file_format_data;

	/**
	 *	Attribute num_frames_left related methods
	 *
	 *
	 *	Data type:  Tango::DevLong64
	 *	Attr type:	Scalar
	 */
	virtual void read_num_frames_left(Tango::Attribute &attr);
	virtual bool is_num_frames_left_allowed(Tango::AttReqType type);
	void add_num_frames_left_dynamic_attribute(std::string attname);
	void remove_num_frames_left_dynamic_attribute(std::string attname);
	Tango::DevLong64 *get_num_frames_left_data_ptr(std::string &name);
	map<std::string,Tango::DevLong64>	   num_frames_left_data;

	/**
	 *	Attribute num_triggers_left related methods
	 *
	 *
	 *	Data type:  Tango::DevLong
	 *	Attr type:	Scalar
	 */
	virtual void read_num_triggers_left(Tango::Attribute &attr);
	virtual bool is_num_triggers_left_allowed(Tango::AttReqType type);
	void add_num_triggers_left_dynamic_attribute(std::string attname);
	void remove_num_triggers_left_dynamic_attribute(std::string attname);
	Tango::DevLong *get_num_triggers_left_data_ptr(std::string &name);
	map<std::string,Tango::DevLong>	   num_triggers_left_data;

	/**
	 *	Attribute power_chip related methods
	 *
	 *
	 *	Data type:  Tango::DevBoolean
	 *	Attr type:	Scalar
	 */
	virtual void read_power_chip(Tango::Attribute &attr);
	virtual void write_power_chip(Tango::WAttribute &attr);
	virtual bool is_power_chip_allowed(Tango::AttReqType type);
	void add_power_chip_dynamic_attribute(std::string attname);
	void remove_power_chip_dynamic_attribute(std::string attname);
	Tango::DevBoolean *get_power_chip_data_ptr(std::string &name);
	map<std::string,Tango::DevBoolean>	   power_chip_data;

	/**
	 *	Attribute readout_speed related methods
	 *
	 *
	 *	Data type:  Tango::DevEnum
	 *	Attr type:	Scalar
	 */
	virtual void read_readout_speed(Tango::Attribute &attr);
	virtual void write_readout_speed(Tango::WAttribute &attr);
	virtual bool is_readout_speed_allowed(Tango::AttReqType type);
	void add_readout_speed_dynamic_attribute(std::string attname);
	void remove_readout_speed_dynamic_attribute(std::string attname);
	Tango::DevEnum *get_readout_speed_data_ptr(std::string &name);
	map<std::string,Tango::DevEnum>	   readout_speed_data;

	/**
	 *	Attribute receiver_status related methods
	 *
	 *
	 *	Data type:  Tango::DevEnum
	 *	Attr type:	Scalar
	 */
	virtual void read_receiver_status(Tango::Attribute &attr);
	virtual bool is_receiver_status_allowed(Tango::AttReqType type);
	void add_receiver_status_dynamic_attribute(std::string attname);
	void remove_receiver_status_dynamic_attribute(std::string attname);
	Tango::DevEnum *get_receiver_status_data_ptr(std::string &name);
	map<std::string,Tango::DevEnum>	   receiver_status_data;

	/**
	 *	Attribute temperature_10ge related methods
	 *
	 *
	 *	Data type:  Tango::DevLong
	 *	Attr type:	Scalar
	 */
	virtual void read_temperature_10ge(Tango::Attribute &attr);
	virtual bool is_temperature_10ge_allowed(Tango::AttReqType type);
	void add_temperature_10ge_dynamic_attribute(std::string attname);
	void remove_temperature_10ge_dynamic_attribute(std::string attname);
	Tango::DevLong *get_temperature_10ge_data_ptr(std::string &name);
	map<std::string,Tango::DevLong>	   temperature_10ge_data;

	/**
	 *	Attribute temperature_adc related methods
	 *
	 *
	 *	Data type:  Tango::DevLong
	 *	Attr type:	Scalar
	 */
	virtual void read_temperature_adc(Tango::Attribute &attr);
	virtual bool is_temperature_adc_allowed(Tango::AttReqType type);
	void add_temperature_adc_dynamic_attribute(std::string attname);
	void remove_temperature_adc_dynamic_attribute(std::string attname);
	Tango::DevLong *get_temperature_adc_data_ptr(std::string &name);
	map<std::string,Tango::DevLong>	   temperature_adc_data;

	/**
	 *	Attribute temperature_dcdc related methods
	 *
	 *
	 *	Data type:  Tango::DevLong
	 *	Attr type:	Scalar
	 */
	virtual void read_temperature_dcdc(Tango::Attribute &attr);
	virtual bool is_temperature_dcdc_allowed(Tango::AttReqType type);
	void add_temperature_dcdc_dynamic_attribute(std::string attname);
	void remove_temperature_dcdc_dynamic_attribute(std::string attname);
	Tango::DevLong *get_temperature_dcdc_data_ptr(std::string &name);
	map<std::string,Tango::DevLong>	   temperature_dcdc_data;

	/**
	 *	Attribute temperature_fpga2 related methods
	 *
	 *
	 *	Data type:  Tango::DevLong
	 *	Attr type:	Scalar
	 */
	virtual void read_temperature_fpga2(Tango::Attribute &attr);
	virtual bool is_temperature_fpga2_allowed(Tango::AttReqType type);
	void add_temperature_fpga2_dynamic_attribute(std::string attname);
	void remove_temperature_fpga2_dynamic_attribute(std::string attname);
	Tango::DevLong *get_temperature_fpga2_data_ptr(std::string &name);
	map<std::string,Tango::DevLong>	   temperature_fpga2_data;

	/**
	 *	Attribute temperature_fpga3 related methods
	 *
	 *
	 *	Data type:  Tango::DevLong
	 *	Attr type:	Scalar
	 */
	virtual void read_temperature_fpga3(Tango::Attribute &attr);
	virtual bool is_temperature_fpga3_allowed(Tango::AttReqType type);
	void add_temperature_fpga3_dynamic_attribute(std::string attname);
	void remove_temperature_fpga3_dynamic_attribute(std::string attname);
	Tango::DevLong *get_temperature_fpga3_data_ptr(std::string &name);
	map<std::string,Tango::DevLong>	   temperature_fpga3_data;

	/**
	 *	Attribute temperature_fpgaext related methods
	 *
	 *
	 *	Data type:  Tango::DevLong
	 *	Attr type:	Scalar
	 */
	virtual void read_temperature_fpgaext(Tango::Attribute &attr);
	virtual bool is_temperature_fpgaext_allowed(Tango::AttReqType type);
	void add_temperature_fpgaext_dynamic_attribute(std::string attname);
	void remove_temperature_fpgaext_dynamic_attribute(std::string attname);
	Tango::DevLong *get_temperature_fpgaext_data_ptr(std::string &name);
	map<std::string,Tango::DevLong>	   temperature_fpgaext_data;

	/**
	 *	Attribute temperature_sodl related methods
	 *
	 *
	 *	Data type:  Tango::DevLong
	 *	Attr type:	Scalar
	 */
	virtual void read_temperature_sodl(Tango::Attribute &attr);
	virtual bool is_temperature_sodl_allowed(Tango::AttReqType type);
	void add_temperature_sodl_dynamic_attribute(std::string attname);
	void remove_temperature_sodl_dynamic_attribute(std::string attname);
	Tango::DevLong *get_temperature_sodl_data_ptr(std::string &name);
	map<std::string,Tango::DevLong>	   temperature_sodl_data;

	/**
	 *	Attribute temperature_sodr related methods
	 *
	 *
	 *	Data type:  Tango::DevLong
	 *	Attr type:	Scalar
	 */
	virtual void read_temperature_sodr(Tango::Attribute &attr);
	virtual bool is_temperature_sodr_allowed(Tango::AttReqType type);
	void add_temperature_sodr_dynamic_attribute(std::string attname);
	void remove_temperature_sodr_dynamic_attribute(std::string attname);
	Tango::DevLong *get_temperature_sodr_data_ptr(std::string &name);
	map<std::string,Tango::DevLong>	   temperature_sodr_data;

	/**
	 *	Attribute tengiga related methods
	 *
	 *
	 *	Data type:  Tango::DevBoolean
	 *	Attr type:	Scalar
	 */
	virtual void read_tengiga(Tango::Attribute &attr);
	virtual void write_tengiga(Tango::WAttribute &attr);
	virtual bool is_tengiga_allowed(Tango::AttReqType type);
	void add_tengiga_dynamic_attribute(std::string attname);
	void remove_tengiga_dynamic_attribute(std::string attname);
	Tango::DevBoolean *get_tengiga_data_ptr(std::string &name);
	map<std::string,Tango::DevBoolean>	   tengiga_data;

	/**
	 *	Attribute timing_mode related methods
	 *
	 *
	 *	Data type:  Tango::DevEnum
	 *	Attr type:	Scalar
	 */
	virtual void read_timing_mode(Tango::Attribute &attr);
	virtual void write_timing_mode(Tango::WAttribute &attr);
	virtual bool is_timing_mode_allowed(Tango::AttReqType type);
	void add_timing_mode_dynamic_attribute(std::string attname);
	void remove_timing_mode_dynamic_attribute(std::string attname);
	Tango::DevEnum *get_timing_mode_data_ptr(std::string &name);
	map<std::string,Tango::DevEnum>	   timing_mode_data;

	/**
	 *	Attribute threshold_energy related methods
	 *
	 *
	 *	Data type:  Tango::DevLong
	 *	Attr type:	Spectrum max = 3
	 */
	virtual void read_threshold_energy(Tango::Attribute &attr);
	virtual void write_threshold_energy(Tango::WAttribute &attr);
	virtual bool is_threshold_energy_allowed(Tango::AttReqType type);
	void add_threshold_energy_dynamic_attribute(std::string attname, Tango::DevLong *ptr=NULL);
	void remove_threshold_energy_dynamic_attribute(std::string attname, bool free_it=true);
	Tango::DevLong *get_threshold_energy_data_ptr(std::string &name);
	map<std::string,Tango::DevLong *>	   threshold_energy_data;

	//--------------------------------------------------------
	/**
	 *	Method      : SlsDetectorControl::add_dynamic_attributes()
	 * Description:  Add dynamic attributes if any.
	 */
	//--------------------------------------------------------
	void add_dynamic_attributes();




//	Command related methods
public:
	/**
	 *	Command start_acquire related method
	 *
	 *
	 */
	virtual void start_acquire();
	virtual bool is_start_acquire_allowed(const CORBA::Any &any);
	/**
	 *	Command start_detector related method
	 *
	 *
	 */
	virtual void start_detector();
	virtual bool is_start_detector_allowed(const CORBA::Any &any);
	/**
	 *	Command start_receiver related method
	 *
	 *
	 */
	virtual void start_receiver();
	virtual bool is_start_receiver_allowed(const CORBA::Any &any);
	/**
	 *	Command stop_acquire related method
	 *
	 *
	 */
	virtual void stop_acquire();
	virtual bool is_stop_acquire_allowed(const CORBA::Any &any);
	/**
	 *	Command stop_detector related method
	 *
	 *
	 */
	virtual void stop_detector();
	virtual bool is_stop_detector_allowed(const CORBA::Any &any);
	/**
	 *	Command stop_receiver related method
	 *
	 *
	 */
	virtual void stop_receiver();
	virtual bool is_stop_receiver_allowed(const CORBA::Any &any);

//	Dynamic commands methods
public:
	/**
	 *	Command load_trimbits related method
	 *
	 *
	 *	@param argin
	 */
	virtual void load_trimbits(Tango::DevString argin,Tango::Command &command);
	virtual bool is_load_trimbits_allowed(const CORBA::Any &any);
	void add_load_trimbits_dynamic_command(std::string cmdname, bool device);
	void remove_load_trimbits_dynamic_command(std::string cmdname);

	//--------------------------------------------------------
	/**
	 *	Method      : SlsDetectorControl::add_dynamic_commands()
	 * Description:  Add dynamic commands if any.
	 */
	//--------------------------------------------------------
	void add_dynamic_commands();

/*----- PROTECTED REGION ID(SlsDetectorControl::Additional Method prototypes) ENABLED START -----*/
    /* clang-format on */
    void check_stop_in_background_acquisition();
    void add_detector_status_dynamic_attribute(std::string attname,
                                               std::unique_ptr<SlsTangoEnumAdapter<runStatus>> &slsEnumAdapter_ptr);
    void add_receiver_status_dynamic_attribute(std::string attname,
                                               std::unique_ptr<SlsTangoEnumAdapter<runStatus>> &slsEnumAdapter_ptr);
    void add_readout_speed_dynamic_attribute(std::string attname,
                                             std::unique_ptr<SlsTangoEnumAdapter<speedLevel>> &slsEnumAdapter_ptr);
    void add_detector_setting_dynamic_attribute(
        std::string attname, std::unique_ptr<SlsTangoEnumAdapter<detectorSettings>> &slsEnumAdapter_ptr);
    void add_timing_mode_dynamic_attribute(std::string attname,
                                           std::unique_ptr<SlsTangoEnumAdapter<timingMode>> &slsEnumAdapter_ptr);
    void add_file_format_dynamic_attribute(std::string attname,
                                           std::unique_ptr<SlsTangoEnumAdapter<fileFormat>> &slsEnumAdapter_ptr);

    /* clang-format off */
/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::Additional Method prototypes
};

/*----- PROTECTED REGION ID(SlsDetectorControl::Additional Classes Definitions) ENABLED START -----*/
/* clang-format on */
//	Additional Classes Definitions
/* clang-format off */
/*----- PROTECTED REGION END -----*/	//	SlsDetectorControl::Additional Classes Definitions

}	//	End of namespace

#endif   //	SlsDetectorControl_H
