name: Build and Test Ubuntu Linux

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '.clang-format'
      - '.pre-commit-config.yaml'
      - 'LICENSE'
      - 'README.md'
      - 'docker/**'
  push:
    branches:
      - main
    paths-ignore:
      - '.clang-format'
      - '.pre-commit-config.yaml'
      - 'LICENSE'
      - 'README.md'
      - 'docker/**'
      - '.github/workflows/check-build-docker.yml'
  workflow_run:
    workflows: ["Check and Build Docker Images"]
    types:
      - completed

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        tango-version: [9.5.0, 10.0.0, 10.1.0]
        sls-version: [8.0.2, 9.2.0, 10.0.0]
    container:
      image: ghcr.io/slsdetectorgroup/tango-${{ matrix.tango-version }}-sls-${{ matrix.sls-version }}:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Configure CMake our repository
        # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
        # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
        run: cmake -B build

      - name: Build the repository
        run: cmake --build build -j
